### ISSUE TITLE
Windows 10: installation failed, filename too long

### ISSUE THREAD

**Issue by scorwin** [Acly/krita-ai-diffusion#101]
Installation failed because the filename was too long.  Hints?

Thanks in advance,

Steve

From client.log:

2023-11-22 00:10:18,553 ERROR [WinError 206] The filename or extension is too long: 'C:\\Users\\Administrator.DESKTOP-TTE9BN7\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux-98bf5b70a98577dcbb1227cdf4fbbf022149a1e1\\src\\controlnet_aux\\normalbae\\nets\\submodules\\efficientnet_repo\\geffnet\\activations'
Traceback (most recent call last):
  File "C:\Users\Administrator.DESKTOP-TTE9BN7\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\Administrator.DESKTOP-TTE9BN7\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 172, in _install
    await _install_if_missing(dir, self._install_custom_node, pkg, network, cb)
  File "C:\Users\Administrator.DESKTOP-TTE9BN7\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 547, in _install_if_missing
    raise e
  File "C:\Users\Administrator.DESKTOP-TTE9BN7\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 544, in _install_if_missing
    await installer(*args)
  File "C:\Users\Administrator.DESKTOP-TTE9BN7\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 244, in _install_custom_node
    await _extract_archive(pkg.name, resource_zip_path, folder.parent, cb)
  File "C:\Users\Administrator.DESKTOP-TTE9BN7\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 509, in _extract_archive
    zip_file.extractall(target)
  File "zipfile.py", line 1645, in extractall
  File "zipfile.py", line 1695, in _extract_member
FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\\Users\\Administrator.DESKTOP-TTE9BN7\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux-98bf5b70a98577dcbb1227cdf4fbbf022149a1e1\\src\\controlnet_aux\\normalbae\\nets\\submodules\\efficientnet_repo\\geffnet\\activations'
2023-11-22 00:10:18,562 ERROR Installation failed

**Comment by Acly** [comment]
Easiest way is to choose a different installation location for the server (you can select any path in the UI, it doesn't have to be a subfolder of the plugin)

I also added a fix for this yesterday, but it's not part of a release yet.

**Comment by scorwin** [comment]
Thank you!
