### ISSUE TITLE
Installation fails, pip module missing

### ISSUE THREAD

**Issue by lucaspeed72** [Acly/krita-ai-diffusion#1019]
Hi, I'm trying to reinstall ai_diffusion after a system upgrade but it seems I can't because of this error:

`2024-08-01 18:50:08,588 ERROR Installation failed
2024-08-01 18:50:08,588 INFO Found server installation v1.17.0 at /home/luca/.local/share/krita/ai_diffusion/server
2024-08-01 18:52:39,055 INFO Starting upgrade from 1.17.0 to 1.21.0
2024-08-01 18:52:39,056 INFO Backing up /home/luca/.local/share/krita/ai_diffusion/server/ComfyUI to /home/luca/.local/share/krita/ai_diffusion/server/upgrade-1.21.0/ComfyUI
2024-08-01 18:52:39,056 INFO Installation started in /home/luca/.local/share/krita/ai_diffusion/server
2024-08-01 18:52:39,252 INFO Using Python: Python 3.11.9, /home/luca/.local/share/krita/ai_diffusion/server/venv/bin/python3
2024-08-01 18:52:39,412 INFO Using pip: 
2024-08-01 18:52:39,412 INFO Using /home/luca/.local/share/krita/ai_diffusion/server/.cache/ComfyUI-14764aa2e2e2b282c4a4dffbfab4c01d3e46e8a7.zip
2024-08-01 18:52:39,412 INFO Extracting /home/luca/.local/share/krita/ai_diffusion/server/.cache/ComfyUI-14764aa2e2e2b282c4a4dffbfab4c01d3e46e8a7.zip to /home/luca/.local/share/krita/ai_diffusion/server
2024-08-01 18:52:39,473 INFO Executing /home/luca/.local/share/krita/ai_diffusion/server/venv/bin/python3 -su -m pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
2024-08-01 18:52:39,686 ERROR Error during installation: /home/luca/.local/share/krita/ai_diffusion/server/venv/bin/python3: No module named pip
Traceback (most recent call last):
  File "/home/luca/.local/share/krita/pykrita/ai_diffusion/server.py", line 266, in install
    await self._install(cb)
  File "/home/luca/.local/share/krita/pykrita/ai_diffusion/server.py", line 140, in _install
    await try_install(comfy_dir, self._install_comfy, comfy_dir, network, cb)
  File "/home/luca/.local/share/krita/pykrita/ai_diffusion/server.py", line 566, in try_install
    raise e
  File "/home/luca/.local/share/krita/pykrita/ai_diffusion/server.py", line 561, in try_install
    await installer(*args)
  File "/home/luca/.local/share/krita/pykrita/ai_diffusion/server.py", line 194, in _install_comfy
    await _execute_process("PyTorch", self._pip_install(*torch_args), self.path, cb)
  File "/home/luca/.local/share/krita/pykrita/ai_diffusion/server.py", line 555, in _execute_process
    raise Exception(_("Error during installation") + f": {errlog}")
Exception: Error during installation: /home/luca/.local/share/krita/ai_diffusion/server/venv/bin/python3: No module named pip

2024-08-01 18:52:39,687 ERROR Installation failed
2024-08-01 18:52:39,687 INFO Found server installation v1.17.0 at /home/luca/.local/share/krita/ai_diffusion/server
2024-08-01 18:52:39,687 WARNING Error during upgrade: Error during installation: /home/luca/.local/share/krita/ai_diffusion/server/venv/bin/python3: No module named pip
 - Restoring /home/luca/.local/share/krita/ai_diffusion/server/upgrade-1.21.0/ComfyUI`
 
I thought it was a python version problem, I have 3.12 but installed 3.11 too and configured the symlink in venv accordingly, the log shows it is using the 3.11 version but shows that pip is missing to and that's not true, it is in the same directory.

What to try next?

Thank you.

**Comment by Acly** [comment]
>  but shows that pip is missing to and that's not true, it is in the same directory.

Does it actually work though? I think the file in the directory is just a script which does `python3 -m pip`, and apparently that doesn't work. Can't really say why that happened, but easiest way to fix is probably to reinstall. You can make a copy of ComfyUI/models and move it back in afterwards to avoid most of the downloads.

**Comment by lucaspeed72** [comment]
A reinstall is exactly what I'm trying to do with no success.
Doing `python3 -m pip` in the directory (in the directory I am using python3.11 to avoid using the 3.12 system version) actually shows pip's commands list so I suppose it is working.

**Comment by Acly** [comment]
Are you inside the venv?

Either do
```
source .venv/bin/activate
python3 -m pip
```

or call it directly like this
```
cd .venv
bin/python3 -m pip
```

Reinstall sets up a fresh venv, which should always have working pip (as far as I know...)

**Comment by Acly** [comment]
Just delete the directory where the server is installed (called `server` by default).

**Comment by lucaspeed72** [comment]
A clean reinstall solved the problem, thank you!
