### ISSUE TITLE
Missing one or more custom node 

### ISSUE THREAD

**Issue by Cheko95** [Acly/krita-ai-diffusion#1022]
Hey i’ve one problem with comfyui custom nodes 

thank u for helping 

`2024-08-02 19:22:43,387 INFO /Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
2024-08-02 19:22:43,387 INFO warnings.warn(
2024-08-02 19:22:44,067 INFO [Prompt Server] web root: /Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/web
2024-08-02 19:22:44,387 INFO [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: /Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts[0m
2024-08-02 19:22:44,387 INFO [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-08-02 19:22:44,387 INFO [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-08-02 19:22:44,666 INFO /Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
2024-08-02 19:22:44,667 INFO warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
2024-08-02 19:22:44,727 INFO Traceback (most recent call last):
2024-08-02 19:22:44,727 INFO File "/Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/nodes.py", line 1931, in load_custom_node
2024-08-02 19:22:44,727 INFO module_spec.loader.exec_module(module)
2024-08-02 19:22:44,727 INFO File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2024-08-02 19:22:44,727 INFO File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2024-08-02 19:22:44,727 INFO File "/Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/comfyui-tooling-nodes/__init__.py", line 1, in <module>
2024-08-02 19:22:44,728 INFO from . import api, nodes, tile, region, nsfw, translation
2024-08-02 19:22:44,728 INFO File "/Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/comfyui-tooling-nodes/nsfw.py", line 77, in <module>
2024-08-02 19:22:44,728 INFO class CachedModels:
2024-08-02 19:22:44,728 INFO File "/Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/comfyui-tooling-nodes/nsfw.py", line 78, in CachedModels
2024-08-02 19:22:44,728 INFO _instance: WeakRef | None = None
2024-08-02 19:22:44,728 INFO TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
2024-08-02 19:22:44,728 INFO 
2024-08-02 19:22:44,728 INFO Cannot import /Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/comfyui-tooling-nodes module for custom nodes: unsupported operand type(s) for |: 'type' and 'NoneType'
2024-08-02 19:22:44,747 INFO 
2024-08-02 19:22:44,747 INFO Import times for custom nodes:
2024-08-02 19:22:44,747 INFO 0.0 seconds: /Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/websocket_image_save.py
2024-08-02 19:22:44,747 INFO 0.0 seconds: /Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/comfyui-inpaint-nodes
2024-08-02 19:22:44,747 INFO 0.0 seconds: /Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-08-02 19:22:44,747 INFO 0.1 seconds (IMPORT FAILED): /Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/comfyui-tooling-nodes
2024-08-02 19:22:44,747 INFO 0.4 seconds: /Users/cheikd/Library/Application Support/krita/ai_diffusion/server/ddl/ComfyUI/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-08-02 19:22:44,747 INFO 
2024-08-02 19:22:44,747 INFO Starting server
2024-08-02 19:22:44,747 INFO 
2024-08-02 19:22:44,747 INFO To see the GUI go to: http://127….`

**Comment by Acly** [comment]
#1008

**Comment by Cheko95** [comment]
Sorry for thé double post,
And thank you a lot that work like a charm
