### ISSUE TITLE
Version 1.21.0 install fail

### ISSUE THREAD

**Issue by Skylerky** [Acly/krita-ai-diffusion#1031]
Can help me fix to this??
Thank you
![image](https://github.com/user-attachments/assets/5f849b23-b3fc-4e7e-8b33-d5696549cea8)
![image](https://github.com/user-attachments/assets/36984700-bd20-4a58-bba3-d0d8b0cf96b7)

2024-08-04 13:20:29,093 ERROR Error during installation: ERROR: Exception:
Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\cli\base_command.py", line 105, in _run_wrapper
status = _inner_run()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\cli\base_command.py", line 96, in _inner_run
return self.run(options, args)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\cli\req_command.py", line 67, in wrapper
return func(self, options, args)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\commands\install.py", line 379, in run
requirement_set = resolver.resolve(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\resolver.py", line 95, in resolve
result = self._result = resolver.resolve(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 546, in resolve
state = resolution.resolve(requirements, max_rounds=max_rounds)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 427, in resolve
failure_causes = self._attempt_to_pin_criterion(name)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
criteria = self._get_updated_criteria(candidate)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria
self._add_to_criteria(criteria, requirement, parent=candidate)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
if not criterion.candidates:
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\structs.py", line 156, in bool
return bool(self._sequence)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\found_candidates.py", line 174, in bool
return any(self)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\found_candidates.py", line 162, in
return (c for c in iterator if id(c) not in self._incompatible_ids)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
candidate = func()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\factory.py", line 186, in _make_candidate_from_link
base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\factory.py", line 232, in _make_base_candidate_from_link
self._link_candidate_cache[link] = LinkCandidate(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 303, in init
super().init(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 158, in init
self.dist = self._prepare()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
dist = self._prepare_distribution()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\operations\prepare.py", line 527, in prepare_linked_requirement
return self._prepare_linked_requirement(req, parallel_builds)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
dist = _get_prepared_distribution(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\operations\prepare.py", line 72, in _get_prepared_distribution
abstract_dist.prepare_distribution_metadata(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
self._install_build_reqs(finder)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\distributions\sdist.py", line 126, in _install_build_reqs
build_reqs = self._get_build_requires_wheel()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
return backend.get_requires_for_build_wheel()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\utils\misc.py", line 706, in get_requires_for_build_wheel
return super().get_requires_for_build_wheel(config_settings=cs)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\pyproject_hooks_impl.py", line 166, in get_requires_for_build_wheel
return self._call_hook('get_requires_for_build_wheel', {
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\pyproject_hooks_impl.py", line 321, in _call_hook
raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 77, in build_backend
obj = import_module(mod_path)
File "importlib_init.py", line 126, in import_module
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'

Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 266, in install
await self._install(cb)
File "C:\Users\User\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 144, in _install
await install_if_missing(dir, self._install_custom_node, pkg, network, cb)
File "C:\Users\User\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 571, in install_if_missing
await try_install(path, installer, *args)
File "C:\Users\User\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 566, in try_install
raise e
File "C:\Users\User\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 561, in try_install
await installer(*args)
File "C:\Users\User\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 222, in _install_custom_node
await _execute_process(pkg.name, self._pip_install("-r", requirements_txt), folder, cb)
File "C:\Users\User\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 555, in execute_process
raise Exception(("Error during installation") + f": {errlog}")
Exception: Error during installation: ERROR: Exception:
Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\cli\base_command.py", line 105, in _run_wrapper
status = _inner_run()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\cli\base_command.py", line 96, in _inner_run
return self.run(options, args)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\cli\req_command.py", line 67, in wrapper
return func(self, options, args)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\commands\install.py", line 379, in run
requirement_set = resolver.resolve(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\resolver.py", line 95, in resolve
result = self._result = resolver.resolve(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 546, in resolve
state = resolution.resolve(requirements, max_rounds=max_rounds)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 427, in resolve
failure_causes = self._attempt_to_pin_criterion(name)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 239, in _attempt_to_pin_criterion
criteria = self._get_updated_criteria(candidate)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 230, in _get_updated_criteria
self._add_to_criteria(criteria, requirement, parent=candidate)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
if not criterion.candidates:
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\resolvelib\structs.py", line 156, in bool
return bool(self._sequence)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\found_candidates.py", line 174, in bool
return any(self)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\found_candidates.py", line 162, in
return (c for c in iterator if id(c) not in self._incompatible_ids)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
candidate = func()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\factory.py", line 186, in _make_candidate_from_link
base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\factory.py", line 232, in _make_base_candidate_from_link
self._link_candidate_cache[link] = LinkCandidate(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 303, in init
super().init(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 158, in init
self.dist = self._prepare()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 235, in _prepare
dist = self._prepare_distribution()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution
return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\operations\prepare.py", line 527, in prepare_linked_requirement
return self._prepare_linked_requirement(req, parallel_builds)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\operations\prepare.py", line 642, in _prepare_linked_requirement
dist = _get_prepared_distribution(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\operations\prepare.py", line 72, in _get_prepared_distribution
abstract_dist.prepare_distribution_metadata(
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\distributions\sdist.py", line 56, in prepare_distribution_metadata
self._install_build_reqs(finder)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\distributions\sdist.py", line 126, in _install_build_reqs
build_reqs = self._get_build_requires_wheel()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\distributions\sdist.py", line 103, in _get_build_requires_wheel
return backend.get_requires_for_build_wheel()
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_internal\utils\misc.py", line 706, in get_requires_for_build_wheel
return super().get_requires_for_build_wheel(config_settings=cs)
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\pyproject_hooks_impl.py", line 166, in get_requires_for_build_wheel
return self._call_hook('get_requires_for_build_wheel', {
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\pyproject_hooks_impl.py", line 321, in _call_hook
raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
File "C:\Users\User\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 77, in build_backend
obj = import_module(mod_path)
File "importlib_init.py", line 126, in import_module
File "", line 1050, in _gcd_import
File "", line 1027, in _find_and_load
File "", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'mesonpy'

2024-08-04 13:20:29,093 ERROR Installation failed

**Comment by Acly** [comment]
It is trying to install matplotlib, but there are currently no windows whl for latest version (3.9.1) on https://pypi.org/project/matplotlib/#files

I'm not sure why, probably have to ask them if it isn't fixed in a while

**Comment by Cal-Tech129** [comment]
Hi, sorry to say that I'm experiencing the same problem. I hope it gets resolved soon.

**Comment by AbelNavarro** [comment]
same with previous version 1.20.1.

**Comment by Acly** [comment]
I suspect it affects all new installations of any version.

You can go to your plugin install dir (usually `C:\User\<your-name>\AppData\Roaming\krita\pykrita\ai_diffusion`) and modify `server.py` with a text editor as a temporary workaround.

Add a line like here: https://github.com/Acly/krita-ai-diffusion/commit/21db0d704f8650b56db59e069e5580c41666646c

Installation should work after that.

**Comment by Davnit88** [comment]
gracias precisamente estaba revisando voy a intentar tu solucion

**Comment by Anthony-Breneliere** [comment]
I just installed krita and ai diffusion for the first time and this solved the installation issue.

But I don't think everyone will be able to change manually a line of code to apply this fix.

**Comment by Daniposuk** [comment]
I have the same problem, I installed a new krita 5.2.3 and krita_ai_diffusion-1.21.0.zip and when creating a server it threw me the same error, I tried to rewrite according to Acly server.py and reinstall ai_diffusion-1.21.0 unfortunately it doesn't work for me, the error is still reported .

**Comment by Anthony-Breneliere** [comment]
After editing server.py file, I removed the AI diffusion directory, and I pressed the install button with default components checked.
The installation worked.

**Comment by Acly** [comment]
This should be resolved now. The faulty matplotlib release was removed and installations work again. The workaround is no longer needed.

**Comment by Skylerky** [comment]
It work, Thank you

**Comment by donshark2** [comment]
please how do I remove the AI deeffusion directory and do I have to still edit the server.py? if yes, do i just copy the code and paste to the text? please I have no idea on how to go about this
