### ISSUE TITLE
Ai Image generation Face doesn't work dll load failed onnx_cpp2py_export

### ISSUE THREAD

**Issue by alperktt** [Acly/krita-ai-diffusion#1033]
```
2024-08-04 22:08:02,987 INFO model_type EPS
2024-08-04 22:08:05,082 INFO Using pytorch attention in VAE
2024-08-04 22:08:05,082 INFO Using pytorch attention in VAE
2024-08-04 22:08:11,279 INFO !!! Exception during processing!!! DLL load failed while importing onnx_cpp2py_export: The dynamic link library (DLL) initialization routine failed.
2024-08-04 22:08:11,279 INFO Traceback (most recent call last):
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 155, in insightface_loader
2024-08-04 22:08:11,279 INFO from insightface.app import FaceAnalysis
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\python\lib\site-packages\insightface\__init__.py", line 16, in <module>
2024-08-04 22:08:11,279 INFO from . import model_zoo
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\python\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
2024-08-04 22:08:11,279 INFO from .model_zoo import get_model
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
2024-08-04 22:08:11,279 INFO from .arcface_onnx import *
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\python\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
2024-08-04 22:08:11,279 INFO import onnx
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\python\lib\site-packages\onnx\__init__.py", line 77, in <module>
2024-08-04 22:08:11,279 INFO from onnx.onnx_cpp2py_export import ONNX_ML
2024-08-04 22:08:11,279 INFO ImportError: DLL load failed while importing onnx_cpp2py_export: The dynamic link library (DLL) initialization routine failed.
2024-08-04 22:08:11,279 INFO 
2024-08-04 22:08:11,279 INFO During handling of the above exception, another exception occurred:
2024-08-04 22:08:11,279 INFO 
2024-08-04 22:08:11,279 INFO Traceback (most recent call last):
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
2024-08-04 22:08:11,279 INFO output_data, output_ui = get_output_data(obj, input_data_all)
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
2024-08-04 22:08:11,279 INFO return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
2024-08-04 22:08:11,279 INFO results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 643, in load_insightface
2024-08-04 22:08:11,279 INFO return (insightface_loader(provider),)
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 157, in insightface_loader
2024-08-04 22:08:11,279 INFO raise Exception(e)
2024-08-04 22:08:11,279 INFO Exception: DLL load failed while importing onnx_cpp2py_export: The dynamic link library (DLL) initialization routine failed.
2024-08-04 22:08:11,279 INFO 
2024-08-04 22:08:11,279 INFO Prompt executed in 8.42 seconds

```

English One

Turkish one 
```

2024-08-04 22:08:02,987 INFO model_type EPS
2024-08-04 22:08:05,082 INFO Using pytorch attention in VAE
2024-08-04 22:08:05,082 INFO Using pytorch attention in VAE
2024-08-04 22:08:11,279 INFO !!! Exception during processing!!! DLL load failed while importing onnx_cpp2py_export: Devingen bağlantı kitaplığını (DLL) başlatma işlemi başarısız.
2024-08-04 22:08:11,279 INFO Traceback (most recent call last):
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 155, in insightface_loader
2024-08-04 22:08:11,279 INFO from insightface.app import FaceAnalysis
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\python\lib\site-packages\insightface\__init__.py", line 16, in <module>
2024-08-04 22:08:11,279 INFO from . import model_zoo
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\python\lib\site-packages\insightface\model_zoo\__init__.py", line 1, in <module>
2024-08-04 22:08:11,279 INFO from .model_zoo import get_model
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\python\lib\site-packages\insightface\model_zoo\model_zoo.py", line 11, in <module>
2024-08-04 22:08:11,279 INFO from .arcface_onnx import *
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\python\lib\site-packages\insightface\model_zoo\arcface_onnx.py", line 10, in <module>
2024-08-04 22:08:11,279 INFO import onnx
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\python\lib\site-packages\onnx\__init__.py", line 77, in <module>
2024-08-04 22:08:11,279 INFO from onnx.onnx_cpp2py_export import ONNX_ML
2024-08-04 22:08:11,279 INFO ImportError: DLL load failed while importing onnx_cpp2py_export: Devingen bağlantı kitaplığını (DLL) başlatma işlemi başarısız.
2024-08-04 22:08:11,279 INFO 
2024-08-04 22:08:11,279 INFO During handling of the above exception, another exception occurred:
2024-08-04 22:08:11,279 INFO 
2024-08-04 22:08:11,279 INFO Traceback (most recent call last):
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
2024-08-04 22:08:11,279 INFO output_data, output_ui = get_output_data(obj, input_data_all)
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
2024-08-04 22:08:11,279 INFO return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
2024-08-04 22:08:11,279 INFO results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 643, in load_insightface
2024-08-04 22:08:11,279 INFO return (insightface_loader(provider),)
2024-08-04 22:08:11,279 INFO File "D:\AI\Krita\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 157, in insightface_loader
2024-08-04 22:08:11,279 INFO raise Exception(e)
2024-08-04 22:08:11,279 INFO Exception: DLL load failed while importing onnx_cpp2py_export: Devingen bağlantı kitaplığını (DLL) başlatma işlemi başarısız.
2024-08-04 22:08:11,279 INFO 
2024-08-04 22:08:11,279 INFO Prompt executed in 8.42 seconds
```

**Comment by Acly** [comment]
Looks like this issue: https://github.com/onnx/onnx/issues/6267

You can try downgrading onnx. In Command Prompt paste the following:
```
D:\AI\Krita\ComfyUI\python\python.exe -m pip install onnx==1.16.1
```

**Comment by alperktt** [comment]
> Looks like this issue: [onnx/onnx#6267](https://github.com/onnx/onnx/issues/6267)
> 
> You can try downgrading onnx. In Command Prompt paste the following:
> 
> ```
> D:\AI\Krita\ComfyUI\python\python.exe -m pip install onnx==1.16.1
> ```

It did work thanks
