### ISSUE TITLE
[Bug] controlNet not working when on Animation

### ISSUE THREAD

**Issue by guzuligo** [Acly/krita-ai-diffusion#1055]
Whenever I add controlnet, I get internal assertion failed error:
![image](https://github.com/user-attachments/assets/85b1729d-5667-4149-8a1e-f6bbe8b4e1d5)

```
Traceback (most recent call last):
  File "C:\Users\x\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 1072, in _report_errors
    return await coro
  File "C:\Users\x\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 978, in _generate_batch
    inputs = self._prepare_input(canvas, seed, frame)
  File "C:\Users\x\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 921, in _prepare_input
    conditioning, _ = process_regions(m.regions, bounds, self._model.layers.root, time=time)
  File "C:\Users\x\AppData\Roaming\krita\pykrita\ai_diffusion\region.py", line 392, in process_regions
    control=[c.to_api(bounds, time) for c in list(root.control) + parent_control],
  File "C:\Users\x\AppData\Roaming\krita\pykrita\ai_diffusion\region.py", line 392, in <listcomp>
    control=[c.to_api(bounds, time) for c in list(root.control) + parent_control],
  File "C:\Users\x\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 104, in to_api
    image = layer.get_pixels(bounds, time)
  File "C:\Users\x\AppData\Roaming\krita\pykrita\ai_diffusion\layer.py", line 158, in get_pixels
    assert data is not None and data.size() >= bounds.extent.pixel_count * 4
AssertionError
```

**Comment by Acly** [comment]
Are there any frames in the animation where they control layer doesn't have a keyframe?

**Comment by guzuligo** [comment]
No.

Even if all layers have keyframes, it still doesn't work.
