### ISSUE TITLE
Flux inpainting with "refine (custom)" and less than 100% strength fails with assertion

### ISSUE THREAD

**Issue by StableLlama** [Acly/krita-ai-diffusion#1132]
Using Flux, selecting something of the image, setting the strength to something below 100% and using "Refine (custom)" doesn't work with `Error: Internal assertion failed []`

Looking at the client.log it seems that this is the relevant part:
```
2024-09-01 09:39:45,992 INFO Found LoRA model hyper for SD XL: Hyper-SDXL-8steps-CFG-lora.safetensors
2024-09-01 09:39:45,993 INFO Optional LoRA model lcm for SD 1.5 not found (search path: lcm-lora-sdv1-5.safetensors, lcm/sd1.5/pytorch_lora_weights.safetensors)
2024-09-01 09:39:45,993 INFO Optional LoRA model lcm for SD XL not found (search path: lcm-lora-sdxl.safetensors, lcm/sdxl/pytorch_lora_weights.safetensors)
2024-09-01 09:39:45,993 INFO Found LoRA model face for SD 1.5: faceid/ip-adapter-faceid-plus_sd15_lora.safetensors
2024-09-01 09:39:45,994 INFO Found LoRA model face for SD XL: faceid/ip-adapter-faceid-plusv2_sdxl_lora.safetensors
2024-09-01 09:39:45,994 INFO Optional LoRA model lightning for SD XL not found (search path: sdxl_lightning_8step_lora)
2024-09-01 09:39:46,543 INFO SD 1.5: missing 4 models
2024-09-01 09:39:46,543 INFO SD XL: supported
2024-09-01 09:39:46,543 INFO SD 3: missing 1 models
2024-09-01 09:39:46,543 INFO Flux: supported
2024-09-01 10:04:35,387 ERROR Error: Internal assertion failed []
Traceback (most recent call last):
  File "/home/cm/.local/share/krita/pykrita/ai_diffusion/model.py", line 1072, in _report_errors
    return await coro
  File "/home/cm/.local/share/krita/pykrita/ai_diffusion/model.py", line 206, in enqueue_jobs
    await self._enqueue_job(job, input)
  File "/home/cm/.local/share/krita/pykrita/ai_diffusion/model.py", line 212, in _enqueue_job
    job.id = await client.enqueue(input, self.queue_front)
  File "/home/cm/.local/share/krita/pykrita/ai_diffusion/comfy_client.py", line 168, in enqueue
    workflow = create_workflow(work, self.models)
  File "/home/cm/.local/share/krita/pykrita/ai_diffusion/workflow.py", line 1179, in create
    return refine_region(
  File "/home/cm/.local/share/krita/pykrita/ai_diffusion/workflow.py", line 824, in refine_region
    inpaint_patch = w.load_fooocus_inpaint(**models.fooocus_inpaint)
  File "/home/cm/.local/share/krita/pykrita/ai_diffusion/client.py", line 187, in fooocus_inpaint
    assert self.version is SDVersion.sdxl
AssertionError
```

**Comment by Acly** [comment]
This should no longer happen in latest version (v1.23.0)

In prior version you need to untick "Seamless" option (it does not exist for Flux)
