### ISSUE TITLE
LCM LORA SDXL not found

### ISSUE THREAD

**Issue by gerroon** [Acly/krita-ai-diffusion#118]
I use custom ComfyUI server on Windows 11, Krita 5.2.1, Ai-Diffusion 1.7.1 . I can use generate but when I want to use live it throws this error with Digital Artwork XL.

The lora is there (I put additional brackets to make it clear in the report) as explained in the doc, not sure why it cant find it

```
ComfyUI_windows_portable_nightly_pytorch\ComfyUI\models\loras>
 
 Directory of C:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\models\loras

11/24/2023  09:32 PM    <DIR>          .
11/16/2023  10:48 PM    <DIR>          ..
11/22/2023  10:33 PM       681,230,644 dreamshaperXL10_lora.safetensors
11/21/2023  03:23 PM        75,841,105 flat_color.pt
11/24/2023  09:32 PM       393,855,224 >>>>>>>>>>>>lcm-lora-sdxl.safetensors<<<<<<<<<<<<<<<<<
11/24/2023  12:25 AM     5,135,313,712 lcm_lora.fp16.safetensors
11/10/2023  12:13 PM                 0 put_loras_here
11/21/2023  04:10 PM       134,621,556 pytorch_lora_weights.safetensors
11/24/2023  09:30 PM    <DIR>          SD1.5
11/24/2023  08:52 PM    <DIR>          SDXL
11/24/2023  07:48 PM    <DIR>          SDXL_CIVITAI
               6 File(s)  6,420,862,241 bytes
               5 Dir(s)  572,453,347,328 bytes free


```

```
Exception: LCM LoRA model not found for SD XL
2023-11-24 21:32:23,817 ERROR Error: LCM LoRA model not found for SD XL
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 22, in _report_errors
    return await coro
  File "C:\Users\USER\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 291, in _generate_live
    work = workflow.refine(client, style, image, cond, self.live.strength, self.live)
  File "C:\Users\USER\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 476, in refine
    model, clip, vae = load_model_with_lora(w, comfy, style, is_live=live.is_active)
  File "C:\Users\USER\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 197, in load_model_with_lora
    raise Exception(f"LCM LoRA model not found for {sdver.value}")
Exception: LCM LoRA model not found for SD XL
2023-11-24 21:32:24,008 ERROR Error: LCM LoRA model not found for SD XL
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 22, in _report_errors
    return await coro
  File "C:\Users\USER\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 291, in _generate_live
    work = workflow.refine(client, style, image, cond, self.live.strength, self.live)
  File "C:\Users\USER\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 476, in refine
    model, clip, vae = load_model_with_lora(w, comfy, style, is_live=live.is_active)
  File "C:\Users\USER\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 197, in load_model_with_lora
    raise Exception(f"LCM LoRA model not found for {sdver.value}")
Exception: LCM LoRA model not found for SD XL


```

**Comment by Acly** [comment]
The filename looks correct. Can you check the client.log for message like this:
```
2023-11-24 20:51:33,781 WARNING Missing LCM LoRA model for SD XL
2023-11-24 20:51:33,781 INFO Available LCM LoRA models:
2023-11-24 20:51:33,782 INFO No model matches LCM LoRA model search paths: lcm-lora-sdxl.safetensors, lcm/sdxl/pytorch_lora_weights.safetensors
```
this should list all the Lora it does find, maybe it will give a hint.
