### ISSUE TITLE
ERROR Error during installation: ERROR: Exception:  Traceback (most recent call last):

### ISSUE THREAD

**Issue by rebecatvf** [Acly/krita-ai-diffusion#1191]
Hi! I'm trying to install Krita AI for the first time and I keep getting this error:

2024-09-16 16:49:19,174 INFO Installation started in D:\Krita (x64)\KritaAI\server
2024-09-16 16:49:19,175 INFO Downloading https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip to D:\Krita (x64)\KritaAI\server\.cache\python-3.10.11-embed-amd64.zip
2024-09-16 16:49:21,719 INFO Extracting D:\Krita (x64)\KritaAI\server\.cache\python-3.10.11-embed-amd64.zip to D:\Krita (x64)\KritaAI\server\python
2024-09-16 16:49:21,836 INFO Patching D:\Krita (x64)\KritaAI\server\python\python310._pth
2024-09-16 16:49:21,837 INFO Downloading https://bootstrap.pypa.io/get-pip.py to D:\Krita (x64)\KritaAI\server\python\get-pip.py
2024-09-16 16:49:23,157 INFO Executing D:\Krita (x64)\KritaAI\server\python\python.exe D:\Krita (x64)\KritaAI\server\python\get-pip.py
2024-09-16 16:49:26,841 INFO Collecting pip
2024-09-16 16:49:26,841 INFO Using cached pip-24.2-py3-none-any.whl.metadata (3.6 kB)
2024-09-16 16:49:27,091 INFO Collecting setuptools
2024-09-16 16:49:27,091 INFO Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
2024-09-16 16:49:27,184 INFO Collecting wheel
2024-09-16 16:49:27,185 INFO Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
2024-09-16 16:49:27,185 INFO Using cached pip-24.2-py3-none-any.whl (1.8 MB)
2024-09-16 16:49:27,185 INFO Using cached setuptools-75.1.0-py3-none-any.whl (1.2 MB)
2024-09-16 16:49:27,186 INFO Using cached wheel-0.44.0-py3-none-any.whl (67 kB)
2024-09-16 16:49:27,308 INFO Installing collected packages: wheel, setuptools, pip
2024-09-16 16:49:33,997 INFO Successfully installed pip-24.2 setuptools-75.1.0 wheel-0.44.0
2024-09-16 16:49:34,184 INFO Executing D:\Krita (x64)\KritaAI\server\python\python.exe -su -m pip install wheel setuptools
2024-09-16 16:49:35,464 INFO Requirement already satisfied: wheel in d:\krita (x64)\kritaai\server\python\lib\site-packages (0.44.0)
2024-09-16 16:49:35,464 INFO Requirement already satisfied: setuptools in d:\krita (x64)\kritaai\server\python\lib\site-packages (75.1.0)
2024-09-16 16:49:35,653 INFO Patching D:\Krita (x64)\KritaAI\server\python\python310._pth
2024-09-16 16:49:35,654 INFO Finished installing Python
2024-09-16 16:49:35,934 INFO Using Python: Python 3.10.11, D:\Krita (x64)\KritaAI\server\python\python.exe
2024-09-16 16:49:36,591 INFO Using pip: pip 24.2 from D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip (python 3.10)
2024-09-16 16:49:36,591 INFO Downloading https://github.com/comfyanonymous/ComfyUI/archive/236bda26830d719843ba9b5703894297f67f6704.zip to D:\Krita (x64)\KritaAI\server\.cache\ComfyUI-236bda26830d719843ba9b5703894297f67f6704.zip
2024-09-16 16:49:38,061 INFO Extracting D:\Krita (x64)\KritaAI\server\.cache\ComfyUI-236bda26830d719843ba9b5703894297f67f6704.zip to D:\Krita (x64)\KritaAI\server
2024-09-16 16:49:39,187 INFO Executing D:\Krita (x64)\KritaAI\server\python\python.exe -su -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
2024-09-16 16:49:40,152 INFO Looking in indexes: https://download.pytorch.org/whl/cu121
2024-09-16 16:49:41,060 INFO Collecting torch
2024-09-16 16:49:41,121 INFO Downloading https://download.pytorch.org/whl/cu121/torch-2.4.1%2Bcu121-cp310-cp310-win_amd64.whl (2444.9 MB)
2024-09-16 16:55:32,592 INFO ----------------------------             1.8/2.4 GB 4.9 MB/s eta 0:02:19
2024-09-16 16:55:33,311 ERROR Error during installation: ERROR: Exception:

Traceback (most recent call last):

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher

    yield

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read

    data = self._fp_read(amt) if not fp_closed else b""

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read

    return self._fp.read(amt) if amt is not None else self._fp.read()

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read

    data: bytes = self.__fp.read(amt)

  File "http\client.py", line 466, in read

  File "socket.py", line 705, in readinto

  File "ssl.py", line 1274, in recv_into

  File "ssl.py", line 1130, in read

ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper

    status = _inner_run()

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run

    return self.run(options, args)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper

    return func(self, options, args)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\commands\install.py", line 379, in run

    requirement_set = resolver.resolve(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve

    result = self._result = resolver.resolve(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve

    state = resolution.resolve(requirements, max_rounds=max_rounds)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve

    self._add_to_criteria(self.state.criteria, r, parent=None)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria

    if not criterion.candidates:

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__

    return bool(self._sequence)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__

    return any(self)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>

    return (c for c in iterator if id(c) not in self._incompatible_ids)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built

    candidate = func()

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 186, in _make_candidate_from_link

    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 232, in _make_base_candidate_from_link

    self._link_candidate_cache[link] = LinkCandidate(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__

    super().__init__(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__

    self.dist = self._prepare()

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare

    dist = self._prepare_distribution()

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution

    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement

    return self._prepare_linked_requirement(req, parallel_builds)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 598, in _prepare_linked_requirement

    local_file = unpack_url(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 170, in unpack_url

    file = get_http_url(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 111, in get_http_url

    from_path, content_type = download(link, temp_dir.path)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\network\download.py", line 148, in __call__

    for chunk in chunks:

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\cli\progress_bars.py", line 55, in _rich_progress_bar

    for chunk in iterable:

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\network\utils.py", line 65, in response_chunks

    for chunk in response.raw.stream(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream

    data = self.read(amt=amt, decode_content=decode_content)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read

    with self._error_catcher():

  File "contextlib.py", line 153, in __exit__

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 449, in _error_catcher

    raise SSLError(e)

pip._vendor.urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)

Traceback (most recent call last):
  File "C:\Users\Rebeca\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 264, in install
    await self._install(cb)
  File "C:\Users\Rebeca\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 139, in _install
    await try_install(comfy_dir, self._install_comfy, comfy_dir, network, cb)
  File "C:\Users\Rebeca\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 563, in try_install
    raise e
  File "C:\Users\Rebeca\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 558, in try_install
    await installer(*args)
  File "C:\Users\Rebeca\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 193, in _install_comfy
    await _execute_process("PyTorch", self._pip_install(*torch_args), self.path, cb)
  File "C:\Users\Rebeca\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 552, in _execute_process
    raise Exception(f"Error during installation: {errlog}")
Exception: Error during installation: ERROR: Exception:

Traceback (most recent call last):

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher

    yield

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read

    data = self._fp_read(amt) if not fp_closed else b""

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read

    return self._fp.read(amt) if amt is not None else self._fp.read()

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read

    data: bytes = self.__fp.read(amt)

  File "http\client.py", line 466, in read

  File "socket.py", line 705, in readinto

  File "ssl.py", line 1274, in recv_into

  File "ssl.py", line 1130, in read

ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper

    status = _inner_run()

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run

    return self.run(options, args)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper

    return func(self, options, args)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\commands\install.py", line 379, in run

    requirement_set = resolver.resolve(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve

    result = self._result = resolver.resolve(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve

    state = resolution.resolve(requirements, max_rounds=max_rounds)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve

    self._add_to_criteria(self.state.criteria, r, parent=None)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria

    if not criterion.candidates:

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__

    return bool(self._sequence)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__

    return any(self)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>

    return (c for c in iterator if id(c) not in self._incompatible_ids)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built

    candidate = func()

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 186, in _make_candidate_from_link

    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 232, in _make_base_candidate_from_link

    self._link_candidate_cache[link] = LinkCandidate(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 303, in __init__

    super().__init__(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 158, in __init__

    self.dist = self._prepare()

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 235, in _prepare

    dist = self._prepare_distribution()

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 314, in _prepare_distribution

    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement

    return self._prepare_linked_requirement(req, parallel_builds)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 598, in _prepare_linked_requirement

    local_file = unpack_url(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 170, in unpack_url

    file = get_http_url(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 111, in get_http_url

    from_path, content_type = download(link, temp_dir.path)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\network\download.py", line 148, in __call__

    for chunk in chunks:

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\cli\progress_bars.py", line 55, in _rich_progress_bar

    for chunk in iterable:

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_internal\network\utils.py", line 65, in response_chunks

    for chunk in response.raw.stream(

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream

    data = self.read(amt=amt, decode_content=decode_content)

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read

    with self._error_catcher():

  File "contextlib.py", line 153, in __exit__

  File "D:\Krita (x64)\KritaAI\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 449, in _error_catcher

    raise SSLError(e)

pip._vendor.urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)

2024-09-16 16:55:33,312 ERROR Installation failed

What should I do?

**Comment by marcoA152** [comment]
Happened also to me, I have changed connection and download all without problems.
I have used mobile phone usb tethering instead of a weak wifi. Hope it helps 😊

**Comment by ccoroner** [comment]
Hi,
I'm no expert but it seems like the connection went off during the download of pytorch either due to a change of ssl parameters or because parts of the protocol were not executed correctly.
You could try to run the command from a terminal: D:\Krita (x64)\KritaAI\server\python\python.exe -su -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
Maybe this gives more info. Make sure to use a stable Internet connection, though.
