### ISSUE TITLE
Script Error during switch between workspaces (image generation, upscaling, live preview and animation) 

### ISSUE THREAD

**Issue by Saladefroide** [Acly/krita-ai-diffusion#1233]
Hello everyone!

I have this issue with the plugin since I personalized my Krita workspace and window layouts (for dual screen editing)
I tried to relaunch Krita, but the error message appears again. Someone can help me?
Thanks a lot 😁

An exception occurred while running the script.
RuntimeError: wrapped C/C++ object of type WorkspaceSelectWidget has been deleted

"RuntimeError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Sun Sep 29 11:39:18 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\adrug\AppData\Roaming\krita\pykrita\ai_diffusion\properties.py in set_py(value=<Workspace.generation: 0>)
  152 def _setter(inst, property: str):
  153     def set_py(value):
  154         setattr(inst, property, value)
  155 
  156     qt_setter_name = f"set{property.capitalize()}"
builtinsetattr = <built-in function setattr>
inst = <ai_diffusion.ui.widget.WorkspaceSelectWidget object>
property = 'value'
value = <Workspace.generation: 0>

 C:\Users\adrug\AppData\Roaming\krita\pykrita\ai_diffusion\ui\widget.py in value(self=<ai_diffusion.ui.widget.WorkspaceSelectWidget object>, workspace=<Workspace.generation: 0>)
  724     def value(self, workspace: Workspace):
  725         self._value = workspace
  726         self.setIcon(self._icons[workspace])
  727 
  728     def _create_action(self, name: str, workspace: Workspace):
self = <ai_diffusion.ui.widget.WorkspaceSelectWidget object>
self.setIcon = <built-in method setIcon of WorkspaceSelectWidget object>
self._icons = {<Workspace.generation: 0>: <PyQt5.QtGui.QIcon object>, <Workspace.upscaling: 1>: <PyQt5.QtGui.QIcon object>, <Workspace.live: 2>: <PyQt5.QtGui.QIcon object>, <Workspace.animation: 3>: <PyQt5.QtGui.QIcon object>}
workspace = <Workspace.generation: 0>
RuntimeError: wrapped C/C++ object of type WorkspaceSelectWidget has been deleted
    __cause__ = None
    __class__ = <class 'RuntimeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of RuntimeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of RuntimeError object>
    __doc__ = 'Unspecified run-time error.'
    __eq__ = <method-wrapper '__eq__' of RuntimeError object>
    __format__ = <built-in method __format__ of RuntimeError object>
    __ge__ = <method-wrapper '__ge__' of RuntimeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of RuntimeError object>
    __gt__ = <method-wrapper '__gt__' of RuntimeError object>
    __hash__ = <method-wrapper '__hash__' of RuntimeError object>
    __init__ = <method-wrapper '__init__' of RuntimeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of RuntimeError object>
    __lt__ = <method-wrapper '__lt__' of RuntimeError object>
    __ne__ = <method-wrapper '__ne__' of RuntimeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of RuntimeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of RuntimeError object>
    __repr__ = <method-wrapper '__repr__' of RuntimeError object>
    __setattr__ = <method-wrapper '__setattr__' of RuntimeError object>
    __setstate__ = <built-in method __setstate__ of RuntimeError object>
    __sizeof__ = <built-in method __sizeof__ of RuntimeError object>
    __str__ = <method-wrapper '__str__' of RuntimeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('wrapped C/C++ object of type WorkspaceSelectWidget has been deleted',)
    with_traceback = <built-in method with_traceback of RuntimeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\adrug\AppData\Roaming\krita\pykrita\ai_diffusion\properties.py", line 154, in set_py
    setattr(inst, property, value)
  File "C:\Users\adrug\AppData\Roaming\krita\pykrita\ai_diffusion\ui\widget.py", line 726, in value
    self.setIcon(self._icons[workspace])
RuntimeError: wrapped C/C++ object of type WorkspaceSelectWidget has been deleted"

**Comment by Acly** [comment]
I wasn't able to reproduce this, what are you doing exactly?
Using multiple windows? Multiple views? Or just dragging dockers to a second screen?

Even if it doesn't produce an error I don't think multiple windows/views is working properly. But extending the window or placing the docker on a different screen should be fine.
