### ISSUE TITLE
Server running - Connection error: Connection established, but the server is missing one or more custom nodes.

### ISSUE THREAD

**Issue by tjthejuggler** [Acly/krita-ai-diffusion#124]
I'm on Ubuntu 22.04.3 LTS. ComfyUI works fine. I've installed everything in Krita AI Connection tab. No problems there, but when I click connect I get red text that reads:

"Server running - Connection error: Connection established, but the server is missing one or more custom nodes."

I searched around, tried a bunch of stuff, nothing changed my error. On the main krita window it says:

"Not connected to server. Connection attempt failed! Click below to configure and reconnect."

Krita does start up the server at "http://127.0.0.1:8188" and I can go to the browser and its in working condition. I really appreciate any advice anyone might have! Awesome project!

client.log:

2023-11-26 01:19:56,137 INFO Connecting to http://127.0.0.1:8188

server.log:

2023-11-26 01:19:53,771 INFO Total VRAM 16079 MB, total RAM 63992 MB
2023-11-26 01:19:53,911 INFO Set vram state to: NORMAL_VRAM
2023-11-26 01:19:53,911 INFO Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
2023-11-26 01:19:53,911 INFO Using pytorch cross attention
2023-11-26 01:19:55,851 INFO Traceback (most recent call last):
2023-11-26 01:19:55,851 INFO File "/home/peterpan/projects/ComfyUI/nodes.py", line 1647, in load_custom_node
2023-11-26 01:19:55,851 INFO module_spec.loader.exec_module(module)
2023-11-26 01:19:55,851 INFO File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2023-11-26 01:19:55,851 INFO File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2023-11-26 01:19:55,851 INFO File "/home/peterpan/projects/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/__init__.py", line 1, in <module>
2023-11-26 01:19:55,851 INFO from .IPAdapterPlus import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
2023-11-26 01:19:55,851 INFO File "/home/peterpan/projects/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 7, in <module>
2023-11-26 01:19:55,851 INFO from comfy.clip_vision import clip_preprocess
2023-11-26 01:19:55,851 INFO ImportError: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (/home/peterpan/projects/ComfyUI/comfy/clip_vision.py)
2023-11-26 01:19:55,852 INFO 
2023-11-26 01:19:55,852 INFO Cannot import /home/peterpan/projects/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus module for custom nodes: cannot import name 'clip_preprocess' from 'comfy.clip_vision' (/home/peterpan/projects/ComfyUI/comfy/clip_vision.py)
2023-11-26 01:19:56,131 INFO 
2023-11-26 01:19:56,131 INFO Import times for custom nodes:
2023-11-26 01:19:56,131 INFO 0.0 seconds: /home/peterpan/projects/ComfyUI/custom_nodes/comfyui-tooling-nodes
2023-11-26 01:19:56,131 INFO 0.0 seconds: /home/peterpan/projects/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
2023-11-26 01:19:56,131 INFO 0.0 seconds (IMPORT FAILED): /home/peterpan/projects/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2023-11-26 01:19:56,132 INFO 0.3 seconds: /home/peterpan/projects/ComfyUI/custom_nodes/comfyui_controlnet_aux
2023-11-26 01:19:56,132 INFO 
2023-11-26 01:19:56,132 INFO Starting server
2023-11-26 01:19:56,132 INFO 
2023-11-26 01:19:56,132 INFO To see the GUI go to: http://127.0.0.1:8188
2023-11-26 01:19:56,171 INFO 2023-11-26 01:19:54.038922: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-26 01:19:56,171 INFO 2023-11-26 01:19:54.067012: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
2023-11-26 01:19:56,171 INFO To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-11-26 01:19:56,171 INFO 2023-11-26 01:19:54.657228: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-11-26 01:19:56,171 INFO /home/peterpan/projects/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:24: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
2023-11-26 01:19:56,171 INFO warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

**Comment by quakerr** [comment]
the same problem only on windows, please help to solve

**Comment by Acly** [comment]
This looks like the ComfyUI version is too old. If this is your own install of Comfy, update should fix it.

**Comment by tjthejuggler** [comment]
> This looks like the ComfyUI version is too old. If this is your own install of Comfy, update should fix it.

You are one cool cat. This is exactly what I need, fully operational now. Thanks so much!
