### ISSUE TITLE
Cannot connect to remote server

### ISSUE THREAD

**Issue by GeoSphereWave** [Acly/krita-ai-diffusion#1259]
I have previously used Krita AI Diffusion with Vast.ai, but since a few weeks since I last tried I cannot connect to the remote server. The instance is using _aclysia/sd-comfyui-krita:v1.22.0_, and my computer is running Krita 5.2.3 on Win10 with plugin version 1.25.0.

After a few seconds this error in red appears bellow the address field.

`TypeError: 'int' object is not subscriptable`

server.log is empty, but client.log contains the following.

`
2024-10-12 18:48:28,811 INFO Connecting to http://211.21.106.84:34470
2024-10-12 18:48:32,354 ERROR Could not parse device info b'<!DOCTYPE html>\r\n<html lang="en">\r\n<head>\r\n  <meta charset="UTF-8">\r\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\r\n  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">\r\n  <style>\r\n    body {\r\n      background: url(\'https://images.unsplash.com/photo-1533749047139-189de3cf06d3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2439&q=80\') no-repeat center center fixed;\r\n      background-size: cover;\r\n      font-family: \'Arial\', sans-serif;\r\n      color: white;\r\n    }\r\n\r\n    .container {\r\n      background: rgba(0,0,0,0.6);\r\n      border-radius: 15px;\r\n      padding: 20px;\r\n    }\r\n\r\n    .jumbotron {\r\n      background: none;\r\n    }\r\n\r\n    h1, h5, h4 {\r\n      text-shadow: 2px 2px 4px rgba(0,0,0,0.7);\r\n    }\r\n\r\n    .btn-primary {\r\n      background-color: #007BFF;\r\n      border-color: #007BFF;\r\n      box-shadow: 2px 2px 4px rgba(0,0,0,0.4);\r\n    }\r\n\r\n    .btn-primary:hover {\r\n      background-color: #0056b3;\r\n      border-color: #0056b3;\r\n    }\r\n  </style>\r\n  <title>Port Not Up Yet</title>\r\n</head>\r\n<body>\r\n<div class="container mt-5">\r\n  <div class="jumbotron">\r\n    <h1>The port is not up yet</h1>\r\n    <h5>NOTE: This is not necessarily an error</h5>\r\n    <h4 style="color:#FF6347">Check your container logs for the following:</h4>\r\n    <ul class="lead">\r\n      <li>Ensure that the applications have completed syncing to /workspace.</li>\r\n      <li>Ensure that there are no errors.</li>\r\n      <li>Ensure that the logs say <strong>Container is READY!</strong></li>\r\n    </ul>\r\n    <button class="btn btn-primary" onclick="location.reload()">Refresh</button>\r\n  </div>\r\n</div>\r\n</body>\r\n</html>': byte indices must be integers or slices, not str
2024-10-12 18:48:32,636 ERROR Error: 'int' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\work\AppData\Roaming\krita\pykrita\ai_diffusion\connection.py", line 86, in _connect
    self._client = await ComfyClient.connect(url)
  File "C:\Users\work\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 108, in connect
    client._supported_languages = await _list_languages(client)
  File "C:\Users\work\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 688, in _list_languages
    return TranslationPackage.from_list(result)
  File "C:\Users\work\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 227, in from_list
    return [TranslationPackage.from_dict(item) for item in data]
  File "C:\Users\work\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 227, in <listcomp>
    return [TranslationPackage.from_dict(item) for item in data]
  File "C:\Users\work\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 223, in from_dict
    return TranslationPackage(data["code"], data["name"])
TypeError: 'int' object is not subscriptable
`

**Comment by Acly** [comment]
Probably just need to wait until the server is up. After the instance is up it needs to download models, depending on network speed it takes some minutes.

You can check the URL in browser first before connecting with Krita plugin.
