### ISSUE TITLE
Server running - Connection error: Connection established

### ISSUE THREAD

**Issue by quakerr** [Acly/krita-ai-diffusion#126]
please help me find out what the problem might be

client.log
2023-11-25 22:19:53,996 INFO Extension initialized, Version: 1.7.1, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2023-11-25 22:19:53,998 INFO Found server installation v1.7.0 at D:\PROGRAM FILES\Krita (x64)\roaming\pykrita\ai_diffusion\.server
2023-11-25 22:20:03,917 INFO Connecting to http://127.0.0.1:8188
2023-11-25 22:20:04,023 INFO Found ControlNet model inpaint for SD 1.5: control_v11p_sd15_inpaint_fp16.safetensors
2023-11-25 22:20:04,024 INFO Optional ControlNet model scribble for SD 1.5 not found (search path: control_v11p_sd15_scribble, control_lora_rank128_v11p_sd15_scribble)
2023-11-25 22:20:04,024 INFO Optional ControlNet model line_art for SD 1.5 not found (search path: control_v11p_sd15_lineart, control_lora_rank128_v11p_sd15_lineart)
2023-11-25 22:20:04,024 INFO Optional ControlNet model line_art for SD XL not found (search path: control-lora-sketch-rank, sai_xl_sketch_)
2023-11-25 22:20:04,025 INFO Optional ControlNet model soft_edge for SD 1.5 not found (search path: control_v11p_sd15_softedge, control_lora_rank128_v11p_sd15_softedge)
2023-11-25 22:20:04,025 INFO Optional ControlNet model canny_edge for SD 1.5 not found (search path: control_v11p_sd15_canny, control_lora_rank128_v11p_sd15_canny)
2023-11-25 22:20:04,025 INFO Optional ControlNet model canny_edge for SD XL not found (search path: control-lora-canny-rank, sai_xl_canny_)
2023-11-25 22:20:04,025 INFO Optional ControlNet model depth for SD 1.5 not found (search path: control_v11f1p_sd15_depth, control_lora_rank128_v11f1p_sd15_depth)
2023-11-25 22:20:04,026 INFO Optional ControlNet model depth for SD XL not found (search path: control-lora-depth-rank, sai_xl_depth_)
2023-11-25 22:20:04,026 INFO Optional ControlNet model normal for SD 1.5 not found (search path: control_v11p_sd15_normalbae, control_lora_rank128_v11p_sd15_normalbae)
2023-11-25 22:20:04,026 INFO Optional ControlNet model pose for SD 1.5 not found (search path: control_v11p_sd15_openpose, control_lora_rank128_v11p_sd15_openpose)
2023-11-25 22:20:04,027 INFO Optional ControlNet model pose for SD XL not found (search path: control-lora-openposexl2-rank, thibaud_xl_openpose)
2023-11-25 22:20:04,027 INFO Optional ControlNet model segmentation for SD 1.5 not found (search path: control_v11p_sd15_seg, control_lora_rank128_v11p_sd15_seg)
2023-11-25 22:20:04,027 INFO Found ControlNet model blur for SD 1.5: control_lora_rank128_v11f1e_sd15_tile_fp16.safetensors
2023-11-25 22:20:04,027 INFO Found CLIP Vision model for All: SD1.5\pytorch_model.bin
2023-11-25 22:20:04,028 INFO Found IP-Adapter model for SD 1.5: ip-adapter_sd15.safetensors
2023-11-25 22:20:04,028 WARNING Missing IP-Adapter model for SD XL
2023-11-25 22:20:04,028 INFO Available IP-Adapter models: ip-adapter_sd15.safetensors
2023-11-25 22:20:04,028 INFO No model matches IP-Adapter model search paths: ip-adapter_sdxl_vit-h
2023-11-25 22:20:04,029 INFO Found LCM LoRA model for SD 1.5: lcm-lora-sdv1-5.safetensors
2023-11-25 22:20:04,029 WARNING Missing LCM LoRA model for SD XL
2023-11-25 22:20:04,029 INFO Available LCM LoRA models: lcm-lora-sdv1-5.safetensors
2023-11-25 22:20:04,029 INFO No model matches LCM LoRA model search paths: lcm-lora-sdxl.safetensors, lcm/sdxl/pytorch_lora_weights.safetensors
2023-11-25 22:20:04,030 INFO SD 1.5: supported
2023-11-25 22:20:04,030 INFO SD XL: missing resources IP-Adapter model, Stable Diffusion Checkpoint
2023-11-25 22:20:29,401 WARNING Websocket connection closed: no close frame received or sent
2023-11-25 22:20:36,898 ERROR Error: Connection refused
Traceback (most recent call last):
  File "D:\PROGRAM FILES\Krita (x64)\roaming\pykrita\ai_diffusion\ui\model.py", line 22, in _report_errors
    return await coro
  File "D:\PROGRAM FILES\Krita (x64)\roaming\pykrita\ai_diffusion\ui\model.py", line 249, in _generate
    job_id = await client.enqueue(job)
  File "D:\PROGRAM FILES\Krita (x64)\roaming\pykrita\ai_diffusion\client.py", line 207, in enqueue
    result = await self._post("prompt", data)
  File "D:\PROGRAM FILES\Krita (x64)\roaming\pykrita\ai_diffusion\client.py", line 203, in _post
    return await self._requests.post(f"{self.url}/{op}", data)
ai_diffusion.network.NetworkError: Connection refused

2023-11-25 22:20:00,304 INFO Total VRAM 8006 MB, total RAM 8006 MB
2023-11-25 22:20:01,584 INFO Set vram state to: DISABLED
2023-11-25 22:20:01,584 INFO Device: cpu
2023-11-25 22:20:01,585 INFO VAE dtype: torch.float32
2023-11-25 22:20:02,051 INFO Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2023-11-25 22:20:03,899 INFO 
2023-11-25 22:20:03,899 INFO Import times for custom nodes:
2023-11-25 22:20:03,900 INFO 0.0 seconds: D:\PROGRAM FILES\Krita (x64)\roaming\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui-tooling-nodes
2023-11-25 22:20:03,900 INFO 0.0 seconds: D:\PROGRAM FILES\Krita (x64)\roaming\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2023-11-25 22:20:03,901 INFO 0.0 seconds: D:\PROGRAM FILES\Krita (x64)\roaming\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2023-11-25 22:20:03,901 INFO 0.8 seconds: D:\PROGRAM FILES\Krita (x64)\roaming\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux
2023-11-25 22:20:03,901 INFO 
2023-11-25 22:20:03,901 INFO Starting server
2023-11-25 22:20:03,902 INFO 
2023-11-25 22:20:03,902 INFO To see the GUI go to: http://127.0.0.1:8188
2023-11-25 22:20:03,958 INFO D:\PROGRAM FILES\Krita (x64)\roaming\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:24: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
2023-11-25 22:20:03,958 INFO warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
2023-11-25 22:20:25,489 INFO got prompt

**Comment by ZaneH** [comment]
It looks like a network error, do you have any VPNs or firewalls? And have you double checked your network settings?

Also, what causes this error? Does it show up anytime you hit "Generate"?
