### ISSUE TITLE
Trying to inpaint with flux dev got out of memory

### ISSUE THREAD

**Issue by Lastofthefirst** [Acly/krita-ai-diffusion#1290]
I am trying to inpaint with flux and got the following error:

I have 96gb of ram and 24gb of vram.

Any direction for debugging?

```
got prompt
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Requested to load Flux
Requested to load ControlNetFlux
Loading 2 new models
loaded partially 22179.53441989136 22177.927856445312 0
loaded partially 424.9345634460449 424.640625 0
  0%|                                                              | 0/20 [00:00<?, ?it/s]Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Requested to load ControlNetFlux
Loading 1 new model
loaded partially 990.4243743896484 990.322265625 0
loaded partially 21569.563046264648 21569.4609375 0
  0%|                                                              | 0/20 [00:01<?, 
!!! Exception during processing !!! Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 22.86 GiB
Requested               : 185.01 MiB
Device limit            : 23.69 GiB
Free (according to CUDA): 14.06 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB
Traceback (most recent call last):
  File "/home/quddus/sd/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/quddus/sd/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/quddus/sd/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/quddus/sd/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/quddus/sd/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 633, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "/home/quddus/sd/ComfyUI/comfy/samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "/home/quddus/sd/ComfyUI/comfy/samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/quddus/sd/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 87, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
  File "/home/quddus/sd/ComfyUI/comfy/samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/quddus/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/quddus/sd/ComfyUI/comfy/k_diffusion/sampling.py", line 155, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/home/quddus/sd/ComfyUI/comfy/samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "/home/quddus/sd/ComfyUI/comfy/samplers.py", line 682, in __call__
    return self.predict_noise(*args, **kwargs)
  File "/home/quddus/sd/ComfyUI/comfy/samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "/home/quddus/sd/ComfyUI/custom_nodes/ComfyUI_smZNodes/smZNodes.py", line 162, in sampling_function
    out = orig_fn(*args, **kwargs)
  File "/home/quddus/sd/ComfyUI/comfy/samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "/home/quddus/sd/ComfyUI/comfy/samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/quddus/sd/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 69, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "/home/quddus/sd/ComfyUI/comfy/model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/quddus/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/quddus/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/quddus/sd/ComfyUI/comfy/ldm/flux/model.py", line 159, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control)
  File "/home/quddus/sd/ComfyUI/comfy/ldm/flux/model.py", line 130, in forward_orig
    img = block(img, vec=vec, pe=pe)
  File "/home/quddus/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/quddus/miniconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/quddus/sd/ComfyUI/comfy/ldm/flux/layers.py", line 231, in forward
    output = self.linear2(torch.cat((attn, self.mlp_act(mlp)), 2))
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 22.86 GiB
Requested               : 185.01 MiB
Device limit            : 23.69 GiB
Free (according to CUDA): 14.06 MiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

Got an OOM, unloading all loaded models.
Prompt executed in 6.20 seconds
```

**Comment by Acly** [comment]
Check ComfyUI's vram arguments. Not sure what you're using or what the default is for 24gb, but `--normalvram` might work?

Also what version of flux dev? Try a quantized one, 8-bit should be a good match.
