### ISSUE TITLE
IP-Adapter installation error

### ISSUE THREAD

**Issue by tachyonrain** [Acly/krita-ai-diffusion#1305]
When I try to install IP-Adapter Face (XL) or IP-Adapter Face (SD1.5), I get the following error message.
This was also occurring in ver 1.24.
All other tools install successfully.
Is there any way for me to fix this now?
If that is not possible, I hope the problem will be resolved in a future version.
Thank you.
![1](https://github.com/user-attachments/assets/f83903c1-fa82-489a-8e8c-0cef7eb1510f)
![2](https://github.com/user-attachments/assets/b9e937e3-ec1c-452d-a544-019b97559bcd)
Exception: Error during installation: ERROR: Exception:

Traceback (most recent call last):

  File "C:\Users\lime\AppData\Roaming\krita\ai_diffusion\server\python\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper

    status = _inner_run()

             ^^^^^^^^^^^^

  File "C:\Users\lime\AppData\Roaming\krita\ai_diffusion\server\python\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run

    return self.run(options, args)

           ^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\lime\AppData\Roaming\krita\ai_diffusion\server\python\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper

    return func(self, options, args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\lime\AppData\Roaming\krita\ai_diffusion\server\python\Lib\site-packages\pip\_internal\commands\install.py", line 457, in run

    installed = install_given_reqs(

                ^^^^^^^^^^^^^^^^^^^

  File "C:\Users\lime\AppData\Roaming\krita\ai_diffusion\server\python\Lib\site-packages\pip\_internal\req\__init__.py", line 70, in install_given_reqs

    requirement.install(

  File "C:\Users\lime\AppData\Roaming\krita\ai_diffusion\server\python\Lib\site-packages\pip\_internal\req\req_install.py", line 867, in install

    install_wheel(

  File "C:\Users\lime\AppData\Roaming\krita\ai_diffusion\server\python\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 732, in install_wheel

    _install_wheel(

  File "C:\Users\lime\AppData\Roaming\krita\ai_diffusion\server\python\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 590, in _install_wheel

    file.save()

  File "C:\Users\lime\AppData\Roaming\krita\ai_diffusion\server\python\Lib\site-packages\pip\_internal\operations\install\wheel.py", line 378, in save

    with self._zip_file.open(zipinfo) as f:

         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "zipfile.py", line 1584, in open

zipfile.BadZipFile: Bad magic number for file header

**Comment by Lanserotti** [comment]
I got this to

**Comment by Acly** [comment]
It sounds like a broken zip file. I'd try to delete the `.cache` folder inside the server installation path, then retry install.

**Comment by tachyonrain** [comment]
Hi Acly.
Your advice has solved the problem.
Thank you very much.
