### ISSUE TITLE
i think i'm dumb 

### ISSUE THREAD

**Issue by mrblack1986** [Acly/krita-ai-diffusion#1370]
im trying to install ,and it won't install cumfyui 
i think i did some thing wrong i just do know what 

2024-11-08 15:03:36,795 INFO Extension initialized, Version: 1.15.0, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2024-11-08 15:03:37,790 INFO Connecting to http://127.0.0.1:8188
2024-11-08 15:03:51,022 INFO Installation started in C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server
2024-11-08 15:03:51,028 INFO Downloading https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip to C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\.cache\python-3.10.11-embed-amd64.zip
2024-11-08 15:03:52,208 INFO Extracting C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\.cache\python-3.10.11-embed-amd64.zip to C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python
2024-11-08 15:03:52,283 INFO Patching C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\python310._pth
2024-11-08 15:03:52,284 INFO Downloading https://bootstrap.pypa.io/get-pip.py to C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\get-pip.py
2024-11-08 15:03:52,826 INFO Executing C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\python.exe C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\get-pip.py
2024-11-08 15:03:54,642 INFO Collecting pip
2024-11-08 15:03:54,698 INFO Using cached pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
2024-11-08 15:03:54,859 INFO Collecting setuptools
2024-11-08 15:03:54,917 INFO Using cached setuptools-75.3.0-py3-none-any.whl.metadata (6.9 kB)
2024-11-08 15:03:54,949 INFO Collecting wheel
2024-11-08 15:03:55,013 INFO Using cached wheel-0.44.0-py3-none-any.whl.metadata (2.3 kB)
2024-11-08 15:03:55,013 INFO Using cached pip-24.3.1-py3-none-any.whl (1.8 MB)
2024-11-08 15:03:55,081 INFO Using cached setuptools-75.3.0-py3-none-any.whl (1.3 MB)
2024-11-08 15:03:55,081 INFO Using cached wheel-0.44.0-py3-none-any.whl (67 kB)
2024-11-08 15:03:55,112 INFO Installing collected packages: wheel, setuptools, pip
2024-11-08 15:04:03,015 INFO Successfully installed pip-24.3.1 setuptools-75.3.0 wheel-0.44.0
2024-11-08 15:04:03,170 INFO Executing C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\python.exe -su -m pip install wheel setuptools
2024-11-08 15:04:04,106 INFO Requirement already satisfied: wheel in c:\users\pc\appdata\roaming\krita\ai_diffusion\server\python\lib\site-packages (0.44.0)
2024-11-08 15:04:04,107 INFO Requirement already satisfied: setuptools in c:\users\pc\appdata\roaming\krita\ai_diffusion\server\python\lib\site-packages (75.3.0)
2024-11-08 15:04:04,267 INFO Patching C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\python310._pth
2024-11-08 15:04:04,267 INFO Finished installing Python
2024-11-08 15:04:04,804 INFO Using Python: Python 3.10.11, C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\python.exe
2024-11-08 15:04:05,575 INFO Using pip: pip 24.3.1 from C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip (python 3.10)
2024-11-08 15:04:05,575 INFO Downloading https://github.com/comfyanonymous/ComfyUI/archive/236bda26830d719843ba9b5703894297f67f6704.zip to C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\.cache\ComfyUI-236bda26830d719843ba9b5703894297f67f6704.zip
2024-11-08 15:04:06,270 INFO Extracting C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\.cache\ComfyUI-236bda26830d719843ba9b5703894297f67f6704.zip to C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server
2024-11-08 15:04:06,481 INFO Executing C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\python.exe -su -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
2024-11-08 15:04:06,986 INFO Looking in indexes: https://download.pytorch.org/whl/cu121
2024-11-08 15:04:07,210 INFO Collecting torch
2024-11-08 15:04:07,262 INFO Downloading https://download.pytorch.org/whl/cu121/torch-2.5.1%2Bcu121-cp310-cp310-win_amd64.whl (2449.4 MB)
2024-11-08 15:05:07,011 INFO ----                                     0.3/2.4 GB 7.7 MB/s eta 0:04:39
2024-11-08 15:05:07,230 ERROR Error during installation: ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
  File "http\client.py", line 466, in read
  File "socket.py", line 705, in readinto
  File "ssl.py", line 1274, in recv_into
  File "ssl.py", line 1130, in read
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
    super().__init__(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
    self.dist = self._prepare()
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 598, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 170, in unpack_url
    file = get_http_url(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 111, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\network\download.py", line 148, in __call__
    for chunk in chunks:
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\cli\progress_bars.py", line 55, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\network\utils.py", line 65, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
  File "contextlib.py", line 153, in __exit__
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 449, in _error_catcher
    raise SSLError(e)
pip._vendor.urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 264, in install
    await self._install(cb)
  File "C:\Users\PC\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 139, in _install
    await try_install(comfy_dir, self._install_comfy, comfy_dir, network, cb)
  File "C:\Users\PC\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 563, in try_install
    raise e
  File "C:\Users\PC\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 558, in try_install
    await installer(*args)
  File "C:\Users\PC\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 193, in _install_comfy
    await _execute_process("PyTorch", self._pip_install(*torch_args), self.path, cb)
  File "C:\Users\PC\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 552, in _execute_process
    raise Exception(f"Error during installation: {errlog}")
Exception: Error during installation: ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
  File "http\client.py", line 466, in read
  File "socket.py", line 705, in readinto
  File "ssl.py", line 1274, in recv_into
  File "ssl.py", line 1130, in read
ssl.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\commands\install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\resolvelib\structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 174, in __bool__
    return any(self)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\found_candidates.py", line 53, in _iter_built
    candidate = func()
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 304, in __init__
    super().__init__(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 159, in __init__
    self.dist = self._prepare()
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 236, in _prepare
    dist = self._prepare_distribution()
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 315, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 598, in _prepare_linked_requirement
    local_file = unpack_url(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 170, in unpack_url
    file = get_http_url(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\operations\prepare.py", line 111, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\network\download.py", line 148, in __call__
    for chunk in chunks:
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\cli\progress_bars.py", line 55, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_internal\network\utils.py", line 65, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
  File "contextlib.py", line 153, in __exit__
  File "C:\Users\PC\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\pip\_vendor\urllib3\response.py", line 449, in _error_catcher
    raise SSLError(e)
pip._vendor.urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2578)

2024-11-08 15:05:07,231 ERROR Installation failed

**Comment by Acly** [comment]
This looks like a network connection issue, nothing to do except make sure you have stable internet
