### ISSUE TITLE
i can't use sd3.5 large turbo gguf

### ISSUE THREAD

**Issue by esmail-mkh** [Acly/krita-ai-diffusion#1405]
i can't use sd3.5 large gguf and it detects as flux 1 model and load with flux clip, please add gguf version of sd3.5

and the error is:

```
!!! Exception during processing !!! mat1 and mat2 shapes cannot be multiplied (1x768 and 2048x2432)
Traceback (most recent call last):
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 633, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 740, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 719, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 624, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 830, in sample_dpmpp_sde_gpu
    return sample_dpmpp_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, r=r)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 648, in sample_dpmpp_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 706, in __call__
    return self.predict_noise(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 709, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 69, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 144, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 1041, in forward
    return super().forward(x, timesteps, context=context, y=y, control=control, transformer_options=transformer_options)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 1018, in forward
    y = self.y_embedder(y)  # (N, D)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\mmdit.py", line 256, in forward
    emb = self.mlp(x)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\container.py", line 215, in forward
    input = module(input)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 68, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 153, in forward_comfy_cast_weights
    return super().forward_comfy_cast_weights(input, *args, **kwargs)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\comfy\ops.py", line 64, in forward_comfy_cast_weights
    return torch.nn.functional.linear(input, weight, bias)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\_tensor.py", line 1386, in __torch_function__
    ret = func(*args, **kwargs)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x768 and 2048x2432)
```

**Comment by Acly** [comment]
This should work now ([v1.29.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.29.0) if you're using the models from here: https://huggingface.co/city96/stable-diffusion-3.5-large-turbo-gguf

I only tried with sd3-medium so far
