### ISSUE TITLE
i give the models a destination but it deosnt work and i get an error socket not connected and please someone give me the format for where to put the models files in which directory just im really dumb and im on a mac i just really want to get ai image generation to work:(

### ISSUE THREAD

**Issue by brodieleee21312** [Acly/krita-ai-diffusion#1407]
ai_diffusion % python download_models.py --minimal C:\Models

Generative AI for Krita - Model download - v1.28.0
Error downloading CLIP Vision model (attempt 0): Cannot connect to host huggingface.co:443 ssl:default [Socket is not connected]
Traceback (most recent call last):
  File "/Users/1017652/miniconda3/lib/python3.12/site-packages/aiohttp/connector.py", line 1098, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/1017652/miniconda3/lib/python3.12/asyncio/base_events.py", line 1148, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/1017652/miniconda3/lib/python3.12/asyncio/base_events.py", line 1181, in _create_connection_transport
    await waiter
  File "/Users/1017652/miniconda3/lib/python3.12/asyncio/selector_events.py", line 988, in _read_ready__get_buffer
    nbytes = self._sock.recv_into(buf)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 57] Socket is not connected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/1017652/Library/Application Support/krita/pykrita/ai_diffusion/download_models.py", line 217, in <module>
    asyncio.run(
  File "/Users/1017652/miniconda3/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/1017652/miniconda3/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/1017652/miniconda3/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/1017652/Library/Application Support/krita/pykrita/ai_diffusion/download_models.py", line 166, in main
    await download_with_retry(
  File "/Users/1017652/Library/Application Support/krita/pykrita/ai_diffusion/download_models.py", line 64, in download_with_retry
    await download(client, model, destination, verbose, dry_run)
  File "/Users/1017652/Library/Application Support/krita/pykrita/ai_diffusion/download_models.py", line 94, in download
    async with client.get(url) as resp:
               ^^^^^^^^^^^^^^^
  File "/Users/1017652/miniconda3/lib/python3.12/site-packages/aiohttp/client.py", line 1359, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/Users/1017652/miniconda3/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/1017652/miniconda3/lib/python3.12/site-packages/aiohttp/connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/1017652/miniconda3/lib/python3.12/site-packages/aiohttp/connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/1017652/miniconda3/lib/python3.12/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection
    raise last_exc
  File "/Users/1017652/miniconda3/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/1017652/miniconda3/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host huggingface.co:443 ssl:default [Socket is not connected]
(base) 1017652@1017652-student-FVFG332CQ6L3 ai_diffusion %

**Comment by Acly** [comment]
There's nothing I can do if you cannot connect to huggingface.co (your internet blocks it?)
