### ISSUE TITLE
Server execution error: InpaintModelConditioning.encode() missing 1 required positional argument: 'noise_mask'

### ISSUE THREAD

**Issue by ricperry** [Acly/krita-ai-diffusion#1427]
This is a new error. I can no longer select a portion of the image to inpaint. I can only generate the whole image. Occurrs when I try to replace background, inpaint a selection, expand image, etc... any time I'm not re-generating the entire image.

ROCm (linux) or ZLUDA (windows) gives same errors. DirectML (windows) just crashes with no error.

```
!!! Exception during processing !!! InpaintModelConditioning.encode() missing 1 required positional argument: 'noise_mask'
Traceback (most recent call last):
  File "/home/ricperry1/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ricperry1/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ricperry1/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ricperry1/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ricperry1/ComfyUI/custom_nodes/comfyui-inpaint-nodes/nodes.py", line 216, in encode
    positive, negative, latent = nodes.InpaintModelConditioning().encode(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: InpaintModelConditioning.encode() missing 1 required positional argument: 'noise_mask'

Prompt executed in 0.01 seconds
```

**Comment by ricperry** [comment]
fixed already in the inpaint node. Just need to update custom nodes.
