### ISSUE TITLE
new v1.29 is still looking for MAT_Places512_G_fp16 inside the old Comfy models/inpaint folder

### ISSUE THREAD

**Issue by valery016** [Acly/krita-ai-diffusion#1469]
After installing the new v1.29, I spent half an hour resolving the red-colored error message showing up during plugin's startup about missing mat_places512_g_fp16 file. I put a copy of the file everywhere I could think of in both managed and external trees (about 6 copies in total), the plugin still wouldn't find it. It's only after I placed it inside the old Comfy/models tree of the _managed_ server (in the inpaint subfolder) that it could start without an error. It's also strange because I was trying to start the plugin using an _external_ Comfy server, not the managed one.

**Comment by valery016** [comment]
After posting the above I found that the same thing applies to the inpaint fooocus models for SDXL and some other model files.

**Comment by Acly** [comment]
Relevant information:
* the update log (should be part of client.log)
* what exactly is in `[server-path]/models/inpaint` vs `[server-path]/ComfyUI/models/inpaint`
* contents of `[server-path]/ComfyUI/extra_model_paths.yaml`

Not really sure about the mixup between managed/custom install, only way that's possible is if the `extra_model_paths.yaml` is somehow pointing to the other install on your system.

**Comment by valery016** [comment]
Ok, here goes. **The update log section:** 

[v1.29.install.log](https://github.com/user-attachments/files/18049176/v1.29.install.log)

**[server-path]/models/inpaint]** 

C:\AI\ai_diffusion\.serverI\models\inpaint>dir
 Volume in drive C is System
 Volume Serial Number is 2286-4F9D

 Directory of C:\AI\ai_diffusion\.serverI\models\inpaint

06/12/2024  20:37    <DIR>          .
19/10/2024  12:14    <DIR>          ..
13/02/2024  17:29               998 config.json
13/02/2024  18:32     1.445.157.124 diffusion_pytorch_inpaint.safetensors
13/02/2024  15:53            52.602 fooocus_inpaint_head.pth
29/06/2024  22:48       102.218.542 fooocus_lama.safetensors
13/02/2024  15:55     1.323.362.033 inpaint_v26.fooocus.patch
29/06/2024  21:08     2.502.139.104 Kataragi_inpaintXL-fp16.safetensors
13/02/2024  15:50       125.280.278 mat_places512_g_fp16.safetensors
13/07/2024  20:13            32.768 model_metadata.ldb
               8 File(s)  5.498.243.449 bytes
               2 Dir(s)  498.850.418.688 bytes free

**[server-path]/ComfyUI/models/inpaint]**

C:\AI\ai_diffusion\.serverI\ComfyUI\models\inpaint>dir
 Volume in drive C is System
 Volume Serial Number is 2286-4F9D

 Directory of C:\AI\ai_diffusion\.serverI\ComfyUI\models\inpaint

06/12/2024  20:37    <DIR>          .
07/12/2024  00:33    <DIR>          ..
13/02/2024  17:29               998 config.json
13/02/2024  18:32     1.445.157.124 diffusion_pytorch_inpaint.safetensors
29/06/2024  22:48            52.602 fooocus_inpaint_head.pth
29/06/2024  22:48       102.218.542 fooocus_lama.safetensors
29/06/2024  22:45     1.323.362.033 inpaint_v26.fooocus.patch
29/06/2024  21:08     2.502.139.104 Kataragi_inpaintXL-fp16.safetensors
13/02/2024  15:50       125.280.278 mat_places512_g_fp16.safetensors
13/07/2024  20:13            32.768 model_metadata.ldb
               8 File(s)  5.498.243.449 bytes
               2 Dir(s)  498.858.962.944 bytes free

**[server-path]/ComfyUI/extra_model_paths.yaml** (renamed to extra_model_paths.yaml.txt just to be able to drop it here]

[extra_model_paths.yaml.txt](https://github.com/user-attachments/files/18049186/extra_model_paths.yaml.txt)

**Comment by valery016** [comment]
Also on this subject: I could never get the plugin use the **clip_l** model in my config, it is always listed as not found in the client.log, no matter where I place it (it is now in about 6 locations, including those under Stability Matrix, still the same):

C:\AI\ai_diffusion\.serverI\models\clip_vision>dir /s
 Volume in drive C is System
 Volume Serial Number is 2286-4F9D

 Directory of C:\AI\ai_diffusion\.serverI\models\clip_vision

06/12/2024  21:36    <DIR>          .
19/10/2024  12:14    <DIR>          ..
06/12/2024  21:30       246.144.152 clip_l.safetensors
17/10/2024  18:18     3.689.911.098 clip_vision_g.safetensors
13/02/2024  15:40                 0 put_clip_vision_models_here
18/10/2024  22:18    <DIR>          SD1.5
               3 File(s)  3.936.055.250 bytes

 Directory of C:\AI\ai_diffusion\.serverI\models\clip_vision\SD1.5

18/10/2024  22:18    <DIR>          .
06/12/2024  21:36    <DIR>          ..
13/02/2024  15:50     2.528.373.448 model.safetensors
               1 File(s)  2.528.373.448 bytes

     Total Files Listed:
               4 File(s)  6.464.428.698 bytes
               5 Dir(s)  498.844.303.360 bytes free

The last occurrence:

2024-12-07 00:30:37,687 INFO Optional Text Encoder model clip_l for All not found (search path: clip_l)

What's the deal with it?

**Comment by valery016** [comment]
And while we are on this... a new nuisance after installing v1.29: every time I do Connect to my custom Comfy server from the plugin's Configure dialogue, I notice this message in the server console (after a normal, error-free startup sequence):

To see the GUI go to: http://0.0.0.0:8190
Traceback (most recent call last):
  File "C:\AI\StabilityMatrix\Packages\ComfyUI\custom_nodes\comfyui-tooling-nodes\api.py", line 145, in inspect_models
    for filename in folder_paths.get_filename_list(model_type)
  File "C:\AI\StabilityMatrix\Packages\ComfyUI\folder_paths.py", line 322, in get_filename_list
    out = get_filename_list_(folder_name)
  File "C:\AI\StabilityMatrix\Packages\ComfyUI\folder_paths.py", line 283, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'unet_gguf'

I don't recall seeing this error before installing v1.29. This doesn't seem to affect the plugin's work (everything seems normal from within Krita AI), but I wonder why I am getting this, not having installed Flux at all or anything else gguf-related.

**Comment by Acly** [comment]
> Ok, here goes. The update log section:
> [...]

This looks all good as far as I can tell. Update worked, it migrated models to the new path (`[server-path]/models`), it extended the .yaml, and as far as I can see in the log, mat_places512_g_fp16 was found (along with everything else).

The old model folder (`[server-path]/ComfyUI/models`) shouldn't contain model files anymore, but you said you moved stuff their manually, so I'm guessing that's why?

> Also on this subject: I could never get the plugin use the clip_l model in my config

It goes to the `clip` folder, _not_ `clip_vision`

> And while we are on this... a new nuisance after installing v1.29

I'll fix that (shouldn't print an error), but yes it doesn't have any impact since it just says it didn't find any GGUF models (which you don't have).


So I can't find anything wrong here? Was your error with custom StabilityMatrix comfy? I can't really help with that. If you fixed it by moving the models to the _old_ folder, I can only assume that you at some point set it up that way! And it no longer worked because the updated moved the folder. That's to be expected.

**Comment by valery016** [comment]
The missing MAT_Places512_G_fp16 failure - as I found out now - didn’t have anything to do with Stability Matrix in the picture, but with the fact that the external Comfy was/is using junctions for folders in the plugin-managed one's folder tree (to avoid duplication), which were nullified during the v1.29 installation. But I think this is less relevant than it might sound, since it was just one of many examples of this kind of situation that I hear almost daily from folks on Discord (whom I am always glad to help, but my knowledge has its limits of course). 

I’d really like to see more help from the log/diagnostic system of the plugin for both types of configuration, especially in show-stopping situations like this one. For starters. it would be much more helpful if during the startup sequence the plugin added to the error message strings like “(partial) match:  MAT_Places512_G_fp16 …” and “INFO Optional Text Encoder model clip_l for All not found (search path: clip_l)” in the log file the folder name(s) where the plugin was looking for these components. Would this be feasible? That would save lots of guessing work for many users installing or updating the plugin, or otherwise modifying the setup.


_It goes to the clip folder, not clip_vision_

This worked, thanks! Could you shed a bit of light on which base models use this file and for what?

**Comment by Acly** [comment]
>  folder name(s) where the plugin was looking for these components. Would this be feasible?

Would be nice, but not so easy to have. The plugin doesn't know the folders. Would have to extend Comfy to query them.

Clip-L is used by pretty much all models, but in most cases it's part of the checkpoint

**Comment by hendrix2222** [comment]
I'm still struggling with this. No matter where I put the MAT_Places512_G_fp16 model, the plugin cannot find it when I use an existing instance of ComfyUI. I was able to add the ipadapter folder/model just fine, but this one refuses to be found. Not sure what else I can do here.

**Comment by DevonJerothe** [comment]
Still facing this issue for existing installs of ComfyUI

**Comment by dxyklp** [comment]
我安装了最新的1.31版本插件仍然存在这个问题，Missing common models: 
MAT Inpaint (MAT_Places512_G_fp16.safetensors)
问题出在哪里，其它模型文件都能识别到，唯独这个，我确定模型文件放在了comfyui\models\inpaint文件夹中，而且文件名没有错误

**Comment by little-wheat** [comment]
> 我安装了最新的1.31版本插件仍然存在这个问题，Missing common models: MAT Inpaint (MAT_Places512_G_fp16.safetensors) 问题出在哪里，其它模型文件都能识别到，唯独这个，我确定模型文件放在了comfyui\models\inpaint文件夹中，而且文件名没有错误

我也遇到这个问题，不过我是放在外部的文件夹，即是通过extra_model_paths.yml链接的文件夹，然后报找不到。把文件放在Comfyui里面的文件夹就能找到了

**Comment by SethG911** [comment]
Create a folder in the ComfyUI\models\ folder called inpaint, and place the MAT_Places512_G_fp16.safetensors in there.

ComfyUI\models\inpaint\MAT_Places512_G_fp16.safetensors

The instructions from the AI Diffusion website hint at this: https://docs.interstice.cloud/models/?arch-sd15=true&arch-sdxl=false#downloading-models

**Comment by mindels0** [comment]
Hi im on the 1.41.1 version and this problem still there , i tried  many solution there but no one are working  (Have the same error ComfyUI\models\inpaint\MAT_Places512_G_fp16.safetensors on external (Pinokio and The desktop version of Comfy) .

**Comment by Ark-kun** [comment]
Version 1.45.0: The problem is still there when using `extra_model_paths.yaml`.

Root cause analysis:
1. ComfyUI folder configuration via `extra_model_paths.yaml` is weird. It's not enough to just specify `base_path` - you must explicitly specify subdirectory for each model type.
2. ComfyUI does not support model type `inpainting`. See [folder_paths.py](https://github.com/Comfy-Org/ComfyUI/blob/master/folder_paths.py). So, even if you specify `inpaint: models/inpaint/`, this has no effect. ComfyUI does not recognize the extra path.

Solution: The Krita plugin should probably use some directory explicitly supported by ComfyUI instead of the `models/inpaint/` directory for MAT_Places512_G_fp16.safetensors.

**Comment by Acly** [comment]
> So, even if you specify inpaint: models/inpaint/, this has no effect. ComfyUI does not recognize the extra path.

This is wrong. 

Adding inpaint folder to `extra_model_paths.yaml` works fine. It is exactly what the built-in install is doing, which is automatically tested every release. There have never been issues with this.

So far all issues where this file is not found in custom installs are from:
* model is not in the correct folder
* folder hasn't been added to `extra_model_paths.yaml` or there's a typo
* using Stability Matrix which does its own folder mapping
* having installed some other custom node which overwrites the folder paths in a destructive way

**Comment by Ark-kun** [comment]
Sorry for taking your time. I was wrong.

The observed behavior suggested the explanation that I've posted: All other model types were getting found when placed in extra_model_paths subdirs, but the `inpaint/xxx` models were only found when placed in the default ComfyUI models dir.

However, the root cause was different:
ComfyUI Desktop seems to be pretty buggy. It has left ~5 zombie app instances (no visible windows) and 2+ more backend-only instances (it took me a lot of time to play whack-a-mole with them). Among all those zombie instances 2 (somehow, only 2) were operating working HTTP endpoints on localhost:8000 and localhost:8001. So, when I updated extra_model_paths.yaml to include the inpaint dir and restarted ComfyUI, it was now operating on  localhost:8002, while the instances running on localhost:8000 and localhost:8001 were still using the old paths that did not include inpaint model type. So, the Krita AI plugin was not finding the model.

I really wish ComfyUI's model folder management was better. It would be great to just specify the root directory and not have to explicitly list every single model type.

I suspect there could be more users tripped over this.
The https://github.com/Comfy-Org/ComfyUI/blob/master/extra_model_paths.yaml.example template does not include inpaint model type and neither does [folder_paths.py](https://github.com/Comfy-Org/ComfyUI/blob/master/folder_paths.py). So there is a big chance that users who use `extra_model_paths.yaml` do not have `inpaint` it listed there, causing model not found issues.

**Comment by Nodael** [comment]
i still have the same issue for this with comfydestop , i added the inpaint folder on the yaml file ,but still get indetected on krita diffusion :/

> # ComfyUI extra_model_paths.yaml for win32
comfyui_migration:
  inpaint: models\inpaint\
  checkpoints: models\checkpoints\
  classifiers: models\classifiers\
  clip: models\clip\
  clip_vision: models\clip_vision\
  configs: models\configs\
  controlnet: models\controlnet\
  diffusers: models\diffusers\
  diffusion_models: models\diffusion_models\
  embeddings: models\embeddings\
  gligen: models\gligen\
  hypernetworks: models\hypernetworks\
  loras: models\loras\
  photomaker: models\photomaker\
  style_models: models\style_models\
  text_encoders: models\text_encoders\
  unet: models\unet\
  upscale_models: models\upscale_models\
  vae: models\vae\
  vae_approx: models\vae_approx\
  animatediff_models: models\animatediff_models\
  animatediff_motion_lora: models\animatediff_motion_lora\
  animatediff_video_formats: models\animatediff_video_formats\
  ipadapter: models\ipadapter\
  liveportrait: models\liveportrait\
  insightface: models\insightface\
  layerstyle: models\layerstyle\
  LLM: models\LLM\
  Joy_caption: models\Joy_caption\
  sams: models\sams\
  blip: models\blip\
  CogVideo: models\CogVideo\
  xlabs: models\xlabs\
  instantid: models\instantid\
  base_path: C:\pinokio\api\comfy.git\app

comfyui_desktop:
  is_default: "true"
  custom_nodes: custom_nodes/
  download_model_base: models
  base_path: C:\Users\aaa\Documents\ComfyUI
desktop_extensions:
  custom_nodes: C:\aaa\AppData\Local\Programs\ComfyUI\resources\ComfyUI\custom_nodes`
