### ISSUE TITLE
ComfyUI ERROR (IMPORT FAILED): E:\ComfyUI_Portable\ComfyUI\custom_nodes\comfyui_controlnet_aux

### ISSUE THREAD

**Issue by pendave** [Acly/krita-ai-diffusion#1498]
I reinstall the new version of ComfyUI, but here's the Error for Krita in client.log:

2024-12-19 13:27:45,524 ERROR Missing required node InpaintPreprocessor from package ControlNet Preprocessors (https://github.com/Fannovel16/comfyui_controlnet_aux)

in Comfy UI:
`Traceback (most recent call last):
File "E:\ComfyUI_Portable\ComfyUI\nodes.py", line 2072, in load_custom_node
module_spec.loader.exec_module(module)
File "", line 883, in exec_module
File "", line 241, in call_with_frames_removed
File "E:\ComfyUI_Portable\ComfyUI\custom_nodes\comfyui_controlnet_aux_init.py", line 2, in
from .utils import here, define_preprocessor_inputs, INPUT
ImportError: cannot import name 'define_preprocessor_inputs' from 'comfyui_controlnet_aux.utils' (E:\ComfyUI_Portable\py
thon_embeded\lib\site-packages\filterpy-0.0.15-py3.10.egg\comfyui_controlnet_aux\utils.py)

Cannot import E:\ComfyUI_Portable\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: cannot import nam
e 'define_preprocessor_inputs' from 'comfyui_controlnet_aux.utils' (E:\ComfyUI_Portable\python_embeded\lib\site-packages
\filterpy-0.0.15-py3.10.egg\comfyui_controlnet_aux\utils.py)`

**Comment by pendave** [comment]
I get several utils.py

E:\ComfyUI_Portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py
it has 
`def define_preprocessor_inputs(**arguments):
    return dict(
        required=dict(image=INPUT.IMAGE()),
        optional=arguments
    )`

E:\ComfyUI_Portable\python_embeded\Lib\site-packages\filterpy-0.0.15-py3.10.egg\comfyui_controlnet_aux\utils.py
it does not have `def define_preprocessor_inputs(**arguments):`

So the import stuff got messed up. How to fix it?

**Comment by Acly** [comment]
> E:\ComfyUI_Portable\python_embeded\Lib\site-packages\filterpy-0.0.15-py3.10.egg\comfyui_controlnet_aux

I have no idea what that is or where it came from, looks like you installed something that now causes a conflict. I'd say get rid of it?

Anyway this isn't related to the plugin...

**Comment by pendave** [comment]
Sure, everything works right after I get rid of the 

> E:\ComfyUI_Portable\python_embeded\Lib\site-packages\filterpy-0.0.15-py3.10.egg\comfyui_controlnet_aux

which has higher privilege.

**Comment by pendave** [comment]
Why is the filterpy package installed? I downloaded a version of ComfyUI made by others, and there is \python_embeded\Lib\site-packages\filterpy-0.0.15-py3.10.egg in it, and it contains content related to ComfyUI's plugins. However, this filterpy is not included in the officially downloaded ComfyUI.
Why is this the case?

**Comment by Acly** [comment]
no idea, presumably whoever made the package had some idea about it
