### ISSUE TITLE
Selection via inpainting/generating new images not working in Krita and generating an error message

### ISSUE THREAD

**Issue by Shangooriginal** [Acly/krita-ai-diffusion#158]
ISSUE: whenever I try to use the selection tool to select an area to inpaint/generate a new image, it throws up the below error message.
FYI: I am using the latest version of the plugin as well. Also, I did an update Comfyui just before using the latest version of the plugin. 

2023-11-30 11:54:58,450 ERROR Error: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}} (Error transferring http://127.0.x.x:xxxx/prompt - server replied: Bad Request)
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 22, in _report_errors
    return await coro
  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\ui\model.py", line 249, in _generate
    job_id = await client.enqueue(job)
  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 211, in enqueue
    result = await self._post("prompt", data)
  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 207, in _post
    return await self._requests.post(f"{self.url}/{op}", data)
ai_diffusion.network.NetworkError: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}} (Error transferring http://127.0.x.x:xxxx/prompt - server replied: Bad Request)

**Comment by Acly** [comment]
By latest version you mean 1.8.2? Because this sounds a lot like #138 which should be fixed there.
Can you check ComfyUI output for the full error message?

**Comment by Acly** [comment]
Oh nevermind, ComfyUI_IPAdapter_plus got changed again yesterday, breaking existing workflows. So for now it's incompatible.

Are you using git? If so you can go easily go back to previous version by going into folder `...\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus` and run
```
git checkout 6bb44bb0ab99333c5ba02875c9f722530cd813d2
``

**Comment by Danamir** [comment]
Dammit they added a new parameter... again !

![image](https://github.com/Acly/krita-ai-diffusion/assets/15424198/3279d74c-d205-47c6-9e2f-5aceecfa4072)

I'll do a fix.

**Comment by Acly** [comment]
Can we just take the node parameters from `object_info` and supply any that we don't specify explicitly? They do have defaults.

It might be a bit of work to match the correct type. But some kind of forwards-compatibility might be achieved...

**Comment by Danamir** [comment]
>  They do have defaults

I was just wondering if we can get the default value. I just fixed the code with the same method as before, but it's not very pretty. I'll create a PR to investigate a cleaner method to do this.

**Comment by Shangooriginal** [comment]
@Acly. Reverting back to the previous version of the  ComfyUI_IPAdapter_plus fixed the issue for me. Thanks.
