### ISSUE TITLE
Server doesn't always stop

### ISSUE THREAD

**Issue by DFarley100** [Acly/krita-ai-diffusion#196]
I don't know if this thing is unique to me or it happens to other people, but I sometimes get into a situation where the server is stopped according to the plugin control panel. Except it isn't. When I try to start it I get the log snippet below (which is a mass of tiny red text in the plugin window). Scroll all the way to the end and there's the problem. Finding the PID and manually killing the server does the trick. All those other errors seem to go away, too. Thanks. David

Edit: Win11 Enterprise 23H2

2023-12-06 19:25:58,041 INFO Total VRAM 16380 MB, total RAM 32610 MB
2023-12-06 19:25:58,411 INFO Set vram state to: NORMAL_VRAM
2023-12-06 19:25:58,411 INFO Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2023-12-06 19:25:58,411 INFO VAE dtype: torch.bfloat16
2023-12-06 19:25:58,572 INFO Using pytorch cross attention
2023-12-06 19:25:59,511 INFO 
2023-12-06 19:25:59,511 INFO Import times for custom nodes:
2023-12-06 19:25:59,511 INFO 0.0 seconds: H:\sd-krita\ComfyUI\custom_nodes\comfyui-tooling-nodes
2023-12-06 19:25:59,511 INFO 0.0 seconds: H:\sd-krita\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2023-12-06 19:25:59,511 INFO 0.0 seconds: H:\sd-krita\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2023-12-06 19:25:59,511 INFO 0.3 seconds: H:\sd-krita\ComfyUI\custom_nodes\comfyui_controlnet_aux
2023-12-06 19:25:59,511 INFO 
2023-12-06 19:25:59,978 INFO 
2023-12-06 19:25:59,978 ERROR H:\sd-krita\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:24: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "H:\sd-krita\ComfyUI\main.py", line 201, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "H:\sd-krita\ComfyUI\main.py", line 105, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "H:\sd-krita\ComfyUI\server.py", line 614, in start
    await site.start()
  File "H:\sd-krita\python\lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
  File "asyncio\base_events.py", line 1519, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by Acly** [comment]
The plugin stops the server process when Krita is closed. But if Krita crashes or is killed the process "leaks" and you get this issue. It shouldn't be common though...
There are some ways to improve this, only they're a bit messy.

**Comment by DanielAdolfsson** [comment]
Happens on Linux at times as well. 

I don't think a solution would be too messy.

On linux we could use PR_SET_PDEATHSIG, and on Windows we could use a Job object instead (ensuring the Job exits when no one holds the handle.)

Just a thought

**Comment by Acly** [comment]
Yes that would be the preferred solution. It's "a bit messy" because platform-dependent code, WinAPI, and need to test on multiple OS (hope the linux/posix solution also works for mac).

But I didn't mean to imply that it can't/shouldn't be done, just that for a seemingly simple problem it requires quite a bit of work.

**Comment by Acly** [comment]
Fixed in [1.14.1](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.14.1) (for Windows & Linux)
