### ISSUE TITLE
--nohalf not implemented for macs?

### ISSUE THREAD

**Issue by deadcat000** [Acly/krita-ai-diffusion#219]
getting RuntimeError: "upsample_nearest2d_channels_last" not implemented for 'Half' shortly after I start image generation.
I can run the plugin with my own ComfyUI server, but the one managed by the plugin seems not to be using the --nohalf argument
OSX 12.6 / Krita 5.2.2 / krita_ai_diffusion 1.10.0

**Comment by Acly** [comment]
No it doesn't, #104 suggested fp16 for Apple silicon MPS. Is this tied to specific hardware? Or are you using CPU?

**Comment by deadcat000** [comment]
Still trying to troubleshoot... I tried by letting the plugin download the model himself. no cigar. I wonder if the model has to be converted to fp16 first. (in that case I guess the plugin should download the right model instead or convert it)
Here's a bit from my log file if it helps:
```
2023-12-13 13:28:18,499 INFO Total VRAM 65536 MB, total RAM 65536 MB
2023-12-13 13:28:18,499 INFO Forcing FP16.
2023-12-13 13:28:18,819 INFO Set vram state to: SHARED
2023-12-13 13:28:18,820 INFO Device: mps
2023-12-13 13:28:18,820 INFO VAE dtype: torch.float32
2023-12-13 13:28:18,940 INFO Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2023-12-13 13:28:19,720 INFO 
2023-12-13 13:28:19,720 INFO Import times for custom nodes:
2023-12-13 13:28:19,720 INFO 0.0 seconds: /Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/custom_nodes/comfyui-tooling-nodes
2023-12-13 13:28:19,720 INFO 0.0 seconds: /Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2023-12-13 13:28:19,720 INFO 0.0 seconds: /Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
2023-12-13 13:28:19,720 INFO 0.5 seconds: /Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/custom_nodes/comfyui_controlnet_aux
2023-12-13 13:28:19,720 INFO 
2023-12-13 13:28:19,720 INFO Starting server
2023-12-13 13:28:19,720 INFO 
2023-12-13 13:28:19,720 INFO To see the GUI go to: http://127.0.0.1:8188
2023-12-13 13:28:19,758 INFO [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: /Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts[0m
2023-12-13 13:28:19,758 INFO [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2023-12-13 13:28:19,758 INFO [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider'][0m
2023-12-13 13:28:19,758 INFO /Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:25: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
2023-12-13 13:28:19,758 INFO warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
2023-12-13 13:29:15,659 INFO got prompt
2023-12-13 13:29:15,739 INFO model_type EPS
2023-12-13 13:29:15,739 INFO adm 0
2023-12-13 13:29:15,919 INFO Using split attention in VAE
2023-12-13 13:29:15,919 INFO Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
2023-12-13 13:29:15,919 INFO Using split attention in VAE
2023-12-13 13:29:16,539 INFO missing {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
2023-12-13 13:29:16,539 INFO left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
2023-12-13 13:29:16,559 INFO Requested to load SD1ClipModel
2023-12-13 13:29:16,559 INFO Loading 1 new model
2023-12-13 13:29:16,679 INFO Requested to load BaseModel
2023-12-13 13:29:16,679 INFO Loading 1 new model
2023-12-13 13:29:17,897 INFO 0%|          | 0/6 [00:00<?, ?it/s]/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/nn/functional.py:3983: UserWarning: MPS: 'nearest' mode upsampling is supported natively starting from macOS 13.0. Falling back on CPU. This may have performance implications. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/UpSample.mm:255.)
2023-12-13 13:29:17,898 INFO return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
2023-12-13 13:29:17,898 INFO 0%|          | 0/6 [00:00<?, ?it/s]
2023-12-13 13:29:17,918 INFO ERROR:root:!!! Exception during processing !!!
2023-12-13 13:29:17,938 INFO ERROR:root:Traceback (most recent call last):
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/execution.py", line 153, in recursive_execute
2023-12-13 13:29:17,939 INFO output_data, output_ui = get_output_data(obj, input_data_all)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/execution.py", line 83, in get_output_data
2023-12-13 13:29:17,939 INFO return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/execution.py", line 76, in map_node_over_list
2023-12-13 13:29:17,939 INFO results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/nodes.py", line 1333, in sample
2023-12-13 13:29:17,939 INFO return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/nodes.py", line 1269, in common_ksampler
2023-12-13 13:29:17,939 INFO samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/sample.py", line 100, in sample
2023-12-13 13:29:17,939 INFO samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/samplers.py", line 711, in sample
2023-12-13 13:29:17,939 INFO return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/samplers.py", line 617, in sample
2023-12-13 13:29:17,939 INFO samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/samplers.py", line 556, in sample
2023-12-13 13:29:17,939 INFO samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2023-12-13 13:29:17,939 INFO return func(*args, **kwargs)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/k_diffusion/sampling.py", line 745, in sample_lcm
2023-12-13 13:29:17,939 INFO denoised = model(x, sigmas[i] * s_in, **extra_args)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2023-12-13 13:29:17,939 INFO return self._call_impl(*args, **kwargs)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2023-12-13 13:29:17,939 INFO return forward_call(*args, **kwargs)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/samplers.py", line 277, in forward
2023-12-13 13:29:17,939 INFO out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
2023-12-13 13:29:17,939 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2023-12-13 13:29:17,940 INFO return self._call_impl(*args, **kwargs)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2023-12-13 13:29:17,940 INFO return forward_call(*args, **kwargs)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/samplers.py", line 267, in forward
2023-12-13 13:29:17,940 INFO return self.apply_model(*args, **kwargs)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/samplers.py", line 264, in apply_model
2023-12-13 13:29:17,940 INFO out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/samplers.py", line 252, in sampling_function
2023-12-13 13:29:17,940 INFO cond, uncond = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/samplers.py", line 230, in calc_cond_uncond_batch
2023-12-13 13:29:17,940 INFO output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/model_base.py", line 83, in apply_model
2023-12-13 13:29:17,940 INFO model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2023-12-13 13:29:17,940 INFO return self._call_impl(*args, **kwargs)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2023-12-13 13:29:17,940 INFO return forward_call(*args, **kwargs)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 888, in forward
2023-12-13 13:29:17,940 INFO h = forward_timestep_embed(module, h, emb, context, transformer_options, output_shape, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 50, in forward_timestep_embed
2023-12-13 13:29:17,940 INFO x = layer(x, output_shape=output_shape)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
2023-12-13 13:29:17,940 INFO return self._call_impl(*args, **kwargs)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
2023-12-13 13:29:17,940 INFO return forward_call(*args, **kwargs)
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 95, in forward
2023-12-13 13:29:17,940 INFO x = F.interpolate(x, size=shape, mode="nearest")
2023-12-13 13:29:17,940 INFO File "/Users/nicola/My Drive/presets/krita sync/pykrita/ai_diffusion/.server/venv/lib/python3.9/site-packages/torch/nn/functional.py", line 3983, in interpolate
2023-12-13 13:29:17,940 INFO return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
2023-12-13 13:29:17,940 INFO RuntimeError: "upsample_nearest2d_channels_last" not implemented for 'Half'
```

**Comment by Acly** [comment]
Models are almost all stored as fp16, but they can be used when doing computations in fp32, no need to have multiple versions. Can't help with the error though. Recommendation to use --force-fp16 comes [from here](https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#apple-mac-silicon) - maybe it's on issue with torch version, but according to other mac users nightly was not needed.

**Comment by deadcat000** [comment]
since --force-fp16 isn't recognised in my own comfy UI and Automatic1111 installations, I'm guessing it's a problem with the version of pytorch. On my server I am using the latest Automatic111 installation, which gives me python: 3.10.8  and  torch: 2.0.1 
I start wondering if the OSX might be the culprit... they say from 12.3 on pytorch site (i'm on 12.6), but I might just try and upgrade to 13 as soon as I have some time. I could also try and install a new ComfyUI server with the same Pytorch and Python as yours.
I am supposing you are using pytorch 2.1 and Python 3.11 in the plugin? Correct?

**Comment by Acly** [comment]
For the record, I removed the `--force-fp16` in version 1.16.0 of the plugin since I'm not convinced it's a good idea. That means you can decide to
* run without any flags (default)
* set `--force-fp16` (maybe better performance)
* set `--force-fp32` (if you get Half-related errors, similar to --nohalf in A1111)

Info on how to pass command line arguments when you use the plugin installer [here](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#how-do-i-pass-additional-arguments-to-comfyui)

**Comment by deadcat000** [comment]
Cool. And also for the record, I discovered that version 13 of OS X is needed and not 12.3 as stated on PyTorchs page.
