### ISSUE TITLE
Does this plug-in have compatibility issues with fp8?

### ISSUE THREAD

**Issue by NoMansPC** [Acly/krita-ai-diffusion#229]
ComfyUI supports fp8, which I have been using since it saves a lot of VRAM. However, in some instances, like when inpainting with 100% strength or using controlnet, I get the following error:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
Prompt executed in 4.64 seconds
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 403, in apply_ipadapter
    image_prompt_embeds, uncond_image_prompt_embeds = self.ipadapter.get_image_embeds(clip_embed.to(self.device, self.dtype), clip_embed_zeroed.to(self.device, self.dtype))
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 211, in get_image_embeds
    image_prompt_embeds = self.image_proj_model(clip_embed)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 54, in forward
    clip_extra_context_tokens = self.proj(embeds).reshape(-1, self.clip_extra_context_tokens, self.cross_attention_dim)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "N:\Stable Diffusion WebUI\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_cuda" not implemented for 'Float8_e4m3fn'

I posted about this in the ComfyUI's page, but I'm posting here just in case.

**Comment by Acly** [comment]
Specifically it is [ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus) which seems to be incompatible. It's used as part of the 100% inpaint pipeline. You could try raising an issue there (though it may not be easy to support it).

**Comment by NoMansPC** [comment]
Done. For now I guess that the solution is reloading ComfyUI on fp16 when that error pops up.
