### ISSUE TITLE
Getting the message " Error: Error during installation: xcrun: error: cannot be used within an App Sandbox. " on OSX

### ISSUE THREAD

**Issue by Aedant13** [Acly/krita-ai-diffusion#250]
Hi, I REALLY wish to use this amazing plugin, but it seems I can,t install the server... I get the following message when trying to install in this directory : /Users/franck/Library/Application Support/krita/pykrita/ai_diffusion/.Server

Error: Error during installation: xcrun: error: cannot be used within an App Sandbox.

Is there a way to solve that?

Here are my mac specs

<img width="267" alt="Screenshot 2023-12-19 at 11 05 41 AM" src="https://github.com/Acly/krita-ai-diffusion/assets/118572026/f9ead74a-a094-41ca-9408-e5545b8ecb91">

<img width="1380" alt="Screenshot 2023-12-19 at 11 02 22 AM" src="https://github.com/Acly/krita-ai-diffusion/assets/118572026/737948a4-ad7b-4b5c-91fd-c0f2f716f359">

Here is the log

2023-12-19 10:47:50,228 INFO Extension initialized, Version: 1.10.0, Python: 3.10.7 (main, Nov  1 2023, 10:10:21) [Clang 13.0.0 (clang-1300.0.29.30)]
2023-12-19 10:47:51,765 INFO Connecting to http://127.0.0.1:8188
2023-12-19 10:48:21,934 INFO Installation started in /Users/franck/Library/Application Support/krita/pykrita/ai_diffusion/.server
2023-12-19 10:48:21,943 INFO Creating venv in /Users/franck/Library/Application Support/krita/pykrita/ai_diffusion/.server/venv
2023-12-19 10:48:21,943 INFO Executing /usr/bin/python3 -m venv venv
2023-12-19 10:48:22,188 ERROR Error during installation: xcrun: error: cannot be used within an App Sandbox.
Traceback (most recent call last):
  File "/Users/franck/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 265, in install
    await self._install(cb)
  File "/Users/franck/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 148, in _install
    await install_if_missing(python_dir, self._create_venv, cb)
  File "/Users/franck/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 572, in install_if_missing
    await try_install(path, installer, *args)
  File "/Users/franck/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 567, in try_install
    raise e
  File "/Users/franck/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 562, in try_install
    await installer(*args)
  File "/Users/franck/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 197, in _create_venv
    await _execute_process("Python", venv_cmd, self.path, cb)
  File "/Users/franck/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 556, in _execute_process
    raise Exception(f"Error during installation: {errlog}")
Exception: Error during installation: xcrun: error: cannot be used within an App Sandbox.

**Comment by pitxels** [comment]
same issue here

**Comment by aotsukiqx** [comment]
same with me on M2 mac studio

**Comment by VojtechHermann** [comment]
Same with M1 Pro MacBook Pro 14. Any ideas how to fix that?

**Comment by pavelkrivka** [comment]
Same with M1 Max MacBook Pro 16, OS Sanoma 14.4.1. 
Krita 5.2.1.
krita_ai_diffusion-1.16.1

**Comment by Acly** [comment]
Ok I don't know anything about macOS. But I suspect installation can never work from Sandbox. It's meant to prevent the application from installing stuff and making similar changes.

I'm not sure when Krita runs in Sandbox vs not, my guess is the App Store version runs Sandboxed. You can download it directly from [krita.org](https://krita.org/) it should work?

**Comment by ApproximateMan** [comment]
Dears, I'm facing the same problem-I can't find a way to solve it. Did anyone manage to find a solution?
