### ISSUE TITLE
error when using Upscale  with refine upscaled image

### ISSUE THREAD

**Issue by nabileisa** [Acly/krita-ai-diffusion#264]
Hi , thanks for the great work.
I' was trying to use your extension and got this error when attempting to upscale an image in comfy consol
I'm using ComfyUI server 
this error in krita

![image](https://github.com/Acly/krita-ai-diffusion/assets/6467131/332cc515-d86d-4f68-a4c6-3d4b92e4aae0)
and this error in ComfyUI console
`
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
got prompt
ERROR:root:Failed to validate prompt for output 11:
ERROR:root:* UltimateSDUpscale 10:
ERROR:root:  - Required input is missing: tiled_decode
ERROR:root:Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
`

**Comment by Acly** [comment]
Hi, this is probably related to a recent (4 days ago) update for [ComfyUI_UltimateSDUpscale](https://github.com/ssitu/ComfyUI_UltimateSDUpscale). You can try going to an older version.

But I also added some code in (just released) [1.11.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.11.0) to handle these kinds of issues, and it works for me even with the latest ComfyUI_UltimateSDUpscale. Which version of the plugin are you using?

**Comment by nabileisa** [comment]
I was using version 1.10.0 , I tested the latest 1.11.0  and I seem to be unable to connect to the server at all
![image](https://github.com/Acly/krita-ai-diffusion/assets/6467131/8175fe46-3d63-4481-a8dc-cb9f13e87878)
here is the log file 
[client.log](https://github.com/Acly/krita-ai-diffusion/files/13759478/client.log)

**Comment by Acly** [comment]
That was my bad (see #266), I did a quick fix and patched release: [1.11.1](https://github.com/Acly/krita-ai-diffusion/releases/download/v1.11.1/krita_ai_diffusion-1.11.1.zip)

**Comment by nabileisa** [comment]
Thanks for the quick fix and reply, server connection now works as before but still no luck with upscale.
It woks fine without but when enabled `refine upscaled image` but when enabled it throws this error

![image](https://github.com/Acly/krita-ai-diffusion/assets/6467131/4d6ca7e8-5e29-4338-ba55-64d47bd8bd8e)

And in comfy console

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 125, in upscale
    processed = script.run(p=sdprocessing, _=None, tile_width=tile_width, tile_height=tile_height,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 553, in run
    upscaler.process()
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 136, in process
    self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 243, in start
    return self.linear_process(p, image, rows, cols)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 178, in linear_process
    processed = processing.process_images(p)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\modules\processing.py", line 122, in process_images
    (samples,) = common_ksampler(p.model, p.seed, p.steps, p.cfg, p.sampler_name,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\nodes.py", line 1269, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\sample.py", line 101, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 129, in KSampler_sample
    return _KSampler_sample(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 138, in sample
    return _sample(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\samplers.py", line 622, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\samplers.py", line 561, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\k_diffusion\sampling.py", line 580, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\samplers.py", line 285, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\samplers.py", line 275, in forward
    return self.apply_model(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 992, in apply_model
    out = super().apply_model(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\samplers.py", line 272, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\samplers.py", line 252, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\samplers.py", line 201, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\controlnet.py", line 174, in get_control
    control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint, timesteps=timestep.float(), context=context.to(dtype), y=y)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\accelerate\hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\cldm\cldm.py", line 289, in forward
    guided_hint = self.input_hint_block(hint, emb, context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\accelerate\hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 62, in forward
    return forward_timestep_embed(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 52, in forward_timestep_embed
    x = layer(x)
        ^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\accelerate\hooks.py", line 159, in new_forward
    args, kwargs = module._hf_hook.pre_forward(module, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\accelerate\hooks.py", line 104, in pre_forward
    args, kwargs = hook.pre_forward(module, *args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\accelerate\hooks.py", line 286, in pre_forward
    set_module_tensor_to_device(
  File "F:\ComfyUI-Portable\ComfyUI\python_embeded\Lib\site-packages\accelerate\utils\modeling.py", line 317, in set_module_tensor_to_device
    new_value = value.to(device)
                ^^^^^^^^^^^^^^^^
NotImplementedError: Cannot copy out of meta tensor; no data!

Prompt executed in 16.78 seconds

```

One more bug I found , When I attempt to use custom fraction in the `scale` input ie:1.1, Krita would crash completely.

and once again thank you for the amazing work you are doing here ❤

**Comment by Acly** [comment]
That's a new error, haven't seen it before. I don't think it's related to the krita plugin, can you check if [ComfyUI_UltimateSDUpscale](https://github.com/ssitu/ComfyUI_UltimateSDUpscale) works in ComfyUI or shows the same problem?

**Comment by nabileisa** [comment]
Yes, it works fine in ComfyUI itself , the problem show up only when using krita,
here is wroking test images and workflow from comfy
 
[output.zip](https://github.com/Acly/krita-ai-diffusion/files/13761481/output.zip)

**Comment by Acly** [comment]
That's good to know. I'm attaching the workflow dumped from the plugin. It's not very complex, the most important difference is that it uses tile control net. The error message mentions control net, so probably that is involved.

[upscale.json](https://github.com/Acly/krita-ai-diffusion/files/13761698/upscale.json)

It works fine for me, but I would expect it to produce the same error when you drag it into ComfyUI, maybe it gives a hint what exactly is causing it.

Btw if you want to dump workflows, you can go to [client.py line 202](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/client.py#L202) and add a line like this:
```
workflow.dump("C:/upscale.json")
```

**Comment by nabileisa** [comment]
Thanks for posting the workflow , that helped point me in the right direction.
Turns out that  I was missing  [ControlNet tile Lora](https://huggingface.co/comfyanonymous/ControlNet-v1-1_fp16_safetensors/resolve/main/control_lora_rank128_v11f1e_sd15_tile_fp16.safetensors)  in my install, I have that full  model  `control_v11f1e_sd15_tile_fp16.safetensors` installed and assumed it would work and didn't check the link in the guide, turns out I was wrong 😂

If possible may be you could update the guide to indicate that it is the `lora` version that is needed ,so that no one makes my mistake in the future 
Consider the upscaling issue resolved.

----------------
What remains  is the issue of Krita crashing when I try manually enter a number as scaling factor 
when I change it using the arrows from 2 -> 1.5 -> 1 it works fine , but when I try to enter a number into the input like for example 1.25  the application freeze and crash
hope you can look into it when you have time.

And thank you for your help and thank you for the great work on this project.

**Comment by Acly** [comment]
> I have that full model control_v11f1e_sd15_tile_fp16.safetensors installed and assumed it would work and didn't check the link in the guide, turns out I was wrong

You're not wrong though, the full model should work too. I have an ancient version (`control_v11f1e_sd15_tile.pth`) still lying around and it works, just downloaded `control_v11f1e_sd15_tile_fp16.safetensors` and it's fine too... maybe there was something wrong with the file?

> What remains is the issue of Krita crashing when I try manually enter a number as scaling factor

Yep I'm getting that too, will keep this open and look into it

**Comment by nabileisa** [comment]
> > I have that full model control_v11f1e_sd15_tile_fp16.safetensors installed and assumed it would work and didn't check the link in the guide, turns out I was wrong
> 
> You're not wrong though, the full model should work too. I have an ancient version (`control_v11f1e_sd15_tile.pth`) still lying around and it works, just downloaded `control_v11f1e_sd15_tile_fp16.safetensors` and it's fine too... maybe there was something wrong with the file?



I tested `control_v11f1e_sd15_tile_fp16.safetensors` directly in ComfyUI and it produced the same error with `UltimateSDUpscale` but no error when used with a `ksampler` directly so the file is fine.

After some research, from what I found this https://github.com/ssitu/ComfyUI_UltimateSDUpscale/issues/26 , it's an issue related to ComfyUI_UltimateSDUpscale not this extension.

Anyway just to be sure I updated every thing I have installed and tried again , and now the error went away, probably was a compatibility issue but I'm not sure.
