### ISSUE TITLE
KeyError: 'required' upon connecting to remote server.

### ISSUE THREAD

**Issue by irldoggo** [Acly/krita-ai-diffusion#266]
Hey, I am getting this error upon trying to connect to another machine on my local network, I have all the required dependencies installed. It was working fine in previous updates, but I updated today and now it refuses to connect. Is this an issue on my end or is there something up with the latest version?

**Client.log output:**
```
2023-12-23 07:53:24,739 INFO Connecting to http://x.x.x.x:8188
2023-12-23 07:53:25,146 ERROR Error: 'required'
Traceback (most recent call last):
  File "/home/USER/.local/share/krita/pykrita/ai_diffusion/connection.py", line 48, in _connect
    self._client = await Client.connect(url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.local/share/krita/pykrita/ai_diffusion/client.py", line 150, in connect
    client.nodes_inputs = {name: nodes[name]["input"]["required"] for name in nodes}
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.local/share/krita/pykrita/ai_diffusion/client.py", line 150, in <dictcomp>
    client.nodes_inputs = {name: nodes[name]["input"]["required"] for name in nodes}
                                 ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'required'
```

**Comment by Acly** [comment]
Hmm it's caused by a change in the latest version, and probably some custom nodes you have installed, to explain why I didn't see this error.

**Comment by Acly** [comment]
I patched the release: https://github.com/Acly/krita-ai-diffusion/releases/download/v1.11.1/krita_ai_diffusion-1.11.1.zip

**Comment by irldoggo** [comment]
Thanks for the quick fix. Seems to be working now!

**Comment by Molinist** [comment]
Hi, I think I got similar error:

2023-12-29 22:37:14,808 INFO Connecting to http://x.x.x.x:8188
2023-12-29 22:37:14,984 ERROR Error: 'required'
Traceback (most recent call last):
  File "C:\Users\theop\AppData\Roaming\krita\pykrita\ai_diffusion\connection.py", line 48, in _connect
    self._client = await Client.connect(url)
  File "C:\Users\theop\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 150, in connect
    client.nodes_inputs = {name: nodes[name]["input"]["required"] for name in nodes}
  File "C:\Users\theop\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 150, in <dictcomp>
    client.nodes_inputs = {name: nodes[name]["input"]["required"] for name in nodes}
KeyError: 'required'
