### ISSUE TITLE
DirectML on Radeon RX 6600 not working.

### ISSUE THREAD

**Issue by Richard127** [Acly/krita-ai-diffusion#279]
Not running on my Radeon RX6600 GPU. It runs on CPU only, but is hopelessly slow.
With RX 6600, I get this error log.

2023-12-27 01:12:06,940 ERROR Traceback (most recent call last):
File "C:\Users\Richard\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\[main.py](https://main.py/)", line 72, in <module> import execution
File "C:\Users\Richard\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\[execution.py](https://execution.py/)", line 12, in <module> import nodes
File "C:\Users\Richard\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\[nodes.py](https://nodes.py/)", line 20, in <module> import comfy.diffusers_load
File "C:\Users\Richard\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\diffusers_load.py", line 4, in <module> import [comfy.sd](https://comfy.sd/)
File "C:\Users\Richard\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\[sd.py](https://sd.py/)", line 5, in <module> from comfy import model_management
File "C:\Users\Richard\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\model_management.py", line 114, in <module> total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
File "C:\Users\Richard\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\model_management.py", line 83, in get_torch_device return torch.device(torch.cuda.current_device())
File "C:\Users\Richard\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages\torch\cuda\__init__.py", line 769, in current_device_lazy_init()
File "C:\Users\Richard\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages\torch\cuda\__init__.py", line 298, in _lazy_init
torch._C._cuda_init()

Would appreciate any ideas of how to fix. Many thanks in advance

**Comment by Acly** [comment]
You do have DirectML selected, not CUDA? Asking because the error is the first thing you run into when server is started with CUDA and is skipped with DirectML...

**Comment by Richard127** [comment]
Yes, definitely have DirectML selected. If I choose CUDA, I get a much longer error list starting with no NVidia graphics card found.

**Comment by Richard127** [comment]
I don't understand why Cuda is mentioned in the last line of the error log. Everything is installed DirectML is definitely selected for the server. I can't use CPU only as it takes forever just to do simple renders.

**Comment by LanceSpear11** [comment]
Hi I have the same issue.  
In the lower right the progress of generation stays still, 
In task manager I see no cpu usage, no gpu usage,  but my RAM is  overflowed.  By overflowed it doubled, from 7-8 to 16.6 and 
flatlined after that. 
On the left you can see the DirectML is selected. 
I have a Ryzen CPU 3900x and a RX 7900xtx. 

![image](https://github.com/Acly/krita-ai-diffusion/assets/155374065/2b033db7-8beb-4b7a-855f-6430b76f2764)

**Comment by Richard127** [comment]
I've given up and deleted Krita, it was winding me up so much. It wouldn't
be so bad if all the online software wasn't subscription.

**Comment by LanceSpear11** [comment]
I just  fixed it, I have a 4K LGC3 tv as a monitor,  and Krita defaulted a almost  4k resolution for the file, Dropped to Full HD 1920*1080  and  now it works. Now to figure out the rest.

**Comment by Kogije** [comment]
From the initial post it seems there are Nvidia Drivers lingering on the system that confuse the install, if anyone else has this same issue and no Nvidia card try removing any old Nvidia Drivers that are lingering on your system before installing this!
Also...
Not sure on current version but torch-directml was not automatically installed on 1.10, under command prompt you can use: C:\Users\%username%\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python -m pip install torch-directml==0.2.0.dev230426 (as of 01/07/24 this works to resolve missing torch-directml errors and works with torch 2.0.0. There doesn't seem to be any working torch-directml for torch 2.1.2 as of yet.)
