### ISSUE TITLE
[BUG] An exception of unknown nature

### ISSUE THREAD

**Issue by Pirog17000** [Acly/krita-ai-diffusion#324]
I honestly don't understand what triggers the error, but it began to happen very often as I have updated to 1.12 version

```
A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

Roaming\krita\pykrita\ai_diffusion\model.py in update_preview(self=<ai_diffusion.model.Model object>)
  292     def update_preview(self):
  293         if selection := self.jobs.selection:
  294             self.show_preview(selection.job, selection.image)
  295         else:
  296             self.hide_preview()
self = <ai_diffusion.model.Model object>
self.show_preview = <bound method Model.show_preview of <ai_diffusion.model.Model object>>
selection = Item(job='f98d3f95-06f8-4e0c-b634-2f5be03c00ed', image=0)
selection.job = 'f98d3f95-06f8-4e0c-b634-2f5be03c00ed'
selection.image = 0

Roaming\krita\pykrita\ai_diffusion\model.py in show_preview(self=<ai_diffusion.model.Model object>, job_id='f98d3f95-06f8-4e0c-b634-2f5be03c00ed', index=0, name_prefix='Preview')
  304         if self._layer is not None:
  305             self._layer.setName(name)
  306             self._doc.set_layer_content(self._layer, job.results[index], job.params.bounds)
  307             self._doc.move_to_top(self._layer)
  308         else:
self = <ai_diffusion.model.Model object>
self._doc = <ai_diffusion.document.KritaDocument object>
self._doc.set_layer_content = <bound method KritaDocument.set_layer_content of <ai_diffusion.document.KritaDocument object>>
self._layer = <PyKrita.krita.Node object>
job = <ai_diffusion.jobs.Job object>
job.results = <ai_diffusion.image.ImageCollection object>
index = 0
job.params = JobParams(bounds=Bounds(x=0, y=0, width=640, hei...egative_prompt='', strength=0.79, seed=459605084)
job.params.bounds = Bounds(x=0, y=0, width=640, height=1100)

Roaming\krita\pykrita\ai_diffusion\document.py in set_layer_content(self=<ai_diffusion.document.KritaDocument object>, layer=<PyKrita.krita.Node object>, img=<ai_diffusion.image.Image object>, bounds=Bounds(x=0, y=0, width=640, height=1100))
  227         if layer_bounds != bounds:
  228             # layer.cropNode(*bounds)  <- more efficient, but clutters the undo stack
  229             blank = Image.create(layer_bounds.extent, fill=0)
  230             layer.setPixelData(blank.data, *layer_bounds)
  231         layer.setPixelData(img.data, *bounds)
blank undefined
global Image = <class 'ai_diffusion.image.Image'>
Image.create = <function Image.create>
layer_bounds = Bounds(x=0, y=0, width=0, height=0)
layer_bounds.extent = Extent(width=0, height=0)
fill undefined

Roaming\krita\pykrita\ai_diffusion\image.py in create(extent=Extent(width=0, height=0), fill=0)
  196     @staticmethod
  197     def create(extent: Extent, fill=None):
  198         img = Image(QImage(extent.width, extent.height, QImage.Format_ARGB32))
  199         if fill is not None:
  200             img._qimage.fill(fill)
img undefined
global Image = <class 'ai_diffusion.image.Image'>
global QImage = <class 'PyQt5.QtGui.QImage'>
extent = Extent(width=0, height=0)
extent.width = 0
extent.height = 0
QImage.Format_ARGB32 = 5

Roaming\krita\pykrita\ai_diffusion\image.py in __init__(self=<ai_diffusion.image.Image object>, qimage=<PyQt5.QtGui.QImage object>)
  184 class Image:
  185     def __init__(self, qimage: QImage):
  186         assert qimage.format() in [QImage.Format_ARGB32, QImage.Format_Grayscale8]
  187         self._qimage = qimage
  188 
qimage = <PyQt5.QtGui.QImage object>
qimage.format = <built-in method format of QImage object>
global QImage = <class 'PyQt5.QtGui.QImage'>
QImage.Format_ARGB32 = 5
QImage.Format_Grayscale8 = 24
AssertionError: 
    __cause__ = None
    __class__ = <class 'AssertionError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of AssertionError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of AssertionError object>
    __doc__ = 'Assertion failed.'
    __eq__ = <method-wrapper '__eq__' of AssertionError object>
    __format__ = <built-in method __format__ of AssertionError object>
    __ge__ = <method-wrapper '__ge__' of AssertionError object>
    __getattribute__ = <method-wrapper '__getattribute__' of AssertionError object>
    __gt__ = <method-wrapper '__gt__' of AssertionError object>
    __hash__ = <method-wrapper '__hash__' of AssertionError object>
    __init__ = <method-wrapper '__init__' of AssertionError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of AssertionError object>
    __lt__ = <method-wrapper '__lt__' of AssertionError object>
    __ne__ = <method-wrapper '__ne__' of AssertionError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of AssertionError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of AssertionError object>
    __repr__ = <method-wrapper '__repr__' of AssertionError object>
    __setattr__ = <method-wrapper '__setattr__' of AssertionError object>
    __setstate__ = <built-in method __setstate__ of AssertionError object>
    __sizeof__ = <built-in method __sizeof__ of AssertionError object>
    __str__ = <method-wrapper '__str__' of AssertionError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ()
    with_traceback = <built-in method with_traceback of AssertionError object>
```

```
Traceback (most recent call last):
  File "..\Roaming\krita\pykrita\ai_diffusion\model.py", line 294, in update_preview
    self.show_preview(selection.job, selection.image)
  File "..\Roaming\krita\pykrita\ai_diffusion\model.py", line 306, in show_preview
    self._doc.set_layer_content(self._layer, job.results[index], job.params.bounds)
  File "..\Roaming\krita\pykrita\ai_diffusion\document.py", line 229, in set_layer_content
    blank = Image.create(layer_bounds.extent, fill=0)
  File "..\Roaming\krita\pykrita\ai_diffusion\image.py", line 198, in create
    img = Image(QImage(extent.width, extent.height, QImage.Format_ARGB32))
  File "..\Roaming\krita\pykrita\ai_diffusion\image.py", line 186, in __init__
    assert qimage.format() in [QImage.Format_ARGB32, QImage.Format_Grayscale8]
AssertionError
```

**Comment by Acly** [comment]
It looks like same root cause as #306, and (hopefully) gone after the fix
