### ISSUE TITLE
This is a SD XL checkpoint, but the SD XL workload has not been installed

### ISSUE THREAD

**Issue by JeffreyBull76** [Acly/krita-ai-diffusion#336]
Using this on a cloud deployed instance of comfyUI. I cannot get it to recognize that I have all the correct models (have ever IP adapter model in both locations, the clip vision models, all correctly renamed) 

Logs in the notebook throw this
---------------------------------------------------------
ERROR] An error occurred while retrieving information for the 'CR Select Font' node.
Traceback (most recent call last):
  File "/workspace/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/workspace/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_text.py", line 458, in INPUT_TYPES
    font_dir = os.path.join(system_root, 'Fonts')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] An error occurred while retrieving information for the 'CR Select Font' node.
Traceback (most recent call last):
  File "/workspace/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/workspace/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_text.py", line 458, in INPUT_TYPES
    font_dir = os.path.join(system_root, 'Fonts')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] An error occurred while retrieving information for the 'CR Select Font' node.
Traceback (most recent call last):
  File "/workspace/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/workspace/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_text.py", line 458, in INPUT_TYPES
    font_dir = os.path.join(system_root, 'Fonts')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] An error occurred while retrieving information for the 'CR Select Font' node.
Traceback (most recent call last):
  File "/workspace/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/workspace/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_text.py", line 458, in INPUT_TYPES
    font_dir = os.path.join(system_root, 'Fonts')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
[ERROR] An error occurred while retrieving information for the 'CR Select Font' node.
Traceback (most recent call last):
  File "/workspace/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
  File "/workspace/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_text.py", line 458, in INPUT_TYPES
    font_dir = os.path.join(system_root, 'Fonts')
  File "/usr/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
-------------------------------------------------------------------------

Reinstalled that repeatedly, Not sure what it even has to do with your extension?
Nothing works. The strangest thing is i can run the sdxl models in Krita despite them being marked with an exclamation and they work fine, it just refuses to accept the workload is complete.

**Comment by Acly** [comment]
The error message is related to ComfyUI_Comfyroll_CustomNodes which is not used by the plugin.

Regarding worklord not installed: you are probably missing the LCM LoRA. Generating images with other samplers will work, but LCM sampler and Live mode not. See [requirements](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md), troubleshooting section at the bottom will allow you to get precise hints what's missing.

**Comment by JeffreyBull76** [comment]
> The error message is related to ComfyUI_Comfyroll_CustomNodes which is not used by the plugin.
> 
> Regarding worklord not installed: you are probably missing the LCM LoRA. Generating images with other samplers will work, but LCM sampler and Live mode not. See [requirements](https://github.com/Acly/krita-ai-diffusion/blob/main/doc/comfy-requirements.md), troubleshooting section at the bottom will allow you to get precise hints what's missing.

----------------------------------

I have the LCM lora and its renamed correctly. Very strange.
