### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by kungful** [Acly/krita-ai-diffusion#349]
got prompt
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "D:\windowsAI\ComfyUI_windows\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "D:\windowsAI\ComfyUI_windows\python_embeded\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "D:\windowsAI\ComfyUI_windows\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "D:\windowsAI\ComfyUI_windows\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "D:\windowsAI\ComfyUI_windows\ComfyUI\server.py", line 469, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\windowsAI\ComfyUI_windows\ComfyUI\execution.py", line 598, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'LoraLoaderModelOnly'
![屏幕截图 2024-01-21 230521](https://github.com/Acly/krita-ai-diffusion/assets/84950880/2c12ae0f-3410-46ff-ac69-912ddfe1db99)

**Comment by kungful** [comment]
KeyError: 'LoraLoaderModelOnly'

**Comment by Acly** [comment]
That node is part of base ComfyUI. Probably you need to update it.

**Comment by kungful** [comment]
> The node is part of the underlying ComfyUI. Probably you need to update it.

Thank you for your answer，god bless you
