### ISSUE TITLE
Error when generating Blur/Tile controlnet image from visible.

### ISSUE THREAD

**Issue by vidiotgameboss** [Acly/krita-ai-diffusion#369]
2024-01-30 16:27:14,024 ERROR Error: Internal assertion failed []
Traceback (most recent call last):
  File "D:\Stable Diffusion\krita-x64-5.2.1\share\krita\pykrita\ai_diffusion\model.py", line 560, in _report_errors
    return await coro
  File "D:\Stable Diffusion\krita-x64-5.2.1\share\krita\pykrita\ai_diffusion\model.py", line 248, in _generate_control_layer
    work = workflow.create_control_image(client, image, mode, bounds)
  File "D:\Stable Diffusion\krita-x64-5.2.1\share\krita\pykrita\ai_diffusion\workflow.py", line 924, in create_control_image
    assert result is not None
AssertionError

**Comment by Acly** [comment]
The generate button should not be there for Blur/Tile. The input is just your image.
