### ISSUE TITLE
Installation error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 29: invalid continuation byte

### ISSUE THREAD

**Issue by MononcGeek** [Acly/krita-ai-diffusion#370]
When I try to install the server stuff I quickly get this error: 

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 29: invalid continuation byte

Here is the full log: 

2024-01-30 11:39:11,942 INFO Extension initialized, Version: 1.13.1, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2024-01-30 11:40:09,858 INFO Extension initialized, Version: 1.13.1, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2024-01-30 11:40:19,761 INFO Installation started in C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2024-01-30 11:40:19,769 INFO Downloading https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip to C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\python-3.10.11-embed-amd64.zip
2024-01-30 11:40:20,445 INFO Extracting C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\python-3.10.11-embed-amd64.zip to C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python
2024-01-30 11:40:20,541 INFO Patching C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python310._pth
2024-01-30 11:40:20,542 INFO Downloading https://bootstrap.pypa.io/get-pip.py to C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\get-pip.py
2024-01-30 11:40:21,133 INFO Executing C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\get-pip.py
2024-01-30 11:40:23,507 INFO Collecting pip
2024-01-30 11:40:23,507 INFO Using cached pip-23.3.2-py3-none-any.whl.metadata (3.5 kB)
2024-01-30 11:40:23,694 INFO Collecting setuptools
2024-01-30 11:40:23,694 INFO Using cached setuptools-69.0.3-py3-none-any.whl.metadata (6.3 kB)
2024-01-30 11:40:23,788 INFO Collecting wheel
2024-01-30 11:40:23,788 INFO Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
2024-01-30 11:40:23,850 INFO Using cached pip-23.3.2-py3-none-any.whl (2.1 MB)
2024-01-30 11:40:23,850 INFO Using cached setuptools-69.0.3-py3-none-any.whl (819 kB)
2024-01-30 11:40:23,850 INFO Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
2024-01-30 11:40:23,914 INFO Installing collected packages: wheel, setuptools, pip
2024-01-30 11:40:29,412 INFO Successfully installed pip-23.3.2 setuptools-69.0.3 wheel-0.42.0
2024-01-30 11:40:29,568 INFO Executing C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe -su -m pip install wheel setuptools
2024-01-30 11:40:30,255 INFO Patching C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python310._pth
2024-01-30 11:40:30,255 INFO Finished installing Python
2024-01-30 11:40:30,537 INFO Using Python: Python 3.10.11, C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe
2024-01-30 11:40:31,162 ERROR 'utf-8' codec can't decode byte 0xe7 in position 29: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 272, in install
    await self._install(cb)
  File "C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 143, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\???\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 639, in get_python_version
    return out.decode(enc).strip()
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 29: invalid continuation byte
2024-01-30 11:40:31,162 ERROR Installation failed

**Comment by Acly** [comment]
It might be related to non-latin characters in the installation path, does your user name contain any?
Does it work if you choose a different installation path for the server?

I thought it worked if I chose the same encoding as the system default, but apparently not. I can probably make it not abort with an error in this case though for next version.

**Comment by MononcGeek** [comment]
Yes it does have non ASCII characters. I will try to change the path to see if it works.

François Ménard
il, lui / he, him
________________________________

**Comment by MononcGeek** [comment]
So I tried it, changed the path and it did fix the issue. Thanks!
