### ISSUE TITLE
"Internal Server Error"

### ISSUE THREAD

**Issue by GloomyHunter** [Acly/krita-ai-diffusion#379]
Hi, so I've installed this plugin and immediately got this error.

2024-02-04 00:03:39,853 ERROR Error: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 560, in _report_errors
    return await coro
  File "C:\Users\xxx\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 174, in _generate
    job_id = await client.enqueue(job)
  File "C:\Users\xxx\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 214, in enqueue
    result = await self._post("prompt", data)
  File "C:\Users\xxx\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 208, in _post
    return await self._requests.post(f"{self.url}/{op}", data)
ai_diffusion.network.NetworkError: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error

**Comment by Phen-Ro** [comment]
If you visit http://127.0.0.1:8188/ in a browser directly, does ComfyUI load?  You'll probably need to share the server.log file under the .logs folder under krita\pykrita\ai_diffusion.

**Comment by GloomyHunter** [comment]
Yeah, ComfyUI seems to load.

server.log is here, especially the error part :

2024-02-04 01:19:55,648 INFO Total VRAM 2048 MB, total RAM 8140 MB
2024-02-04 01:19:55,649 INFO Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
2024-02-04 01:19:55,649 INFO Set vram state to: LOW_VRAM
2024-02-04 01:19:55,649 INFO Device: cuda:0 NVIDIA GeForce GTX 1050 : cudaMallocAsync
2024-02-04 01:19:55,650 INFO VAE dtype: torch.float32
2024-02-04 01:19:56,023 INFO Using pytorch cross attention
2024-02-04 01:20:33,709 INFO 
2024-02-04 01:20:33,709 INFO Import times for custom nodes:
2024-02-04 01:20:33,709 INFO 0.1 seconds: C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui-tooling-nodes
2024-02-04 01:20:33,710 INFO 0.1 seconds: C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-02-04 01:20:33,710 INFO 0.1 seconds: C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-02-04 01:20:33,710 INFO 9.3 seconds: C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-02-04 01:20:33,710 INFO 
2024-02-04 01:20:36,665 INFO 
2024-02-04 01:20:36,666 ERROR [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m

[36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m

[36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m

C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly

  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

Traceback (most recent call last):

  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 246, in <module>

    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))

  File "asyncio\base_events.py", line 649, in run_until_complete

  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 148, in run

    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())

  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\server.py", line 633, in start

    await site.start()

  File "C:\Users\xxxx\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages\aiohttp\web_runner.py", line 119, in start

    self._server = await loop.create_server(

  File "asyncio\base_events.py", line 1519, in create_server

OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): normally only one use per socket address (protocol/network address/port) is allowed

**Comment by GloomyHunter** [comment]
Whoops my bad, I hate getting used to new UIs.

**Comment by Phen-Ro** [comment]
> OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): normally only one use per socket address (protocol/network address/port) is allowed

It sounds like something else is already running on port 8188.   Since you can access ComfyUI through the browser, could it be that you have a custom installation of ComfyUI running as well as another instance trying to be run via this plugin?

If not, maybe these instructions could help identify what's happening: https://stackoverflow.com/a/41836612/1991305

**Comment by GloomyHunter** [comment]
> > OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): normally only one use per socket address (protocol/network address/port) is allowed
> 
> It sounds like something else is already running on port 8188. Since you can access ComfyUI through the browser, could it be that you have a custom installation of ComfyUI running as well as another instance trying to be run via this plugin?
> 
> If not, maybe these instructions could help identify what's happening: https://stackoverflow.com/a/41836612/1991305

Checked it, there is nothing running on port 8188, should I just re-install?

**Comment by Acly** [comment]
I don't think reinstall will help. If there is nothing running it might be a firewall or something that interferes?

You can try a different port: open `ai_diffusion\settings.json` in the plugin folder with a text editor, and change the line with  `""server_arguments"`:
```
"server_arguments": "--port 25605",
```
(you can use any number)

**Comment by ryukra** [comment]
I have this now too, kinda weird, port change didn't help :/
