### ISSUE TITLE
Local server Comfy UI already running

### ISSUE THREAD

**Issue by radialmonster** [Acly/krita-ai-diffusion#390]
I have newly installed this plugin and trying it out.  I am using the local server managed by krita plugin. it worked fine, i exited krita and did other things.  now i am back, and i can not launch the server though, because it seems to be still stuck running from the previous session and it seems it never closed. i have closed krita and opened again and it still has same error.   if i go in browser to 127.0.0.1:8188 i see the comfyui interface.  i dont see comfyui in my task manager to close it.  can there be something added in the plugin ui to connect to the already running server? or to force close the running comfyui.  how do i close the comfyui the plugin previously started and never closed?

thanks

![20240207_093511156_Z6dpJTRAOJ](https://github.com/Acly/krita-ai-diffusion/assets/40280180/c13c52d4-9356-4c3e-99e9-eb4aa2990758)

![20240207_093644746_I9o2fd82D5](https://github.com/Acly/krita-ai-diffusion/assets/40280180/9aa11eb1-355b-46d4-8c58-adf3a3fd9df4)

![20240207_093740532_vVHZz1lofB](https://github.com/Acly/krita-ai-diffusion/assets/40280180/e8d05b0f-536b-43f5-bd09-7701d90582f2)

some of my last log files:
2024-02-07 09:26:58,753 INFO Total VRAM 24576 MB, total RAM 130969 MB
2024-02-07 09:26:58,753 INFO Set vram state to: NORMAL_VRAM
2024-02-07 09:26:58,753 INFO Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2024-02-07 09:26:58,753 INFO VAE dtype: torch.bfloat16
2024-02-07 09:26:58,753 INFO Using pytorch cross attention
2024-02-07 09:27:01,848 INFO 
2024-02-07 09:27:01,849 INFO Import times for custom nodes:
2024-02-07 09:27:01,849 INFO 0.0 seconds: C:\Users\radia\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui-tooling-nodes
2024-02-07 09:27:01,849 INFO 0.0 seconds: C:\Users\radia\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-02-07 09:27:01,849 INFO 0.0 seconds: C:\Users\radia\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-02-07 09:27:01,849 INFO 0.8 seconds: C:\Users\radia\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-02-07 09:27:01,849 INFO 
2024-02-07 09:27:02,440 INFO 
2024-02-07 09:27:02,440 ERROR [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\radia\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
C:\Users\radia\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "C:\Users\radia\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 246, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\Users\radia\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 148, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "C:\Users\radia\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\server.py", line 633, in start
    await site.start()
  File "C:\Users\radia\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
  File "asyncio\base_events.py", line 1519, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): only one usage of each socket address (protocol/network address/port) is normally permitted

**Comment by Acly** [comment]
The process is just called "python" in task manager, you can find and kill it
To connect to already running server, use the second option ("Connec to external server")
I know this is annoying, but difficult to fix because the libraries required aren't available in Krita's python.
See #196 (closing this because duplicate)
