### ISSUE TITLE
getting error message xcrun missing?

### ISSUE THREAD

**Issue by Blendupper** [Acly/krita-ai-diffusion#409]
CLIENT LOG:

2024-02-13 10:19:20,016 INFO Extension initialized, Version: 1.14.0, Python: 3.10.7 (main, Dec  7 2023, 11:44:20) [Clang 13.0.0 (clang-1300.0.29.30)]
2024-02-13 10:22:47,587 INFO Extension initialized, Version: 1.14.0, Python: 3.10.7 (main, Dec  7 2023, 11:44:20) [Clang 13.0.0 (clang-1300.0.29.30)]
2024-02-13 10:22:48,402 INFO Connecting to http://127.0.0.1:8188
2024-02-13 10:24:10,016 INFO Installation started in /Users/graphics/Library/Application Support/krita/pykrita/ai_diffusion/.server
2024-02-13 10:24:10,024 INFO Creating venv in /Users/graphics/Library/Application Support/krita/pykrita/ai_diffusion/.server/venv
2024-02-13 10:24:10,024 INFO Executing /usr/bin/python3 -m venv venv
2024-02-13 10:24:10,266 ERROR Error during installation: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Traceback (most recent call last):
  File "/Users/graphics/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 264, in install
    await self._install(cb)
  File "/Users/graphics/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 131, in _install
    await install_if_missing(python_dir, self._create_venv, cb)
  File "/Users/graphics/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 571, in install_if_missing
    await try_install(path, installer, *args)
  File "/Users/graphics/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 566, in try_install
    raise e
  File "/Users/graphics/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 561, in try_install
    await installer(*args)
  File "/Users/graphics/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 179, in _create_venv
    await _execute_process("Python", venv_cmd, self.path, cb)
  File "/Users/graphics/Library/Application Support/krita/pykrita/ai_diffusion/server.py", line 555, in _execute_process
    raise Exception(f"Error during installation: {errlog}")
Exception: Error during installation: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

2024-02-13 10:24:10,267 ERROR Installation failed

**Comment by Blendupper** [comment]
Finally figured it out after a few days... go to terminal, type in xcode-select --install. and click install..
