### ISSUE TITLE
I get an error when I use the Remove Content feature

### ISSUE THREAD

**Issue by esmail-mkh** [Acly/krita-ai-diffusion#428]
Hello friends, I get an error when I use the Remove Content feature
I just select the part that I want to Remove, but it gives me an error

![Image of error](https://github.com/Acly/krita-ai-diffusion/assets/77193962/32a7790c-0353-4b10-8fef-3eb32013f725)

Please help me if there is a way to fix this error

**Comment by sbonkosky** [comment]
Im also having the same issue.

**Comment by Acly** [comment]
Please check & post logs, they should contain a a trace.

Does this happen with specific canvas resolution or selection size? If possible attach .kra file with active selection, it might help reproduce the issue.

**Comment by esmail-mkh** [comment]
the error of comfyui in terminal is:

`[2024-02-25 11:55] ERROR:root:!!! Exception during processing !!!
[2024-02-25 11:55] ERROR:root:Traceback (most recent call last):
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\nodes.py", line 361, in inpaint
    work_image, work_mask = to_torch(image[i].unsqueeze(0), mask[i].unsqueeze(0))
  File "M:\Apps\AI Image Maker\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes\util.py", line 15, in to_torch
    raise ValueError(
ValueError: Image and mask must be the same size. torch.Size([1184, 888]) != torch.Size([1, 888])`


I tested both with SD 1.5 and SD XL but it didn't work

**Comment by Acly** [comment]
Should be fixed with https://github.com/Acly/comfyui-inpaint-nodes/commit/ed5a8b21bb416d59506fe5e58fc9a36be48f25fb, please update [comfyui-inpaint-nodes](https://github.com/Acly/comfyui-inpaint-nodes) custom node and try again.

**Comment by esmail-mkh** [comment]
fixed, thanks
