### ISSUE TITLE
I am facing a problem where I can't install

### ISSUE THREAD

**Issue by oguchi-kyohei** [Acly/krita-ai-diffusion#442]
Translated from Japanese by DeepL. Sorry if the text is difficult to read.

I tried to call Configure Image Diffusion from Krita and install it, but I am getting the following error.
------------------------------------------------------
2024-02-29 09:18:10,077 ERROR Failed to download https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors: Error transferring https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors - server replied: Not Implemented
Traceback (most recent call last):
  File "C:\krita2024\krita\pykrita\ai_diffusion\network.py", line 212, in download
    async for progress in _try_download(network, url, path):
  File "C:\krita2024\krita\pykrita\ai_diffusion\network.py", line 203, in _try_download
    raise e
ai_diffusion.network.NetworkError: Error transferring https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors - server replied: Not Implemented
------------------------------------------------------
It seems that the error is occurring in the IP-Adapter URL.

Sorry for being a newbie, but I would appreciate your advice.

**Comment by Acly** [comment]
The download is still working for me. Does the link work for you manually in the browser? Maybe it was a temporary issue with the server?

**Comment by oguchi-kyohei** [comment]
Thanks for the reply.
Sorry for the late reply, I was away from home for work.

I tried to install it again and it completed successfully. I guess I just couldn't access it due to bad timing.

I sincerely appreciate you replying to me. I really appreciate it.
