### ISSUE TITLE
Server execution error:Invalid buffer size:68.99GB

### ISSUE THREAD

**Issue by careyzhang66** [Acly/krita-ai-diffusion#445]
When I start to use LCM mod in krita,the process bar up to 12% then stopped.The error is "Server execution error:Invalid buffer size:68.99GB" 

Apple m1 macos 12.6. memory 64GB

**Comment by careyzhang66** [comment]
Prompt executed in 4.41 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
model_type EPS
adm 0
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
clip missing: ['clip_l.text_projection', 'clip_l.logit_scale']
clip unexpected: ['clip_l.transformer.text_model.embeddings.position_ids']
Requested to load SD1ClipModel
Loading 1 new model
Requested to load AutoencoderKL
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/Users/baorui/AI/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/nodes.py", line 313, in encode
    t = vae.encode(pixels[:,:,:,:3])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/sd.py", line 314, in encode
    samples[x:x+batch_number] = self.first_stage_model.encode(pixels_in).to(self.output_device).float()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/ldm/models/autoencoder.py", line 181, in encode
    z = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 531, in forward
    h = self.mid.attn_1(h)
        ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 287, in forward
    h_ = self.optimized_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 206, in normal_attention
    r1 = slice_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 180, in slice_attention
    s1 = torch.bmm(q[:, i:end], k) * scale
         ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Invalid buffer size: 68.99 GB

Prompt executed in 10.92 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
model_type EPS
adm 0
Using split attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using split attention in VAE
clip missing: ['clip_l.text_projection', 'clip_l.logit_scale']
clip unexpected: ['clip_l.transformer.text_model.embeddings.position_ids']
left over keys: dict_keys(['model_ema.decay', 'model_ema.num_updates'])
Requested to load SD1ClipModel
Loading 1 new model
Requested to load AutoencoderKL
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/Users/baorui/AI/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/nodes.py", line 313, in encode
    t = vae.encode(pixels[:,:,:,:3])
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/sd.py", line 314, in encode
    samples[x:x+batch_number] = self.first_stage_model.encode(pixels_in).to(self.output_device).float()
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/ldm/models/autoencoder.py", line 181, in encode
    z = self.encoder(x)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 531, in forward
    h = self.mid.attn_1(h)
        ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 287, in forward
    h_ = self.optimized_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 206, in normal_attention
    r1 = slice_attention(q, k, v)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/baorui/AI/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 180, in slice_attention
    s1 = torch.bmm(q[:, i:end], k) * scale
         ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Invalid buffer size: 68.99 GB

**Comment by DanielAron** [comment]
Same problem here
MabBook Pro M1
Sonoma 14.5

Server execution error: Invalid buffer size: 58.63 GB

**Comment by JeffreyEvey** [comment]
i'm having the same issue: Server execution error: Invalid buffer size: 58.63 GB
