### ISSUE TITLE
The error occurs when I try to use pose in live mode

### ISSUE THREAD

**Issue by livingking5** [Acly/krita-ai-diffusion#463]
I tried to use pose to control the character's movements in live mode, but this prompt appeared. I can't specifically know what this error refers to? But I can use the pose function perfectly in the comfyui I  @linked.https://github.com/Acly 
Can you help me try to solve this problem, thanks for your work
![Screenshot 2024-03-05 at 16 28 36](https://github.com/Acly/krita-ai-diffusion/assets/131408721/d71459d5-b84f-4fde-b144-775d0949ff70)

2024-03-05 15:22:22,782 INFO Optional LoRA model face for SD 1.5 not found (search path: ip-adapter-faceid-plusv2_sd15_lora, ip-adapter-faceid-plus_sd15_lora)
2024-03-05 15:22:22,782 INFO Optional LoRA model face for SD XL not found (search path: ip-adapter-faceid-plusv2_sdxl_lora, ip-adapter-faceid_sdxl_lora)
2024-03-05 15:22:22,856 INFO SD 1.5: supported
2024-03-05 15:22:22,856 INFO SD XL: missing resources IP-Adapter model, Stable Diffusion Checkpoint, Inpaint model, Inpaint model
2024-03-05 16:28:02,217 ERROR Error: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error
Traceback (most recent call last):
  File "C:\Users\yang\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 784, in _report_errors
    return await coro
  File "C:\Users\yang\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 254, in _generate_control_layer
    job.id = await client.enqueue(work, self.queue_front)
  File "C:\Users\yang\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 220, in enqueue
    result = await self._post("prompt", data)
  File "C:\Users\yang\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 214, in _post
    return await self._requests.post(f"{self.url}/{op}", data)
ai_diffusion.network.NetworkError: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error

![Screenshot 2024-03-05 at 16 35 12](https://github.com/Acly/krita-ai-diffusion/assets/131408721/10047750-a00a-48f4-bb2b-9b495d047210)

**Comment by livingking5** [comment]
@Acly Can you help me try to solve this problem, thanks for your work！

**Comment by Acly** [comment]
DWPreprocessor node is missing in ComfyUI. It is part of [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux). Make sure you can find it in ComfyUI, if it's not there try to update/reinstall the custom node.

**Comment by livingking5** [comment]
> DWPreprocessor node is missing in ComfyUI. It is part of [comfyui_controlnet_aux](https://github.com/Fannovel16/comfyui_controlnet_aux). Make sure you can find it in ComfyUI, if it's not there try to update/reinstall the custom node.

Thank you for your help! I successfully installed the comfyui_controlnet_aux you mentioned manually. I found that my previous model should have an internal error. No matter how I reinstall it in comfy manager, it cannot be successful, but I installed it manually successfully. For those who have related problems, I suggest: 1. Try to install manually. 2: Check if you are using a VPN, this often causes link problems with automatic installation.
Finally thank you again, I am happily enjoying krita ai now
<img width="845" alt="Screenshot 2024-03-05 225156" src="https://github.com/Acly/krita-ai-diffusion/assets/131408721/20b1e428-778b-49fc-9513-00dc9ad5ab71">

**Comment by foxqin10000** [comment]
krita5.26  Pose error .Report an error"Server execution error: 'NoneType' object has no attribute 'get_providers'"How to solve, have any friends encountered
![krita_pose_error](https://github.com/user-attachments/assets/41842fa7-49fb-4c8b-87f2-4bdb37c60f3c)
