### ISSUE TITLE
Missing one or more custom nodes

### ISSUE THREAD

**Issue by MartynaKalemba** [Acly/krita-ai-diffusion#514]
I got the following issue:

![image](https://github.com/Acly/krita-ai-diffusion/assets/78158150/7c4c4110-566c-4d2d-8570-24fcf150e83a)

I've already tried to reinstall krita and the plugin, and it didn't helped

Here are the logs: 

`2024-03-19 21:41:46,035 INFO Starting server
2024-03-19 21:41:46,035 INFO 
2024-03-19 21:41:46,035 INFO To see the GUI go to: http://127.0.0.1:8188
2024-03-19 22:48:55,965 INFO Total VRAM 4096 MB, total RAM 16304 MB
2024-03-19 22:48:55,966 INFO Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
2024-03-19 22:48:55,966 INFO Set vram state to: LOW_VRAM
2024-03-19 22:48:55,966 INFO Device: cuda:0 NVIDIA GeForce GTX 1650 : native
2024-03-19 22:48:55,967 INFO VAE dtype: torch.float32
2024-03-19 22:48:56,071 INFO Using pytorch cross attention
2024-03-19 22:48:59,251 INFO ****** User settings have been changed to be stored on the server instead of browser storage. ******
2024-03-19 22:48:59,251 INFO ****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******
2024-03-19 22:49:01,989 INFO Traceback (most recent call last):
2024-03-19 22:49:01,990 INFO File "C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\nodes.py", line 1893, in load_custom_node
2024-03-19 22:49:01,990 INFO module_spec.loader.exec_module(module)
2024-03-19 22:49:01,990 INFO File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-03-19 22:49:01,990 INFO File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-03-19 22:49:01,991 INFO File "C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
2024-03-19 22:49:01,991 INFO from .utils import here, create_node_input_types
2024-03-19 22:49:01,991 INFO File "C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in <module>
2024-03-19 22:49:01,991 INFO import cv2
2024-03-19 22:49:01,992 INFO File "C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\cv2\__init__.py", line 181, in <module>
2024-03-19 22:49:01,992 INFO bootstrap()
2024-03-19 22:49:01,992 INFO File "C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\python\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
2024-03-19 22:49:01,992 INFO native_module = importlib.import_module("cv2")
2024-03-19 22:49:01,993 INFO File "importlib\__init__.py", line 126, in import_module
2024-03-19 22:49:01,993 INFO ImportError: DLL load failed while importing cv2: Nie można odnaleźć określonego modułu.
2024-03-19 22:49:01,994 INFO 
2024-03-19 22:49:01,994 INFO Cannot import C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: DLL load failed while importing cv2: Nie można odnaleźć określonego modułu.
2024-03-19 22:49:02,052 INFO 
2024-03-19 22:49:02,053 INFO Import times for custom nodes:
2024-03-19 22:49:02,054 INFO 0.0 seconds: C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-tooling-nodes
2024-03-19 22:49:02,054 INFO 0.0 seconds: C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-03-19 22:49:02,055 INFO 0.0 seconds: C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-03-19 22:49:02,056 INFO 0.0 seconds: C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-03-19 22:49:02,056 INFO 0.1 seconds (IMPORT FAILED): C:\Users\Szron\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-03-19 22:49:02,057 INFO 
2024-03-19 22:49:02,057 INFO Starting server
2024-03-19 22:49:02,058 INFO 
2024-03-19 22:49:02,058 INFO To see the GUI go to: http://127.0.0.1:8188
`

**Comment by Acly** [comment]
It's an issue with OpenCV module: `DLL load failed while importing cv2`

You might be able to find something when searching, for example https://stackoverflow.com/questions/52349669/dll-load-failed-when-import-cv2-opencv
If you have Windows N (common in EU) this may help.

**Comment by MartynaKalemba** [comment]
Ok, so I installed the Future Media Pack, and also seperately installed the openCV and it helped, thanks
