### ISSUE TITLE
[Help] PermissionError: [WinError 5] 

### ISSUE THREAD

**Issue by alinasama** [Acly/krita-ai-diffusion#515]
Hi, when I tried to install, after a while, I got the error message that said access denied:

2024-03-20 00:14:12,669 INFO Finished installing ComfyUI
2024-03-20 00:14:12,669 INFO Downloading https://github.com/Fannovel16/comfyui_controlnet_aux/archive/c24b2dcb00cd26e4515cd897e14ec21cc5ff3b2d.zip to H:\krita\ai_diffusion\server\.cache\comfyui_controlnet_aux-c24b2dcb00cd26e4515cd897e14ec21cc5ff3b2d.zip
2024-03-20 00:14:15,139 INFO Extracting H:\krita\ai_diffusion\server\.cache\comfyui_controlnet_aux-c24b2dcb00cd26e4515cd897e14ec21cc5ff3b2d.zip to H:\krita\ai_diffusion\server\ComfyUI\custom_nodes
2024-03-20 00:14:17,291 ERROR [WinError 5] 拒绝访问。: 'H:\\krita\\ai_diffusion\\server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux-c24b2dcb00cd26e4515cd897e14ec21cc5ff3b2d' -> 'H:\\krita\\ai_diffusion\\server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux'
Traceback (most recent call last):
  File "C:\Users\47478\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 264, in install
    await self._install(cb)
  File "C:\Users\47478\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 143, in _install
    await install_if_missing(dir, self._install_custom_node, pkg, network, cb)
  File "C:\Users\47478\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 568, in install_if_missing
    await try_install(path, installer, *args)
  File "C:\Users\47478\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 563, in try_install
    raise e
  File "C:\Users\47478\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 558, in try_install
    await installer(*args)
  File "C:\Users\47478\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 217, in _install_custom_node
    rename_extracted_folder(pkg.name, folder, pkg.version)
  File "C:\Users\47478\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 608, in rename_extracted_folder
    extracted_folder.rename(path)
  File "pathlib.py", line 1234, in rename
PermissionError: [WinError 5] 拒绝访问。: 'H:\\krita\\ai_diffusion\\server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux-c24b2dcb00cd26e4515cd897e14ec21cc5ff3b2d' -> 'H:\\krita\\ai_diffusion\\server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux'
2024-03-20 00:14:17,295 ERROR Installation failed

How can I fix this problem?

**Comment by alinasama** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/122513615/f608f6fa-4245-402b-80bb-49d6b85d3848)
this is the screenshot

**Comment by melvixiodf** [comment]
I have the same issue. Anyone know the solution:
![rrr](https://github.com/Acly/krita-ai-diffusion/assets/54470864/22fa74d1-0491-4c8a-b4bc-558125fb6097)

**Comment by Jim1829** [comment]
Getting the same thing.
![image](https://github.com/Acly/krita-ai-diffusion/assets/106937492/376aa2db-54d8-4705-8cbc-cef2b62b9a96)

**Comment by alinasama** [comment]
anyone got it fixed?

**Comment by Acly** [comment]
The error doesn't make a lot of sense to me, but stuff like this can sometimes happen on Windows if explorer is indexing files or there is anti-virus scanning.

I tried to make it more robust by adding a delayed retry in [v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0), maybe it helps

**Comment by PinscherGui** [comment]
This error happened to me too. To solve this i ran the Krita as Administrator and worked.
