### ISSUE TITLE
Error occurred when using Inpaint after updating to version 1.16.0: KeyError: ‘INPAINT_DenoiseToCompositingMask’.

### ISSUE THREAD

**Issue by gmf1982** [Acly/krita-ai-diffusion#534]
Hello, after updating to version 1.16.0, I encountered an error when using local inpainting. This issue occurs regardless of whether I use SD1.5 or XL models, but generating images directly works fine.May I ask what caused it? Thank you!

_Error handling request
Traceback (most recent call last):
  File "D:\AI\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "D:\AI\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\AI\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\AI\ComfyUI\server.py", line 41, in cache_control
    response: web.Response = await handler(request)
  File "D:\AI\ComfyUI\server.py", line 468, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\AI\ComfyUI\execution.py", line 624, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'INPAINT_DenoiseToCompositingMask'_

**Comment by gmf1982** [comment]
Solved, it turns out that I did not update "comfyui-inpaint-node"
