### ISSUE TITLE
'Server execution error' on VAE decode stage 

### ISSUE THREAD

**Issue by attyru** [Acly/krita-ai-diffusion#556]
Hello. SDXL generation very often crashes close to the final (I suspect it happens at the VAE decode stage). 
![image](https://github.com/Acly/krita-ai-diffusion/assets/76990611/fab715d1-ba5a-4bce-9dfe-4a550246d517)

Is there any possibility to try to apply Tiled VAE decode node instead regular? As it is implemented in Fooocus.

**Comment by Acly** [comment]
ComfyUI falls back to tiled VAE automatically if it runs out of memory. There should be something in the output (or server.log) about it:
```
Warning: Ran out of memory when regular VAE decoding, retrying with tiled VAE decoding.
```
It usually works pretty well in my experience, and you don't have to guess/configure at which point tiling becomes necessary.

**Comment by attyru** [comment]
> ComfyUI falls back to tiled VAE automatically if it runs out of memory. There should be something in the output (or server.log) about it:
> 
> ```
> Warning: Ran out of memory when regular VAE decoding, retrying with tiled VAE decoding.
> ```
> 
> It usually works pretty well in my experience, and you don't have to guess/configure at which point tiling becomes necessary.
Yes exactly about such functionality I was talking about, for some reason I was sure that it was Fooocus and not Comfyui🤷‍♂️

here is a sample log with VAE error, it doesn't try to use Tiled VAE, it just aborts:
2024-03-31 16:19:10,816 INFO Requested to load SDXL
2024-03-31 16:19:10,816 INFO Loading 1 new model
2024-03-31 16:19:10,882 INFO loading in lowvram mode 64.0
2024-03-31 16:19:51,458 INFO 0%|          | 0/8 [00:00<?, ?it/s]
 12%|█▎        | 1/8 [00:05<00:35,  5.08s/it]
 25%|██▌       | 2/8 [00:10<00:30,  5.11s/it]
 38%|███▊      | 3/8 [00:15<00:25,  5.09s/it]
 50%|█████     | 4/8 [00:20<00:20,  5.08s/it]
 62%|██████▎   | 5/8 [00:25<00:15,  5.07s/it]
 75%|███████▌  | 6/8 [00:30<00:10,  5.06s/it]
 88%|████████▊ | 7/8 [00:35<00:05,  5.06s/it]
100%|██████████| 8/8 [00:40<00:00,  5.05s/it]
100%|██████████| 8/8 [00:40<00:00,  5.06s/it]
2024-03-31 16:19:51,459 INFO Requested to load AutoencoderKL
2024-03-31 16:19:51,459 INFO Loading 1 new model
2024-03-31 16:19:51,522 INFO loading in lowvram mode 64.0
2024-03-31 16:19:54,643 INFO !!! Exception during processing !!!
2024-03-31 16:19:54,644 INFO Traceback (most recent call last):
2024-03-31 16:19:54,644 INFO File "C:\TOOLS\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
2024-03-31 16:19:54,644 INFO output_data, output_ui = get_output_data(obj, input_data_all)
2024-03-31 16:19:54,644 INFO File "C:\TOOLS\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
2024-03-31 16:19:54,645 INFO return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2024-03-31 16:19:54,645 INFO File "C:\TOOLS\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
2024-03-31 16:19:54,645 INFO results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2024-03-31 16:19:54,645 INFO File "C:\TOOLS\ComfyUI\ComfyUI\nodes.py", line 288, in decode
2024-03-31 16:19:54,645 INFO return (vae.decode(samples["samples"]), )
2024-03-31 16:19:54,646 INFO File "C:\TOOLS\ComfyUI\ComfyUI\comfy\sd.py", line 293, in decode
2024-03-31 16:19:54,646 INFO pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
2024-03-31 16:19:54,646 INFO File "C:\TOOLS\ComfyUI\ComfyUI\comfy\ldm\models\autoencoder.py", line 202, in decode
2024-03-31 16:19:54,646 INFO dec = self.decoder(dec, **decoder_kwargs)
2024-03-31 16:19:54,646 INFO File "C:\TOOLS\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1502, in _call_impl
2024-03-31 16:19:54,647 INFO return forward_call(*args, **kwargs)
2024-03-31 16:19:54,647 INFO File "C:\TOOLS\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 636, in forward
2024-03-31 16:19:54,647 INFO h = self.up[i_level].block[i_block](h, temb, **kwargs)
2024-03-31 16:19:54,647 INFO File "C:\TOOLS\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1502, in _call_impl
2024-03-31 16:19:54,647 INFO return forward_call(*args, **kwargs)
2024-03-31 16:19:54,648 INFO File "C:\TOOLS\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 142, in forward
2024-03-31 16:19:54,648 INFO h = self.swish(h)
2024-03-31 16:19:54,648 INFO File "C:\TOOLS\ComfyUI\python\lib\site-packages\torch\nn\modules\module.py", line 1502, in _call_impl
2024-03-31 16:19:54,648 INFO return forward_call(*args, **kwargs)
2024-03-31 16:19:54,649 INFO File "C:\TOOLS\ComfyUI\python\lib\site-packages\torch\nn\modules\activation.py", line 396, in forward
2024-03-31 16:19:54,649 INFO return F.silu(input, inplace=self.inplace)
2024-03-31 16:19:54,649 INFO File "C:\TOOLS\ComfyUI\python\lib\site-packages\torch\nn\functional.py", line 2058, in silu
2024-03-31 16:19:54,649 INFO return torch._C._nn.silu_(input)
2024-03-31 16:19:54,649 INFO RuntimeError: Could not allocate tensor with 1035993088 bytes. There is not enough GPU video memory available!
2024-03-31 16:19:54,650 INFO 
2024-03-31 16:19:54,650 INFO Prompt executed in 43.82 seconds

Also attached workflow dump and screenshot of error from comfyui:
![image](https://github.com/Acly/krita-ai-diffusion/assets/76990611/a39d918b-b689-4cc7-b518-3b1a4644c9b9)
[debug_workflow_with_VAE_error.json](https://github.com/Acly/krita-ai-diffusion/files/14816041/debug_workflow_with_VAE_error.json)

**Comment by attyru** [comment]
also, please take this opportunity to add the possibility to select the following combinations of sampler and scheduler:
dpmpp_2s_ancestral+ddim_uniform
dpmpp_2s_ancestral+karras
dpm_2+karras
dpmpp_3m_sde+karras
I noticed on civitai a lot of people use them, and me too😊
And, pardon my impertinence, but in case it's possible to add support for "Playground AI's Playground v2.5 1024px" model 😊Workflow attached.
[Playground_v2.5.json](https://github.com/Acly/krita-ai-diffusion/files/14816286/Playground_v2.5.json)

**Comment by Acly** [comment]
You can add your own sampler presets in [v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0)

Regarding tiled VAE, I'm not sure why it doesn't work automatically, but looks like the error is not the correct type to trigger the tile fallback. But this is more of a ComfyUI issue and not something I can easily fix.

Playground: The model itself is not enough, for a good integration it really needs the ecosystem (ControlNet, IP-adapter, Lora, etc.)
