### ISSUE TITLE
Style load error when checkpoint for pre installed styles is not found, either deleted or not downloaded, with show pre installed styles set to disabled

### ISSUE THREAD

**Issue by freecoderwaifu** [Acly/krita-ai-diffusion#564]
![Screenshot 2024-03-31 224143](https://github.com/Acly/krita-ai-diffusion/assets/66507343/caf5c490-5280-466c-a89b-420d48a9e55a)

Steps to reproduce:
Launch comfyui 
Launch Krita
Create new canvas
Go to live mode and press Play with custom style already in dropdown
Error appears

Deleting all the pre installed styles seems to fix it. 

Also switching to a different custom style fixes it.

It also only happens on first load when trying to load a custom style, and doesn't happen on subsequent new canvases created, after switching between other custom styles once per session. 

Log:

```
2024-03-31 22:50:53,478 INFO Extension initialized, Version: 1.16.1, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2024-03-31 22:50:53,478 INFO Loading settings from F:\LIBRARIES\AppData\Roaming\krita\ai_diffusion\settings.json
2024-03-31 22:50:54,586 INFO Connecting to http://127.0.0.1:8188
2024-03-31 22:50:58,461 INFO Found ControlNet model inpaint for SD 1.5: control_v11p_sd15_inpaint_fp16.safetensors
2024-03-31 22:50:58,462 INFO Found ControlNet model scribble for SD 1.5: control_lora_rank128_v11p_sd15_scribble_fp16.safetensors
2024-03-31 22:50:58,462 INFO Found ControlNet model scribble for SD XL: sai_xl_sketch_256lora.safetensors
2024-03-31 22:50:58,462 INFO Found ControlNet model line_art for SD 1.5: control_v11p_sd15_lineart_fp16.safetensors
2024-03-31 22:50:58,462 INFO Found ControlNet model line_art for SD XL: sai_xl_sketch_256lora.safetensors
2024-03-31 22:50:58,462 INFO Found ControlNet model soft_edge for SD 1.5: control_v11p_sd15_softedge_fp16.safetensors
2024-03-31 22:50:58,462 INFO Found ControlNet model canny_edge for SD 1.5: control_v11p_sd15_canny_fp16.safetensors
2024-03-31 22:50:58,463 INFO Found ControlNet model canny_edge for SD XL: sai_xl_canny_256lora.safetensors
2024-03-31 22:50:58,463 INFO Found ControlNet model depth for SD 1.5: control_lora_rank128_v11f1p_sd15_depth_fp16.safetensors
2024-03-31 22:50:58,463 INFO Found ControlNet model depth for SD XL: sai_xl_depth_256lora.safetensors
2024-03-31 22:50:58,463 INFO Found ControlNet model normal for SD 1.5: control_lora_rank128_v11p_sd15_normalbae_fp16.safetensors
2024-03-31 22:50:58,463 INFO Found ControlNet model pose for SD 1.5: control_lora_rank128_v11p_sd15_openpose_fp16.safetensors
2024-03-31 22:50:58,463 INFO Found ControlNet model pose for SD XL: thibaud_xl_openpose_256lora.safetensors
2024-03-31 22:50:58,463 INFO Found ControlNet model segmentation for SD 1.5: control_lora_rank128_v11p_sd15_seg_fp16.safetensors
2024-03-31 22:50:58,464 INFO Found ControlNet model blur for SD 1.5: control_lora_rank128_v11f1e_sd15_tile_fp16.safetensors
2024-03-31 22:50:58,464 INFO Optional ControlNet model blur for SD XL not found (search path: ttplanetsdxlcontrolnet, ttplanet_sdxl_controlnet_tile_realistic)
2024-03-31 22:50:58,464 INFO Found ControlNet model stencil for SD 1.5: control_v1p_sd15_qrcode_monster.safetensors
2024-03-31 22:50:58,464 INFO Found ControlNet model hands for SD 1.5: control_sd15_inpaint_depth_hand_fp16.safetensors
2024-03-31 22:50:58,464 INFO Found ControlNet model hands for SD XL: sai_xl_depth_256lora.safetensors
2024-03-31 22:50:58,464 INFO Found CLIP Vision model ip_adapter for All: SD1.5\model.safetensors
2024-03-31 22:50:58,464 INFO Found IP-Adapter model reference for SD 1.5: ip-adapter_sd15.safetensors
2024-03-31 22:50:58,465 INFO Found IP-Adapter model reference for SD XL: ip-adapter_sdxl_vit-h.safetensors
2024-03-31 22:50:58,465 INFO Found IP-Adapter model face for SD 1.5: ip-adapter-faceid-plusv2_sd15.bin
2024-03-31 22:50:58,465 INFO Found IP-Adapter model face for SD XL: ip-adapter-faceid-plusv2_sdxl.bin
2024-03-31 22:50:58,465 INFO Found Upscale model default for All: 4x_NMKD-Superscale-SP_178000_G.pth
2024-03-31 22:50:58,465 INFO Found Upscale model fast_2x for All: OmniSR_X2_DIV2K.safetensors
2024-03-31 22:50:58,465 INFO Found Upscale model fast_3x for All: OmniSR_X3_DIV2K.safetensors
2024-03-31 22:50:58,465 INFO Found Upscale model fast_4x for All: OmniSR_X4_DIV2K.safetensors
2024-03-31 22:50:58,465 INFO Found Inpaint model default for All: MAT_Places512_G_fp16.safetensors
2024-03-31 22:50:58,466 INFO Found Inpaint model fooocus_head for SD XL: fooocus_inpaint_head.pth
2024-03-31 22:50:58,466 INFO Found Inpaint model fooocus_patch for SD XL: inpaint_v26.fooocus.patch
2024-03-31 22:50:58,477 INFO Found LoRA model lcm for SD 1.5: lcm-lora-sdv1-5.safetensors
2024-03-31 22:50:58,487 INFO Found LoRA model lcm for SD XL: lcm-lora-sdxl.safetensors
2024-03-31 22:50:58,498 INFO Found LoRA model face for SD 1.5: ip-adapter-faceid-plusv2_sd15_lora.safetensors
2024-03-31 22:50:58,509 INFO Found LoRA model face for SD XL: ip-adapter-faceid-plusv2_sdxl_lora.safetensors
2024-03-31 22:51:04,308 INFO SD 1.5: supported
2024-03-31 22:51:04,308 INFO SD XL: supported
2024-03-31 22:51:15,740 ERROR Error: The checkpoint 'realisticVisionV51_v51VAE.safetensors' used by style 'Cinematic Photo' is not available on the server
Traceback (most recent call last):
  File "F:\LIBRARIES\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 836, in _report_errors
    return await coro
  File "F:\LIBRARIES\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 601, in _continue_generating
    new_input = await self._model._generate_live(self._last_input)
  File "F:\LIBRARIES\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 238, in _generate_live
    input = workflow.prepare(
  File "F:\LIBRARIES\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 812, in prepare
    _check_server_has_models(i.models, models, style.name)
  File "F:\LIBRARIES\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 992, in _check_server_has_models
    raise ValueError(
```

**Comment by Acly** [comment]
Fixed in [v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0)
