### ISSUE TITLE
Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error

### ISSUE THREAD

**Issue by qingzhenbiaojie** [Acly/krita-ai-diffusion#574]
hi,acly:
i have a new problem,After updating the 1.16.0 plug-in, other uses are normal, but an error occurs when using the mask tool:
![B55DA2DB7D2520C8D5A926478DD3A0D6](https://github.com/Acly/krita-ai-diffusion/assets/156321695/1cf14aa8-f4b3-41a9-a090-3fdcf8ea2ab8)

and krita client log show me this:
2024-04-02 21:42:54,311 ERROR Error: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error
Traceback (most recent call last):
  File "C:\Users\王权\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 836, in _report_errors
    return await coro
  File "C:\Users\王权\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 601, in _continue_generating
    new_input = await self._model._generate_live(self._last_input)
  File "C:\Users\王权\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 254, in _generate_live
    await self.enqueue_jobs(input, JobKind.live_preview, JobParams(bounds))
  File "C:\Users\王权\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 176, in enqueue_jobs
    await self._enqueue_job(job, input)
  File "C:\Users\王权\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 182, in _enqueue_job
    job.id = await client.enqueue(input, self.queue_front)
  File "C:\Users\王权\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 150, in enqueue
    result = await self._post("prompt", data)
  File "C:\Users\王权\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 143, in _post
    return await self._requests.post(f"{self.url}/{op}", data)
ai_diffusion.network.NetworkError: Error transferring http://127.0.0.1:8188/prompt - server replied: Internal Server Error

 comfy The console displays these：
![BC2DE2BE77288A432539A19C59EF4A84](https://github.com/Acly/krita-ai-diffusion/assets/156321695/275c1e78-d0c5-4cc7-9838-cbff51ba1b79)

how to fix?

**Comment by Acly** [comment]
Likely ComfyUI too old

**Comment by abmmmm** [comment]
> Likely ComfyUI too old
I encountered the same problem. Version 1.15 works fine, but after updating to version 1.61 along with the IP adapter and ComfyUI, it still doesn't work. Is there any solution to this?
[Diagnostics-1712390163.log](https://github.com/Acly/krita-ai-diffusion/files/14892883/Diagnostics-1712390163.log)

**Comment by Acly** [comment]
>Is there any solution to this?

Yes, in this case update comfyui-inpaint-nodes

**Comment by abmmmm** [comment]
> > Is there any solution to this?
> 
> Yes, in this case update comfyui-inpaint-nodes

Perfect! Problem solved, very feel your reply, helped me a lot!
