### ISSUE TITLE
WinError 87

### ISSUE THREAD

**Issue by Lukasooo** [Acly/krita-ai-diffusion#607]
How should I fix this problem, when I click install it shows this

![Snímek obrazovky 2024-04-11 174001](https://github.com/Acly/krita-ai-diffusion/assets/88082089/78eeb443-a1f7-43d3-9fb2-d912424f461d)

**Comment by Acly** [comment]
Please post [client.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files)

**Comment by papousek24** [comment]
I got the same error.
 Message from log: 
```
 2024-04-13 08:14:11,303 INFO Extension initialized, Version: 1.16.1, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2024-04-13 08:14:13,681 INFO Connecting to http://127.0.0.1:8188
2024-04-13 08:16:01,044 INFO Installation started in C:\Users\user\AppData\Roaming\krita\ai_diffusion\server
2024-04-13 08:16:01,059 INFO Downloading https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip to C:\Users\user\AppData\Roaming\krita\ai_diffusion\server\.cache\python-3.10.11-embed-amd64.zip
2024-04-13 08:16:02,142 INFO Extracting C:\Users\user\AppData\Roaming\krita\ai_diffusion\server\.cache\python-3.10.11-embed-amd64.zip to C:\Users\user\AppData\Roaming\krita\ai_diffusion\server\python
2024-04-13 08:16:02,236 INFO Patching C:\Users\user\AppData\Roaming\krita\ai_diffusion\server\python\python310._pth
2024-04-13 08:16:02,236 INFO Downloading https://bootstrap.pypa.io/get-pip.py to C:\Users\user\AppData\Roaming\krita\ai_diffusion\server\python\get-pip.py
2024-04-13 08:16:02,729 INFO Executing C:\Users\user\AppData\Roaming\krita\ai_diffusion\server\python\python.exe C:\Users\user\AppData\Roaming\krita\ai_diffusion\server\python\get-pip.py
2024-04-13 08:16:02,963 ERROR [WinError 87] Parametr není správný
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 264, in install
    await self._install(cb)
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 127, in _install
    await install_if_missing(python_dir, self._install_python, network, cb)
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 564, in install_if_missing
    await try_install(path, installer, *args)
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 559, in try_install
    raise e
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 554, in try_install
    await installer(*args)
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 169, in _install_python
    await _execute_process("Python", [self._python_cmd, get_pip_file], dir, cb)
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 531, in _execute_process
    process = await create_process(cmd[0], *cmd[1:], cwd=cwd, pipe_stderr=True)
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\util.py", line 184, in create_process
    p = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
OSError: [WinError 87] Parametr není správný
2024-04-13 08:16:02,963 ERROR Installation failed
```

**Comment by Acly** [comment]
Which version of windows is this? It's interesting coincidence (?) that both reports use same OS language (czech?), maybe related to non-ansi characters.

Can't reproduce this myself, so I only guess which parameter might be a problem. If you could try out the following it might give some hint:
* Open file [...\krita\pykrita\ai_diffusion\util.py](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/util.py#L185) in a text editor
* Go to line 185 and delete the `env=env, **platform_args` part at the end
* Try again and let me know if you still run into the error

**Comment by papousek24** [comment]
Its fixed. My antivirus blocked it with auto-sandbox:
Name of antivirus: COMODO internet security
![image](https://github.com/Acly/krita-ai-diffusion/assets/166937484/5471c52c-b73a-4fdc-9a6f-accd6c8ee48d)

**Comment by papousek24** [comment]
It was not detected as a virus, but COMODO loves to block almost any application on my device.
