### ISSUE TITLE
Partial inpaint is not possible

### ISSUE THREAD

**Issue by lcwewei** [Acly/krita-ai-diffusion#611]
Krita AI's latest plugin 1.16.1 gives the following error when there is a selection: Error:Errow transferring http://127.0.0.1:8188/prompt - server replied internal Server Errow [url=http://127.0.0.1:8188/prompt.code=

**Comment by Acly** [comment]
Please check/post the [server.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files)

**Comment by carmo2011** [comment]
> Please check/post the [server.log](https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#log-files)

the server.log is empty, the log in comfyui is as below,
the error only happened when i use partial inpaint
![image](https://github.com/Acly/krita-ai-diffusion/assets/87646057/dc070fa1-9dd1-469f-9def-d5166fd73228)

**Comment by carmo2011** [comment]
> > Krita AI 的最新插件 1.16.1 在选择时给出了以下错误： Error：Errow transferring http://127.0.0.1:8188/prompt - server replied internal Server Errow [url=http：//127.0.0.1：8188/prompt.code=
> 
> Less models in comfyui.The comfyui log contains the model filename.

it only happend when i use inpaint.
I didn't see any error tips about model missing.

**Comment by Acly** [comment]
Please update comfyui-inpaint-nodes

**Comment by carmo2011** [comment]
thanks, it's fixed.

**Comment by lcwewei** [comment]
[client.log](https://github.com/Acly/krita-ai-diffusion/files/14973118/client.log)
[server.log](https://github.com/Acly/krita-ai-diffusion/files/14973119/server.log)
I installed Krita AI's latest plugin 1.16.1 and the latest comfyUI inpaint node, and I still get the above error

**Comment by lcwewei** [comment]
server.log is empty

**Comment by lcwewei** [comment]
FETCH DATA from: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/custom-node-list.json
FETCH DATA from: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/extension-node-map.json
got prompt
Error handling request
Traceback (most recent call last):
  File "D:\Program Files\ComfyUI-aki-v1.2\python\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "<enhanced_experience vendors.sentry_sdk.integrations.aiohttp>", line 139, in sentry_app_handle
  File "<enhanced_experience vendors.sentry_sdk._compat>", line 115, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.aiohttp>", line 129, in sentry_app_handle
  File "D:\Program Files\ComfyUI-aki-v1.2\python\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\Program Files\ComfyUI-aki-v1.2\python\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\Program Files\ComfyUI-aki-v1.2\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
  File "<enhanced_experience patches.comfyui.html_resources_patcher>", line 26, in http_resource_injector
  File "D:\Program Files\ComfyUI-aki-v1.2\server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "D:\Program Files\ComfyUI-aki-v1.2\execution.py", line 620, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
KeyError: 'DifferentialDiffusion'

**Comment by lcwewei** [comment]
The autumn leaf starter I use

**Comment by jovly** [comment]
I also use autumn leaf starter, are you Chinese?&nbsp;
你出现的错误提示在秋叶启动器的日志里看到提示缺失模型文件名的。你试试。
In the Autumn Leaf Launcher log you see a prompt for missing model file names. Try it.
&nbsp;


蓝色大雪?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月15日(星期一) 上午10:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Acly/krita-ai-diffusion] Partial inpaint is not possible (Issue #611)














 
The autumn leaf starter I use

**Comment by jovly** [comment]
Are you making a mistake with your hand control layer? This problem was solved when I found the corresponding model file and placed it under model/controlNET. I encountered a problem is the image reference control layer error, model file also has, prompt does not recognize the file, you try, the same? Questions to the author were not answered.&nbsp;


蓝色大雪?
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月15日(星期一) 上午10:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Acly/krita-ai-diffusion] Partial inpaint is not possible (Issue #611)














 
FETCH DATA from: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/custom-node-list.json
 FETCH DATA from: https://gitcode.net/ranting8323/ComfyUI-Manager/-/raw/main/extension-node-map.json
 got prompt
 Error handling request
 Traceback (most recent call last):
 File "D:\Program Files\ComfyUI-aki-v1.2\python\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
 resp = await request_handler(request)
 File "<enhanced_experience vendors.sentry_sdk.integrations.aiohttp&gt;", line 139, in sentry_app_handle
 File "<enhanced_experience vendors.sentry_sdk._compat&gt;", line 115, in reraise
 File "<enhanced_experience vendors.sentry_sdk.integrations.aiohttp&gt;", line 129, in sentry_app_handle
 File "D:\Program Files\ComfyUI-aki-v1.2\python\lib\site-packages\aiohttp\web_app.py", line 504, in handle
 resp = await handler(request)
 File "D:\Program Files\ComfyUI-aki-v1.2\python\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
 return await handler(request)
 File "D:\Program Files\ComfyUI-aki-v1.2\server.py", line 47, in cache_control
 response: web.Response = await handler(request)
 File "<enhanced_experience patches.comfyui.html_resources_patcher&gt;", line 26, in http_resource_injector
 File "D:\Program Files\ComfyUI-aki-v1.2\server.py", line 474, in post_prompt
 valid = execution.validate_prompt(prompt)
 File "D:\Program Files\ComfyUI-aki-v1.2\execution.py", line 620, in validate_prompt
 class = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
 KeyError: 'DifferentialDiffusion'

**Comment by lcwewei** [comment]
Missing that model file? I should put it there

**Comment by Acly** [comment]
> KeyError: 'DifferentialDiffusion'

This node is part of base ComfyUI. Please update

**Comment by lcwewei** [comment]
I don't see the node in my comfyUI, is my version too old

**Comment by lcwewei** [comment]
My version is ec4d89c and the time is 2024.02.20

**Comment by lcwewei** [comment]
Upgrade to the latest version, problem solved, thank you
