### ISSUE TITLE
 Reference Images.Exception: invalid ip-adapter_sd15-image-encoder.bin  

### ISSUE THREAD

**Issue by jovly** [Acly/krita-ai-diffusion#614]
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\AI\ComfyUI-aki-v1.3\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI-aki-v1.3\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI-aki-v1.3\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 501, in load_ipadapter_model
    return (ipadapter_model_loader(ipadapter_file),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 130, in ipadapter_model_loader
    raise Exception("invalid IPAdapter model {}".format(file))
Exception: invalid IPAdapter model D:/AI/sd-webui-aki-v4.7\models/ControlNet\ip-adapter_sd15-image-encoder.bin

ip-adapter_sd15-image-encoder.bin  
This model has, in https://huggingface.co/h94/IP-Adapter/tree/main/models/image_encoder download and renamed. Find a lot of models also error.
This model keeps saying the wrong thing when using the Reference Images layer function. Do you know why?

**Comment by Acly** [comment]
For the record, this file does not belong in the ControlNet folder for ComfyUI.
