### ISSUE TITLE
Click Launch to report an error

### ISSUE THREAD

**Issue by liujvnes** [Acly/krita-ai-diffusion#616]
Hello, I got an error when I clicked Launch. Please help me find out the reason.
![屏幕截图 2024-04-15 005930](https://github.com/Acly/krita-ai-diffusion/assets/25132014/ee08b9f2-ee4f-4155-b115-6cbccf81b034)
2024-04-15 00:57:38,407 INFO Extension initialized, Version: 1.16.1, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2024-04-15 00:57:38,407 INFO Loading settings from C:\Users\liujv\AppData\Roaming\krita\ai_diffusion\settings.json
2024-04-15 00:57:41,651 INFO Starting server with python -su -Xutf8 main.py
2024-04-15 00:57:57,995 WARNING Failed to launch/connect server at startup: Error during server startup: Could not bind on address ('127.0.0.1', 8188): 通常每个套接字地址(协议/网络地址/端口)只允许使用一次。. <a href='https://github.com/Acly/krita-ai-diffusion/wiki/Common-Issues#error-during-server-startup-could-not-bind-on-address-only-one-usage-of-each-socket-address-is-normally-permitted'>More information...</a>
2024-04-15 00:58:27,556 INFO Starting server with python -su -Xutf8 main.py
2024-04-15 00:58:27,741 ERROR Error during server start: AssignProcessToJobObject failed: 5
Traceback (most recent call last):
  File "C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 384, in start
    self._process = await create_process(
  File "C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\util.py", line 190, in create_process
    win32.attach_process_to_job(p.pid)
  File "C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\win32.py", line 80, in attach_process_to_job
    kernel32.AssignProcessToJobObject(job, process)
  File "C:\Users\liujv\AppData\Roaming\krita\pykrita\ai_diffusion\win32.py", line 56, in _kernel32_call
    raise RuntimeError(f"{func} failed: {self.dll.GetLastError()}")
RuntimeError: AssignProcessToJobObject failed: 5

**Comment by Acly** [comment]
Hm I can try to make this optional. But not sure why it fails. Which version of Windows is this?

**Comment by liujvnes** [comment]
> 嗯，我可以尝试将其设置为可选。但不知道为什么会失败。这是哪个版本的 Windows？

版本	Windows 11 家庭版
版本号	24H2
安装日期	‎2024/‎4/‎4
操作系统版本	26100.1
体验	Windows Feature Experience Pack 1000.26100.1.0

**Comment by Acly** [comment]
I'm not sure what causes it. Error message should be gone [v1.17.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.17.0), but it may result in the server process not being shut down in all cases.
