### ISSUE TITLE
IP-Adapter model 'face' for SD XL not found

### ISSUE THREAD

**Issue by carmo2011** [Acly/krita-ai-diffusion#624]
when i use face layer,the error happened.
I already download these face models and the corresponding loras.
anyone can help this?

![image](https://github.com/Acly/krita-ai-diffusion/assets/87646057/b43bd2bf-c4f1-438b-a60a-8782ba9f4db8)

2024-04-17 13:32:35,893 ERROR Error: IP-Adapter model 'face' for SD XL not found
Traceback (most recent call last):
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 836, in _report_errors
    return await coro
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 601, in _continue_generating
    new_input = await self._model._generate_live(self._last_input)
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 254, in _generate_live
    await self.enqueue_jobs(input, JobKind.live_preview, JobParams(bounds))
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 176, in enqueue_jobs
    await self._enqueue_job(job, input)
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 182, in _enqueue_job
    job.id = await client.enqueue(input, self.queue_front)
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 146, in enqueue
    workflow = create_workflow(work, self.models)
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 954, in create
    return refine_region(
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 620, in refine_region
    model = apply_ip_adapter(w, model, cond.control, models)
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\workflow.py", line 285, in apply_ip_adapter
    ip_adapter = w.load_ip_adapter(models[ControlMode.face])
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 144, in __getitem__
    return self._models.resource(self.kind, key, self.version)
  File "C:\Users\11\AppData\Roaming\krita\pykrita\ai_diffusion\client.py", line 108, in resource
    raise Exception(f"{id.name} not found")
Exception: IP-Adapter model 'face' for SD XL not found

**Comment by carmo2011** [comment]
![image](https://github.com/Acly/krita-ai-diffusion/assets/87646057/945ebd75-447f-4142-94c7-637d44565111)

**Comment by Acly** [comment]
It looks for: ip-adapter-faceid-plusv2_sdxl or ip-adapter-faceid_sdxl
so the file should be there. Make sure they are in the right folder (models/ipadapter). Check if they are listed in ComfyUI web interface (IPAdapter Model Loader node)

**Comment by carmo2011** [comment]
thanks, it's fixed. 
Is it possible to list all the modes for each control layer(face,hand,canny, and so on).
another feature request, if the plugin found any model missing, hope it can download automatically from github or huggingface.
Thanks for your great work.

**Comment by Acly** [comment]
There is a script which can list and also download all models for you.
https://github.com/Acly/krita-ai-diffusion/wiki/ComfyUI-Setup#-download-script

The UI already supports automatic download for the managed install option, the idea is that if you have a custom install, probably you manage it already with some other tool (or by hand).
