### ISSUE TITLE
Pose not work, Server execution errot 'NoneType' object has no attribute 'getUnconnectedOutLayersNames'

### ISSUE THREAD

**Issue by tmape** [Acly/krita-ai-diffusion#630]
I tried fresh installed on Windows and finally just v1.15.0 version is work, tested v1.16.1 and v1.17.0 both have same error on 'ControlNet Pose - Generate control layer from current image' function.

![Untitled](https://github.com/Acly/krita-ai-diffusion/assets/83396855/3cf5cb60-b489-4ff1-906d-391aebd7f944)

Client log:
```
['  File "C:\\Users\\username\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\execution.py", line 151, in recursive_execute\n    output_data, output_ui = get_output_data(obj, input_data_all)\n', '  File "C:\\Users\\username\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\execution.py", line 81, in get_output_data\n    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)\n', '  File "C:\\Users\\username\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\execution.py", line 74, in map_node_over_list\n    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))\n', '  File "C:\\Users\\username\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\node_wrappers\\dwpose.py", line 87, in estimate_pose\n    out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution)\n', '  File "C:\\Users\\username\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\utils.py", line 82, in common_annotator_call\n    np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)\n', '  File "C:\\Users\\username\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\node_wrappers\\dwpose.py", line 83, in func\n    pose_img, openpose_dict = model(image, **kwargs)\n', '  File "C:\\Users\\username\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux\\dwpose\\__init__.py", line 199, in __call__\n    poses = self.detect_poses(input_image)\n', '  File "C:\\Users\\username\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux\\dwpose\\__init__.py", line 187, in detect_poses\n    keypoints_info = self.dw_pose_estimation(oriImg.copy())\n', '  File "C:\\Users\\username\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux\\dwpose\\wholebody.py", line 91, in __call__\n    det_result = inference_onnx_yolo_nas(self.det, oriImg, detect_classes=[0], dtype=np.uint8)\n', '  File "C:\\Users\\username\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux\\dwpose\\dw_onnx\\cv_ox_yolo_nas.py", line 50, in inference_detector\n    outNames = session.getUnconnectedOutLayersNames()\n']
2024-04-19 19:11:45,129 ERROR Job dee17344-0a68-46aa-904f-5f13efbfcc31 failed: 'NoneType' object has no attribute 'getUnconnectedOutLayersNames'
```

Server log:
```
2024-04-19 19:11:45,039 INFO Prompt executed in 0.29 seconds
2024-04-19 19:11:55,351 INFO got prompt
2024-04-19 19:11:55,351 INFO model_path is C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/yolo-nas-fp16\yolo_nas_l_fp16.onnx
2024-04-19 19:11:55,351 INFO model_path is C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\yzd-v/DWPose\dw-ll_ucoco_384.onnx
2024-04-19 19:11:55,351 INFO 
2024-04-19 19:11:55,351 INFO DWPose: Using yolo_nas_l_fp16.onnx for bbox detection and dw-ll_ucoco_384.onnx for pose estimation
2024-04-19 19:11:55,412 INFO DWPose: Caching OpenCV DNN module yolo_nas_l_fp16.onnx on cv2.DNN...
2024-04-19 19:11:55,475 INFO [ERROR:0@70.903] global onnx_importer.cpp:1034 cv::dnn::dnn4_v20231225::ONNXImporter::handleNode DNN/ONNX: ERROR during processing node with 2 inputs and 2 outputs: [TopK]:(onnx_node!/post_process/TopK) from domain='ai.onnx'
2024-04-19 19:11:55,505 INFO TopK operators may not work on your OpenCV, try use onnxruntime with CPUExecutionProvider
2024-04-19 19:11:55,505 INFO Failed to load C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/yolo-nas-fp16\yolo_nas_l_fp16.onnx, you can use other models instead
2024-04-19 19:11:55,505 INFO DWPose: Caching OpenCV DNN module dw-ll_ucoco_384.onnx on cv2.DNN...
2024-04-19 19:11:55,697 INFO !!! Exception during processing !!!
2024-04-19 19:11:55,697 INFO Traceback (most recent call last):
2024-04-19 19:11:55,697 INFO File "C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\execution.py", line 151, in recursive_execute
2024-04-19 19:11:55,697 INFO output_data, output_ui = get_output_data(obj, input_data_all)
2024-04-19 19:11:55,697 INFO File "C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\execution.py", line 81, in get_output_data
2024-04-19 19:11:55,697 INFO return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2024-04-19 19:11:55,697 INFO File "C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\execution.py", line 74, in map_node_over_list
2024-04-19 19:11:55,697 INFO results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2024-04-19 19:11:55,697 INFO File "C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 87, in estimate_pose
2024-04-19 19:11:55,697 INFO out = common_annotator_call(func, image, include_hand=detect_hand, include_face=detect_face, include_body=detect_body, image_and_json=True, resolution=resolution)
2024-04-19 19:11:55,697 INFO File "C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 82, in common_annotator_call
2024-04-19 19:11:55,697 INFO np_result = model(np_image, output_type="np", detect_resolution=detect_resolution, **kwargs)
2024-04-19 19:11:55,697 INFO File "C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 83, in func
2024-04-19 19:11:55,697 INFO pose_img, openpose_dict = model(image, **kwargs)
2024-04-19 19:11:55,697 INFO File "C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 199, in __call__
2024-04-19 19:11:55,697 INFO poses = self.detect_poses(input_image)
2024-04-19 19:11:55,697 INFO File "C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 187, in detect_poses
2024-04-19 19:11:55,697 INFO keypoints_info = self.dw_pose_estimation(oriImg.copy())
2024-04-19 19:11:55,697 INFO File "C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\wholebody.py", line 91, in __call__
2024-04-19 19:11:55,698 INFO det_result = inference_onnx_yolo_nas(self.det, oriImg, detect_classes=[0], dtype=np.uint8)
2024-04-19 19:11:55,698 INFO File "C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\dw_onnx\cv_ox_yolo_nas.py", line 50, in inference_detector
2024-04-19 19:11:55,698 INFO outNames = session.getUnconnectedOutLayersNames()
2024-04-19 19:11:55,698 INFO AttributeError: 'NoneType' object has no attribute 'getUnconnectedOutLayersNames'
```

**Comment by Acly** [comment]
It's related to a change in the detection model. I don't know why it's not working for you though.

Maybe  there is an issue with the file, you can try deleting this folder: `C:\Users\username\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16`

If you don't mind making a code change you can also try if it works with the previous one:
* open `...\pykrita\ai_diffusion\workflow.py` in a text editor
* find [line 702](https://github.com/Acly/krita-ai-diffusion/blob/main/ai_diffusion/workflow.py#L702)
* change `yolo_nas_l_fp16.onnx` to `yolox_l.onnx` (I think that's the default one that was used before)

**Comment by tmape** [comment]
>     * change `yolo_nas_l_fp16.onnx` to `yolox_l.onnx` (I think that's the default one that was used before)

Thanks @Acly , following code changes and a Krita restart, the problem was successfully resolved.
