### ISSUE TITLE
Server execution error: 'model.diffusion model.input blocks.0.0.weight'

### ISSUE THREAD

**Issue by Lemad2** [Acly/krita-ai-diffusion#644]
Using this model: https://civitai.com/models/366138?modelVersionId=409143

Server execution error: 'model.diffusion model.input blocks.0.0.weight'

Server.log:

2024-04-21 14:25:20,248 INFO got prompt
2024-04-21 14:25:20,248 INFO !!! Exception during processing !!!
2024-04-21 14:25:20,248 INFO Traceback (most recent call last):
2024-04-21 14:25:20,249 INFO File "C:\Users\pushp\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\execution.py", line 151, in recursive_execute
2024-04-21 14:25:20,249 INFO output_data, output_ui = get_output_data(obj, input_data_all)
2024-04-21 14:25:20,249 INFO File "C:\Users\pushp\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\execution.py", line 81, in get_output_data
2024-04-21 14:25:20,249 INFO return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
2024-04-21 14:25:20,249 INFO File "C:\Users\pushp\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\execution.py", line 74, in map_node_over_list
2024-04-21 14:25:20,249 INFO results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
2024-04-21 14:25:20,249 INFO File "C:\Users\pushp\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\nodes.py", line 516, in load_checkpoint
2024-04-21 14:25:20,250 INFO out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
2024-04-21 14:25:20,250 INFO File "C:\Users\pushp\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\comfy\sd.py", line 507, in load_checkpoint_guess_config
2024-04-21 14:25:20,250 INFO model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.")
2024-04-21 14:25:20,250 INFO File "C:\Users\pushp\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\comfy\model_detection.py", line 194, in model_config_from_unet
2024-04-21 14:25:20,250 INFO unet_config = detect_unet_config(state_dict, unet_key_prefix)
2024-04-21 14:25:20,250 INFO File "C:\Users\pushp\AppData\Roaming\krita\ai_diffusion\server\ComfyUI\comfy\model_detection.py", line 78, in detect_unet_config
2024-04-21 14:25:20,250 INFO model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
2024-04-21 14:25:20,250 INFO KeyError: 'model.diffusion_model.input_blocks.0.0.weight'
2024-04-21 14:25:20,251 INFO 
2024-04-21 14:25:20,251 INFO Prompt executed in 0.02 seconds

Client.log:

2024-04-21 14:25:20,342 ERROR Job e65d0670-3a0c-49ff-bdec-53d29c34680a failed: 'model.diffusion_model.input_blocks.0.0.weight'
['  File "C:\\Users\\pushp\\AppData\\Roaming\\krita\\ai_diffusion\\server\\ComfyUI\\execution.py", line 151, in recursive_execute\n    output_data, output_ui = get_output_data(obj, input_data_all)\n', '  File "C:\\Users\\pushp\\AppData\\Roaming\\krita\\ai_diffusion\\server\\ComfyUI\\execution.py", line 81, in get_output_data\n    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)\n', '  File "C:\\Users\\pushp\\AppData\\Roaming\\krita\\ai_diffusion\\server\\ComfyUI\\execution.py", line 74, in map_node_over_list\n    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))\n', '  File "C:\\Users\\pushp\\AppData\\Roaming\\krita\\ai_diffusion\\server\\ComfyUI\\nodes.py", line 516, in load_checkpoint\n    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))\n', '  File "C:\\Users\\pushp\\AppData\\Roaming\\krita\\ai_diffusion\\server\\ComfyUI\\comfy\\sd.py", line 507, in load_checkpoint_guess_config\n    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.")\n', '  File "C:\\Users\\pushp\\AppData\\Roaming\\krita\\ai_diffusion\\server\\ComfyUI\\comfy\\model_detection.py", line 194, in model_config_from_unet\n    unet_config = detect_unet_config(state_dict, unet_key_prefix)\n', '  File "C:\\Users\\pushp\\AppData\\Roaming\\krita\\ai_diffusion\\server\\ComfyUI\\comfy\\model_detection.py", line 78, in detect_unet_config\n    model_channels = state_dict[\'{}input_blocks.0.0.weight\'.format(key_prefix)].shape[0]\n']

**Comment by Acly** [comment]
This is a Lora, make sure to put it into the models/loras folder and use it in combination with another checkpoint.
