### ISSUE TITLE
ERROR Error: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}} (Error transferring http://127.0.0.1:8188/prompt - server replied: Bad Request)

### ISSUE THREAD

**Issue by qingzhenbiaojie** [Acly/krita-ai-diffusion#671]
Hi Ackley:

  after upgrading 1.17.0, when I use the **COMPOSITION** and **STYLE** functions, I get the error message in the picture, but strangely, the **REFERENCE function works fine**, in which my COMFY has been upgraded to the latest version, and also IPADAPTER NOTE has been upgraded to the latest version, what should I do to solve it! What should I do to solve this problem?
![微信图片_20240429182945](https://github.com/Acly/krita-ai-diffusion/assets/156321695/add94464-822a-4557-b028-fe9ca1379a38)
![微信图片_20240429182952](https://github.com/Acly/krita-ai-diffusion/assets/156321695/a16c44a2-b7e8-4cd0-b253-2a62d5991628)
![微信图片_20240429182959](https://github.com/Acly/krita-ai-diffusion/assets/156321695/27d62bde-9cd2-464d-a615-e21d95e53071)

**The krtita ai diffusion log  as follows :**
ERROR Error: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}} (Error transferring http://127.0.0.1:8188/prompt - server replied: Bad Request)
Traceback (most recent call last):
  File "C:\Users\ji\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 849, in _report_errors
    return await coro
  File "C:\Users\ji\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 610, in _continue_generating
    new_input = await self._model._generate_live(self._last_input)
  File "C:\Users\ji\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 258, in _generate_live
    await self.enqueue_jobs(input, JobKind.live_preview, JobParams(bounds, self.prompt))
  File "C:\Users\ji\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 180, in enqueue_jobs
    await self._enqueue_job(job, input)
  File "C:\Users\ji\AppData\Roaming\krita\pykrita\ai_diffusion\model.py", line 186, in _enqueue_job
    job.id = await client.enqueue(input, self.queue_front)
  File "C:\Users\ji\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 150, in enqueue
    result = await self._post("prompt", data)
  File "C:\Users\ji\AppData\Roaming\krita\pykrita\ai_diffusion\comfy_client.py", line 143, in _post
    return await self._requests.post(f"{self.url}/{op}", data)
ai_diffusion.network.NetworkError: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}} (Error transferring http://127.0.0.1:8188/prompt - server replied: Bad Request)

**comfy log as  follows:**
got prompt
Failed to validate prompt for output 15:
* IPAdapterEmbeds 8:
  - Value not in list: weight_type: 'style transfer' not in ['linear', 'ease in', 'ease out', 'ease in-out', 'reverse in-out', 'weak input', 'weak output', 'weak middle', 'strong middle', 'style transfer (SDXL)']
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

**Comment by qingzhenbiaojie** [comment]
> The error message sounds very much like it comes from an older version of IP-Adapter. Please double-check that you really have the latest.

@Acly  thx  baby ,This is indeed a problem with ipadapter note upgrades, I found that I can't go to upgrade the node in the comfy manager because upgrades aren't up to date here, I have to go to github and download it to not get an error!
![微信截图_20240501131315](https://github.com/Acly/krita-ai-diffusion/assets/156321695/5fb57753-27ee-4067-abed-4070b0ac3ce5)
