### ISSUE TITLE
Inpainting fails with various messages since recent update

### ISSUE THREAD

**Issue by mysticfall** [Acly/krita-ai-diffusion#713]
After updating ComfyUI to the master (`2d41642716344`) from a couple of days old version, the plugin (1.17.2) throws an error when I try to inpaint an area.

If I try multiple times, I get 3 distinct errors. I'm unsure if they are all relevant to the issue, so I'll just list them all below.

The first error is as follows:

> ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/conv.py:456: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:919.)
  return F.conv2d(input, weight, bias, self.stride,

And the process fails with the error below, which immediately follows the previous one:

> !!! Exception during processing!!! 'TimestepEmbedSequential' object has no attribute '1'
Traceback (most recent call last):
  File "/home/mysticfall/workspace/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/nodes.py", line 1378, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/nodes.py", line 1314, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/sample.py", line 37, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 761, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 663, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 650, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 625, in inner_sample
    self.conds = process_conds(self.inner_model, noise, self.conds, device, latent_image, denoise_mask, seed)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 587, in process_conds
    pre_run_control(model, conds[k])
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 439, in pre_run_control
    x['control'].pre_run(model, percent_to_timestep_function)
  File "/home/mysticfall/workspace/ComfyUI/comfy/controlnet.py", line 200, in pre_run
    super().pre_run(model, percent_to_timestep_function)
  File "/home/mysticfall/workspace/ComfyUI/comfy/controlnet.py", line 59, in pre_run
    self.previous_controlnet.pre_run(model, percent_to_timestep_function)
  File "/home/mysticfall/workspace/ComfyUI/comfy/controlnet.py", line 306, in pre_run
    comfy.utils.set_attr_param(self.control_model, k, self.control_weights[k].to(dtype).to(comfy.model_management.get_torch_device()))
  File "/home/mysticfall/workspace/ComfyUI/comfy/utils.py", line 302, in set_attr_param
    return set_attr(obj, attr, torch.nn.Parameter(value, requires_grad=False))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/utils.py", line 296, in set_attr
    obj = getattr(obj, name)
          ^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1709, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'TimestepEmbedSequential' object has no attribute '1'

And if I try multiple times, sometimes I get this error instead:

> !!! Exception during processing!!! mat1 and mat2 shapes cannot be multiplied (308x2048 and 768x320)
Traceback (most recent call last):
  File "/home/mysticfall/workspace/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/nodes.py", line 1378, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/nodes.py", line 1314, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "/home/mysticfall/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/sample.py", line 37, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 761, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 663, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 650, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 629, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 534, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/k_diffusion/sampling.py", line 715, in sample_dpmpp_2m_sde_gpu
    return sample_dpmpp_2m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler, solver_type=solver_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/k_diffusion/sampling.py", line 618, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 272, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 616, in __call__
    return self.predict_noise(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 619, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 258, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 192, in calc_cond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/controlnet.py", line 184, in get_control
    control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint, timesteps=timestep.float(), context=context.to(dtype), y=y)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/cldm/cldm.py", line 305, in forward
    h = module(h, emb, context)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 60, in forward
    return forward_timestep_embed(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 44, in forward_timestep_embed
    x = layer(x, context, transformer_options)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/ldm/modules/attention.py", line 630, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/ldm/modules/attention.py", line 456, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/util.py", line 191, in checkpoint
    return func(*inputs)
           ^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/ldm/modules/attention.py", line 557, in _forward
    n = self.attn2(n, context=context_attn2, value=value_attn2)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/ldm/modules/attention.py", line 399, in forward
    k = self.to_k(context)
        ^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/ops.py", line 52, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: mat1 and mat2 shapes cannot be multiplied (308x2048 and 768x320)

ComfyUI itself is still working without an issue, as was the plugin, until I updated it from a couple of days old version.

**Comment by Acly** [comment]
I updated to latest ComfyUI version (`0bdc2b1`) from today but don't get any errors. Works as usual.

If you share the .kra file or workflow.json I could try that directly to make sure.

**Comment by mysticfall** [comment]
I'm unsure if it's about the .kra file because I can reproduce the issue by attempting to inpaint or use a control net on a newly generated simple image.

I will try to reinstall everything from scratch and see if it fixes the problem and let you know the result.

Thanks for the testing!

**Comment by mysticfall** [comment]
I just reinstalled ComfyUI from scratch, but the problem persists. I put some debug lines in ComfyUI's code and found that it tries to access `TimestepEmbedSequential.input_blocks.1.1.norm.bias` but fails because either `input_blocks` or `input_blocks.1` doesn't have an attribute `1`. Could you guess where the problem might lie?

By the way, does the plugin create any cache or virtual environment?

**Comment by mysticfall** [comment]
This is how the problematic ControlNet's `input_blocks` looks like:

```
  (input_blocks): ModuleList(
    (0): TimestepEmbedSequential(
      (0): Conv2d()
    )
    (1-2): 2 x TimestepEmbedSequential(
      (0): ResBlock(
        (in_layers): Sequential(
          (0): GroupNorm(32, 320, eps=1e-05, affine=True)
          (1): SiLU()
          (2): Conv2d()
        )
        (h_upd): Identity()
        (x_upd): Identity()
        (emb_layers): Sequential(
          (0): SiLU()
          (1): Linear()
        )
        (out_layers): Sequential(
          (0): GroupNorm(32, 320, eps=1e-05, affine=True)
          (1): SiLU()
          (2): Dropout(p=0, inplace=False)
          (3): Conv2d()
        )
        (skip_connection): Identity()
      )
    )
```

So, it's indeed missing `input_blocks.1.1` for some reason. Maybe I have an old or incompatible model? I'll also reinstall the relevant models and see if it makes any difference.

**Comment by mysticfall** [comment]
Finally figured out what was happening. I'll write a brief description of the root cause of my issue for anyone who may encounter it in future because it was quite a tricky problem for me to find out:

I loaded everything on my IDE to debug the code and found out that the plugin was trying to load SD 1.5 control models for some reason.

From the code, it looks like the plugin tries to guess the version of the SD checkpoint by its name as a fallback, in case the server doesn't specify the information.

The problem was, I also changed my default checkpoint at the same time I updated my ComfyUI + Krita AI plugin installation, and the new model doesn't contain "XL" in its name.

Maybe it's a common knowledge that only I missed somehow, but it looks like I have to install such models under a directory named `SDXL` for the server to respond with the correct version information when a client like the Krita plugin queries it for the model list.

Anyway, I'll close the issue since it was my problem. Sorry for the hassle.

**Comment by Acly** [comment]
> Maybe it's a common knowledge that only I missed somehow, but it looks like I have to install such models under a directory named SDXL for the server to respond with the correct version information when a client like the Krita plugin queries it for the model list.

Not usually. The name-based detection is really just a fallback for before the server-based detection was introduced, which was 6 months ago. Maybe I should just remove the fallback to avoid such issues, I didn't immediately think of it from the error messages either.

Question is, why is the server detection not working for you? It's implemented in _comfyui_tooling_nodes_, could be it's just not up-to-date? You can test it via http://127.0.0.1:8188/etn/model_info while Comfy is running, it should classify models correctly regardless of name.

**Comment by mysticfall** [comment]
> Question is, why is the server detection not working for you? It's implemented in _comfyui_tooling_nodes_, could be it's just not up-to-date? You can test it via http://127.0.0.1:8188/etn/model_info while Comfy is running, it should classify models correctly regardless of name.

I opened the page in a browser and got this error:

```json
{"error": "'model.diffusion_model.input_blocks.0.0.weight'"}
```

And my _comfyui_tooling_nodes_ is the latest version (`bcb591c7b998e`).

**Comment by Acly** [comment]
Thanks for checking. It's probably one file in the checkpoints folder causing the error. Either a bad file / not a checkpoint, or one where the detection fails.

I patched tooling nodes to not fail at the first error: https://github.com/Acly/comfyui-tooling-nodes/commit/294d36641d2ddcd3ef5c71c8e4df12b1f1bd1499

If you pull and query again it should tell which files is responsible, and also the rest of them should work with the plugin.

**Comment by mysticfall** [comment]
I just tested it again, as you requested. And the updated version gave me more helpful information indeed:

```json
{"SDXL/Juggernaut_X_RunDiffusion.safetensors": {"base_model": "sdxl", "is_inpaint": false, "is_refiner": false}, "SUPIR/SUPIR-v0Q_fp16.safetensors": {"base_model": "unknown", "error": "Failed to detect base model: 'model.diffusion_model.input_blocks.0.0.weight'"}, "sdsFILM_v40.safetensors": {"base_model": "sdxl", "is_inpaint": false, "is_refiner": false}}
```

I suspect the tooling nodes correctly identified the models all along but failed to report the result because of the SUPIR model I had in the same directory (which was where ComfyUI downloaded it automatically).

At any rate, I'm happy that now I don't have to put my checkpoints in a specifically named subdirectory after the update.

Thanks for the help! :)

**Comment by SyamsQ** [comment]
> I just tested it again, as you requested. And the updated version gave me more helpful information indeed:
> 
> ```json
> {
>   "Juggernaut_X_RunDiffusion.safetensors": {
>     "base_model": "sdxl",
>     "is_inpaint": false,
>     "is_refiner": false
>   },
>   "SUPIR/SUPIR-v0Q_fp16.safetensors": {
>     "base_model": "unknown",
>     "error": "Failed to detect base model: 'model.diffusion_model.input_blocks.0.0.weight'"
>   },
>   "sdsFILM_v40.safetensors": {
>     "base_model": "sdxl",
>     "is_inpaint": false,
>     "is_refiner": false
>   }
> }
> ```
> 
> I suspect the tooling nodes correctly identified the models all along but failed to report the result because of the SUPIR model I had in the same directory (which was where ComfyUI downloaded it automatically).
> 
> At any rate, I'm happy that now I don't have to put my checkpoints in a specifically named subdirectory after the update.
> 
> Thanks for the help! :)

How and where to put Supir for Krita Ai Diffusion correctly?
