### ISSUE TITLE
ERROR Error: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by SalmonRK** [Acly/krita-ai-diffusion#733]
im got these error from my cloud server which using cloud flare
https://kquhxeinnry81g-8188.proxy.runpod.net

2024-05-24 16:15:22,066 ERROR Error: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/Users/salmonrk/Library/Application Support/krita/pykrita/ai_diffusion/connection.py", line 85, in _connect
    self._client = await ComfyClient.connect(url)
  File "/Users/salmonrk/Library/Application Support/krita/pykrita/ai_diffusion/comfy_client.py", line 81, in connect
    missing = [
  File "/Users/salmonrk/Library/Application Support/krita/pykrita/ai_diffusion/comfy_client.py", line 84, in <listcomp>
    if any(node not in nodes for node in package.nodes)
  File "/Users/salmonrk/Library/Application Support/krita/pykrita/ai_diffusion/comfy_client.py", line 84, in <genexpr>
    if any(node not in nodes for node in package.nodes)
TypeError: a bytes-like object is required, not 'str'
2024-05-24 16:15:32,025 INFO Connecting to https://kquhxeinnry81g-8188.proxy.runpod.net
2024-05-24 16:15:33,669 ERROR Could not parse device info b'<!DOCTYPE html>\n<html lang="en">\n    <head>\n        <script src="https://unpkg.com/htmx.org@1.9.10"></script>\n<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/modern-css-reset/dist/reset.min.css" />\n<link rel="preconnect" href="https://fonts.googleapis.com">\n<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>\n<link href="https://fonts.googleapis.com/css2?family=Rubik&family=Ubuntu+Mono&display=swap" rel="stylesheet">\n<link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.4.2/css/all.css">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n\n<style>\n    :root {\n        font-size: 16px;\n    }\n    body {\n        font-family: \'Rubik\', sans-serif;\n        color: #333333;\n        padding: 0;\n    }\n    #stripe {\n      position: fixed;\n      z-index: 1000;\n      display: grid;\n      justify-items: center;\n      align-items: center;\n      top: 0;\n      width: 100%;\n      background: #000;\n    }\n    .one-row {\n      position: relative;\n      width: 1920px;\n      max-width: 94vw;\n      display: grid;\n      align-items: center;\n      justify-items: center;\n      padding: 8px 5px 0 5px;\n    }\n    ul#github-buttons {\n      margin: 0;\n      padding: 0;\n    }\n    ul#github-buttons li {\n      list-style: none;\n      margin-right: 10px;\n      display: inline-block;\n    }\n    .one-col {\n        display: grid;\n        width: 1920px;\n        max-width: 94vw;\n        grid-template-columns: 1fr;\n        justify-items: center;\n        margin: 5px auto;\n        padding: 40px 5px 5px 5px;\n    }\n\n        .Navbar {\n            width: 100%;\n            display: flex;\n            padding: 16px 0;\n            font-family: sans-serif;\n            justify-content: center;\n            position: relative;\n        }\n\n        .Navbar__Link {\n        margin-right: 8px;\n        border-bottom: 2px solid transparent;\n        transition: border 100ms ease-in;\n        }\n        nav .Navbar__Link.active, .Navbar__Link.active:hover {\n            border-bottom: 2px solid rgba(72, 94, 130, 1);\n        }\n\n        nav .Navbar__Link:hover {\n            border-bottom: 2px solid rgba(72, 94, 130, 0.5);\n        }\n\n        .Navbar__Items {\n        display: flex;\n        }\n\n        .Navbar__Items--right {\n        margin-left:auto;\n        }\n\n        .Navbar__Link-toggle {\n        display: none;\n        }\n\n        @media only screen and (max-width: 768px) {\n        .Navbar__Items,\n        .Navbar {\n            flex-direction: column;\n        }\n            \n        .Navbar__Items {\n            display:none;\n        }\n            \n        .Navbar__Items--right {\n            margin-left:0;\n        }\n            \n        .Navbar__ToggleShow {\n            display: flex;\n        }\n        nav .Navbar__Link {\n        border-bottom: none;\n        margin: 2px 0;\n        padding-left: 6px;\n        border-left: 2px solid transparent;\n        }\n        nav .Navbar__Link.active {\n            border-bottom: none;\n            border-left: 2px solid #485e82;\n        }\n        nav .Navbar__Link.active, .Navbar__Link.active:hover {\n            border-bottom: none;\n        }\n\n        nav .Navbar__Link:hover {\n            border-bottom: none;\n        }\n        .Navbar__Link-toggle {\n            align-self: flex-end;\n            display: initial;\n            position: absolute;\n            top:16px;\n            cursor: pointer;\n        } \n    }\n\n\n    img#logo {\n        height: 50px;\n        width: 150px;\n        object-fit: contain;\n    }\n    img.htmx-indicator {\n        display: inline;\n    }\n    div.message {\n        padding: 5px;\n        text-align: center;\n    }\n    .fa-triangle-exclamation {\n      margin: 10px 0;\n      color: #D0342C;\n    }\n    h1,h2 {\n        justify-self: left;\n        font-size: 1.1rem;\n        padding: 0;\n        margin: 10px 0;\n    }\n    .fa-link, .fa-repeat {\n        color: #485e82;\n        margin-right: 3px;\n    }\n    a, a:visited {\n        color: inherit;\n        text-decoration: none;\n    }\n    div#page {\n        width:100%;\n    }\n    div#page h1 {\n        display: flex;\n        align-items: center;\n    }\n    div#page img#spinner-page {\n        padding-left: 5px;\n        height: 1.6rem;\n    }\n    main#service-list {\n        display: grid;\n        width: 100%;\n        grid-template-columns: 1fr;\n        margin: 10px 0 20px 0;\n        border-radius: 5px;\n        overflow: hidden;\n    }\n    main#service-list div.row {\n        display: grid;\n        width: 100%;\n        grid-template-columns: 1fr 2fr 2fr;\n        justify-items: left;\n        align-items: center;\n    }\n    main#service-list div.row:nth-of-type(odd) {\n        background: #F2F2F2;\n    }\n    main#service-list div.row div {\n        padding: 5px;\n    }\n    \n    main#service-list div.heading {\n        font-weight: bold;\n        padding-bottom: 10px;\n        \n    }\n    main#service-list ul {\n        margin: 0;\n        padding: 0;\n    }\n    main#service-list ul li {\n        list-style: none;\n        padding-bottom: 5px;\n    }\n    main#service-list ul li a {\n        border-bottom: 1px solid transparent;\n        transition: border 100ms ease-in;\n    }\n    main#service-list ul li a:hover {\n        border-bottom: 1px solid #485e82;\n    }\n    main#service-list ul li a.icon:hover {\n        border-bottom: 1px solid transparent;\n    }\n    \n    main#process-list {\n        display: grid;\n        width: 100%;\n        grid-template-columns: 1fr;\n        margin: 10px 0 20px 0;\n        border-radius: 5px;\n        overflow: hidden;\n    }\n    main#process-list div.row {\n        display: grid;\n        width: 100%;\n        grid-template-columns: 5fr 3fr 4fr;\n        justify-items: left;\n        align-items: center;\n    }\n    main#process-list div.row:nth-of-type(odd) {\n        background: #F2F2F2;\n    }\n    main#process-list div.row div {\n        padding: 5px;\n    }\n    main#process-list div.row div.controls {\n        width: 100%;\n    }\n    main#process-list div.row div.controls a,\n    main#process-list div.row div.controls a:visited\n     {\n        margin-right: 5px;\n        border-bottom: 1px solid transparent;\n        transition: border 100ms ease-in;\n    }\n    main#process-list div.row div.controls a:hover,\n    main#process-list div.row div.controls a:focus,\n    main#process-list div.row div.controls a:visited\n     {\n        border-bottom: 1px solid #485e82;\n     }\n    \n    \n    main#process-list div.heading {\n        font-weight: bold;\n        padding-bottom: 10px;\n        \n    }\n    main#process-list ul {\n        margin: 0;\n        padding: 0;\n    }\n    main#process-list ul li {\n        list-style: none;\n        padding-bottom: 5px;\n    }\n    main#process-list .statename {\n        display: flex;\n        align-items: center;\n    }\n    main#process-list .statename img.htmx-indicator {\n        padding-left: 5px;\n        height: 20px;\n    }\n    main#terminal {\n        position: relative;\n        box-sizing: border-box;\n        justify-self: left;\n        margin: 5px 0;\n        padding: 10px 10px 20px 10px;\n        width: 100%;\n        height: 500px;\n        min-height: 50vh;\n        max-height: 80vh;\n        background: #000;\n        font-family: \'Ubuntu Mono\', monospace;\n        word-break: break-all;\n        color: #fafafa;\n        line-height: 1.5;\n        overflow-y: scroll;\n        border-radius: 5px;\n    }\n    main#terminal .error {\n        color: #ED4337;\n    }\n    main#terminal .warning {\n        color: #FFBF00;\n    }\n    main#terminal .tail-header {\n        color: #888888;\n    }\n    main#terminal * {\n        overflow-anchor: none;\n    }\n    main#terminal #anchor {\n        overflow-anchor: auto;\n        height: 1px;\n    }\n\n    section#about {\n        justify-self: left;\n        width: 100%;\n        padding-bottom: 25px;\n        border-bottom: 1px solid #eee;\n    }\n    section#about p {\n        margin: 0 0 10px 0;\n    }\n    section#about a, section#about a:visited {\n        font-style: italic;\n    }\n    footer {\n        display: flex;\n        flex-direction: column;\n        text-align: center;\n        align-items: center;\n        justify-self: center;\n        font-family: \'Rubik\', sans-serif;\n        padding-top: 10px;\n    }\n\n    footer #support-dev {\n        margin: 20px 0;\n        max-width: 95vw;\n    }\n    footer #support-dev summary:hover {\n        cursor: pointer;\n    }\n    footer #support-dev ul.unstyled {\n        list-style: none;\n        padding: 0;\n    }\n    footer #support-dev ul.unstyled li {\n        padding: 3px;\n        word-break: break-all;\n    }\n    footer p {\n        text-align: center;\n        margin: 15px 0;\n    }\n    footer ul#social-buttons {\n        list-style: none;\n        text-align: center;\n        margin: 0;\n        padding: 0;\n    }\n    footer ul#social-buttons li {\n        display: inline-block;\n        margin: 0 5px;\n    }\n    footer ul#social-buttons li img {\n        height: 30px;\n        width: 30px;\n    }\n    #login #form-container {\n        display: flex;\n        flex-direction: column;\n        justify-content: center;\n        align-items: center;\n        width: 600px;\n        max-width: 90vw;\n        margin: 0 auto;\n        background-color: white;\n        padding: 20px;\n        border-radius: 10px;\n        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\n        border: 1px solid #ccc;\n    }\n    #login #form-container img {\n      margin-bottom: 20px;\n    }\n    #login form {\n        justify-self: center;\n        width: 100%;\n    }\n    #login .form-group {\n        margin-bottom: 20px;\n    }\n    #login label {\n        display: block;\n        font-weight: bold;\n    }\n    #login input[type="text"],\n    #login input[type="password"] {\n        width: 100%;\n        padding: 10px;\n        border: 1px solid #ccc;\n        border-radius: 5px;\n    }\n    #login button {\n        width: 100%;\n        background-color: #333;\n        color: #fff;\n        border: none;\n        padding: 10px 20px;\n        font-size: 16px;\n        font-weight: bold;\n        cursor: pointer;\n        border-radius: 5px;\n    }\n    \n</style>\n<script async defer src="https://buttons.github.io/buttons.js"></script>\n<title>Login</title>\n    </head>\n    <body>\n        <div class="one-col">\n            <div id="page">\n                <h1><span id="status"></span>\n    <img id="spinner-page" \n        class="htmx-indicator" \n        src="/static/bars.svg"/>\n</h1>\n<main id="login">\n    <div id="form-container">\n      <img\n        id="logo"\n        alt="ai-dock logo"\n        src="https://res.cloudinary.com/dnijlgpto/image/upload/f_auto,q_auto/v1/ai-dock/ic9zjqumz0cnakr6zzey?utm_content=&utm_source="\n    />\n        <form method="post">\n            <div class="form-group">\n                <label for="user">Username</label>\n                <input type="text" id="user" name="user" required>\n            </div>\n            <div class="form-group">\n                <label for="password">Password</label>\n                <input type="password" id="password" name="password" required>\n            </div>\n            <button type="submit">Log In</button>\n        </form>\n    </div>\n</main>\n            </div>\n    </div>\n    <script>\n    function classToggle() {\n        const navs = document.querySelectorAll(\'.Navbar__Items\')\n        \n        navs.forEach(nav => nav.classList.toggle(\'Navbar__ToggleShow\'));\n        }\n\n        document.querySelector(\'.Navbar__Link-toggle\')\n        .addEventListener(\'click\', classToggle);\n</script>\n  </body>\n</html>': byte indices must be integers or slices, not str
2024-05-24 16:15:34,490 ERROR Error: a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/Users/salmonrk/Library/Application Support/krita/pykrita/ai_diffusion/connection.py", line 85, in _connect
    self._client = await ComfyClient.connect(url)
  File "/Users/salmonrk/Library/Application Support/krita/pykrita/ai_diffusion/comfy_client.py", line 81, in connect
    missing = [
  File "/Users/salmonrk/Library/Application Support/krita/pykrita/ai_diffusion/comfy_client.py", line 84, in <listcomp>
    if any(node not in nodes for node in package.nodes)
  File "/Users/salmonrk/Library/Application Support/krita/pykrita/ai_diffusion/comfy_client.py", line 84, in <genexpr>
    if any(node not in nodes for node in package.nodes)
TypeError: a bytes-like object is required, not 'str'

and I'm try using Acly template on runpod 
https://23n3uvhx5pa0he-3001.proxy.runpod.net
and then Im try using Google colab with cloud flare ,it connected smoothly.

Please suggest me , how can I solve these issue?

**Comment by Acly** [comment]
The URL you enter needs to directly connect to ComfyUI instance. It looks like your URL sent some kind of login page instead.

**Comment by SalmonRK** [comment]
Thank you so much, i remove web authen then i use exactly
