### ISSUE TITLE
KeyError: 'ETN_BackgroundRegion'

### ISSUE THREAD

**Issue by megagrump** [Acly/krita-ai-diffusion#780]
![image](https://github.com/Acly/krita-ai-diffusion/assets/31128870/c6f648a8-0134-45db-a776-e11269f29891)

```
got prompt
Error handling request
Traceback (most recent call last):
  File "/home/god/.local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/god/.local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/god/.local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/god/ComfyUI/server.py", line 41, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/god/ComfyUI/server.py", line 53, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/god/ComfyUI/server.py", line 468, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/god/ComfyUI/execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
             ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ETN_BackgroundRegion'
```

**Comment by megagrump** [comment]
I've managed *once* to *not* get this error, but I can't really tell what I'm doing wrong here.

**Comment by megagrump** [comment]
The problem was that `comfyui-tooling-nodes` was outdated on my machine, because I updated the Krita plugin, but not the nodes. It took me a while to figure that out.

Running `git pull origin main` in `custom_nodes/comfyui-tooling-nodes` solved the issue.
