### ISSUE TITLE
unable to install. 

### ISSUE THREAD

**Issue by nntb** [Acly/krita-ai-diffusion#79]
cant do installs on c:

so i have to use W:/Users/USERID/AppData/Roaming/krita/pykrita/ai_diffusion/.server/
plugin is correct. i have a symbolic system link for krita to my w:\ 
when i run install for the core components it gives me a WinError 2

python installs. but it looks like other stuff dosnt. 

2023-11-20 20:39:19,850 INFO Extension initialized, Version: 1.7.0, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2023-11-20 20:39:45,458 INFO Extension initialized, Version: 1.7.0, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2023-11-20 20:39:49,701 INFO Connecting to http://127.0.0.1:8188
2023-11-20 20:43:46,052 INFO Extension initialized, Version: 1.7.0, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2023-11-20 20:43:50,234 INFO Connecting to http://127.0.0.1:8188
2023-11-20 20:45:16,979 INFO Installation started in C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2023-11-20 20:45:16,994 INFO Downloading https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip to C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\python-3.10.11-embed-amd64.zip
2023-11-20 20:45:18,481 INFO Extracting C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\python-3.10.11-embed-amd64.zip to C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python
2023-11-20 20:45:18,668 INFO Patching C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python310._pth
2023-11-20 20:45:18,670 INFO Downloading https://bootstrap.pypa.io/get-pip.py to C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\get-pip.py
2023-11-20 20:45:19,671 INFO Executing C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\get-pip.py
2023-11-20 20:45:24,445 INFO Collecting pip
2023-11-20 20:45:24,761 INFO Downloading pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
2023-11-20 20:45:25,227 INFO Collecting setuptools
2023-11-20 20:45:25,321 INFO Downloading setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
2023-11-20 20:45:25,507 INFO Collecting wheel
2023-11-20 20:45:25,601 INFO Downloading wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
2023-11-20 20:45:25,758 INFO Downloading pip-23.3.1-py3-none-any.whl (2.1 MB)
2023-11-20 20:45:26,477 INFO ---------------------------------------- 2.1/2.1 MB 3.0 MB/s eta 0:00:00
2023-11-20 20:45:26,539 INFO Downloading setuptools-68.2.2-py3-none-any.whl (807 kB)
2023-11-20 20:45:26,601 INFO --------------------------------------- 807.9/807.9 kB 17.0 MB/s eta 0:00:00
2023-11-20 20:45:26,666 INFO Downloading wheel-0.41.3-py3-none-any.whl (65 kB)
2023-11-20 20:45:26,726 INFO ---------------------------------------- 65.8/65.8 kB 3.7 MB/s eta 0:00:00
2023-11-20 20:45:26,883 INFO Installing collected packages: wheel, setuptools, pip
2023-11-20 20:45:39,351 INFO Successfully installed pip-23.3.1 setuptools-68.2.2 wheel-0.41.3
2023-11-20 20:45:40,416 INFO Patching C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python310._pth
2023-11-20 20:45:40,418 INFO Finished installing Python
2023-11-20 20:45:40,757 INFO Using Python: Python 3.10.11, C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe
2023-11-20 20:45:40,759 ERROR [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 165, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 583, in get_python_version
    proc = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-11-20 20:45:40,761 ERROR Installation failed
2023-11-20 20:46:36,264 INFO Installation started in W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python
2023-11-20 20:46:36,266 INFO Downloading https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip to W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\.cache\python-3.10.11-embed-amd64.zip
2023-11-20 20:46:38,010 INFO Extracting W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\.cache\python-3.10.11-embed-amd64.zip to W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python
2023-11-20 20:46:38,182 INFO Patching W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python\python310._pth
2023-11-20 20:46:38,184 INFO Downloading https://bootstrap.pypa.io/get-pip.py to W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python\get-pip.py
2023-11-20 20:46:39,389 INFO Executing W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python\python.exe W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python\get-pip.py
2023-11-20 20:46:43,917 INFO Collecting pip
2023-11-20 20:46:43,918 INFO Using cached pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
2023-11-20 20:46:44,291 INFO Collecting setuptools
2023-11-20 20:46:44,292 INFO Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
2023-11-20 20:46:44,446 INFO Collecting wheel
2023-11-20 20:46:44,508 INFO Using cached wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
2023-11-20 20:46:44,574 INFO Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
2023-11-20 20:46:44,575 INFO Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
2023-11-20 20:46:44,634 INFO Using cached wheel-0.41.3-py3-none-any.whl (65 kB)
2023-11-20 20:46:44,820 INFO Installing collected packages: wheel, setuptools, pip
2023-11-20 20:46:55,540 INFO Successfully installed pip-23.3.1 setuptools-68.2.2 wheel-0.41.3
2023-11-20 20:46:56,476 INFO Patching W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python\python310._pth
2023-11-20 20:46:56,478 INFO Finished installing Python
2023-11-20 20:46:56,914 INFO Using Python: Python 3.10.11, W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python\python.exe
2023-11-20 20:46:56,915 ERROR [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 165, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 583, in get_python_version
    proc = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-11-20 20:46:56,918 ERROR Installation failed
2023-11-20 20:48:02,106 INFO Installation started in W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2023-11-20 20:48:02,446 INFO Using Python: Python 3.10.11, W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe
2023-11-20 20:48:02,447 ERROR [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 165, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 583, in get_python_version
    proc = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-11-20 20:48:02,449 ERROR Installation failed
2023-11-20 20:48:03,861 INFO Installation started in W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2023-11-20 20:48:04,163 INFO Using Python: Python 3.10.11, W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe
2023-11-20 20:48:04,165 ERROR [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 165, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 583, in get_python_version
    proc = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-11-20 20:48:04,168 ERROR Installation failed
2023-11-20 20:48:04,953 INFO Installation started in W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2023-11-20 20:48:05,258 INFO Using Python: Python 3.10.11, W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe
2023-11-20 20:48:05,259 ERROR [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 165, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 583, in get_python_version
    proc = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-11-20 20:48:05,261 ERROR Installation failed
2023-11-20 20:48:52,143 INFO Installation started in W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2023-11-20 20:48:52,145 INFO Downloading https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip to W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\python-3.10.11-embed-amd64.zip
2023-11-20 20:48:53,580 INFO Extracting W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\python-3.10.11-embed-amd64.zip to W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python
2023-11-20 20:48:53,753 INFO Patching W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python310._pth
2023-11-20 20:48:53,755 INFO Downloading https://bootstrap.pypa.io/get-pip.py to W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\get-pip.py
2023-11-20 20:48:54,667 INFO Executing W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\get-pip.py
2023-11-20 20:49:00,070 INFO Collecting pip
2023-11-20 20:49:00,071 INFO Using cached pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
2023-11-20 20:49:00,562 INFO Collecting setuptools
2023-11-20 20:49:00,563 INFO Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
2023-11-20 20:49:00,695 INFO Collecting wheel
2023-11-20 20:49:00,696 INFO Using cached wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
2023-11-20 20:49:00,793 INFO Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
2023-11-20 20:49:00,852 INFO Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
2023-11-20 20:49:00,853 INFO Using cached wheel-0.41.3-py3-none-any.whl (65 kB)
2023-11-20 20:49:01,070 INFO Installing collected packages: wheel, setuptools, pip
2023-11-20 20:49:13,101 INFO Successfully installed pip-23.3.1 setuptools-68.2.2 wheel-0.41.3
2023-11-20 20:49:14,073 INFO Patching W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python310._pth
2023-11-20 20:49:14,075 INFO Finished installing Python
2023-11-20 20:49:14,415 INFO Using Python: Python 3.10.11, W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe
2023-11-20 20:49:14,418 ERROR [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 165, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 583, in get_python_version
    proc = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-11-20 20:49:14,421 ERROR Installation failed
2023-11-20 20:52:34,022 INFO Installation started in W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2023-11-20 20:52:34,353 INFO Using Python: Python 3.10.11, W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe
2023-11-20 20:52:34,354 ERROR [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 165, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 583, in get_python_version
    proc = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-11-20 20:52:34,356 ERROR Installation failed
2023-11-20 20:52:35,456 INFO Installation started in W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2023-11-20 20:52:35,820 INFO Using Python: Python 3.10.11, W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe
2023-11-20 20:52:35,822 ERROR [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 165, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 583, in get_python_version
    proc = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-11-20 20:52:35,824 ERROR Installation failed
2023-11-20 20:54:16,802 INFO Installation started in W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2023-11-20 20:54:16,806 INFO Downloading https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip to W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\python-3.10.11-embed-amd64.zip
2023-11-20 20:54:18,980 INFO Extracting W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\python-3.10.11-embed-amd64.zip to W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python
2023-11-20 20:54:19,157 INFO Patching W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python310._pth
2023-11-20 20:54:19,159 INFO Downloading https://bootstrap.pypa.io/get-pip.py to W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\get-pip.py
2023-11-20 20:54:20,168 INFO Executing W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\get-pip.py
2023-11-20 20:54:25,416 INFO Collecting pip
2023-11-20 20:54:25,417 INFO Using cached pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
2023-11-20 20:54:25,882 INFO Collecting setuptools
2023-11-20 20:54:25,884 INFO Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
2023-11-20 20:54:26,039 INFO Collecting wheel
2023-11-20 20:54:26,040 INFO Using cached wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
2023-11-20 20:54:26,132 INFO Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
2023-11-20 20:54:26,133 INFO Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
2023-11-20 20:54:26,194 INFO Using cached wheel-0.41.3-py3-none-any.whl (65 kB)
2023-11-20 20:54:26,382 INFO Installing collected packages: wheel, setuptools, pip
2023-11-20 20:54:38,383 INFO Successfully installed pip-23.3.1 setuptools-68.2.2 wheel-0.41.3
2023-11-20 20:54:39,477 INFO Patching W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python310._pth
2023-11-20 20:54:39,479 INFO Finished installing Python
2023-11-20 20:54:39,851 INFO Using Python: Python 3.10.11, W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe
2023-11-20 20:54:39,853 ERROR [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 165, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 583, in get_python_version
    proc = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-11-20 20:54:39,856 ERROR Installation failed

**Comment by Acly** [comment]
Not sure what is going wrong yet. My install is behind a symlink too actually, that shouldn't be a problem. But you can choose server install path freely, no need to place it inside the plugin folder. That's just the default location.

The file it can't find here is `W:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\Scripts\pip.exe`. It should have been installed, according to the log. Can you check if it's there?

**Comment by nntb** [comment]
there is no scirpts folder. ill try and locate it>?

**Comment by nntb** [comment]
my pip is in R:\site-package\bin 
how can i redirect the installer to see it there?

**Comment by Acly** [comment]
The installation process installs a stand-alone, independent version of python and then pip. I assume the one in R:\site-pacakge\bin is from your own python install, it won't help. There really should be a Scripts folder...

R:\site-package\bin is also an interesting location. Do you have something set up to redirect python libs that might interfere?

**Comment by nntb** [comment]
looks like pip is not a stand alone and is trying to install into appdata i cant have anything in my app data.

**Comment by nntb** [comment]
2023-11-22 19:58:30,743 INFO Installation started in W:\ai\.server
2023-11-22 19:58:30,745 INFO Downloading https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip to W:\ai\.server\.cache\python-3.10.11-embed-amd64.zip
2023-11-22 19:58:32,699 INFO Extracting W:\ai\.server\.cache\python-3.10.11-embed-amd64.zip to W:\ai\.server\python
2023-11-22 19:58:32,843 INFO Patching W:\ai\.server\python\python310._pth
2023-11-22 19:58:32,845 INFO Downloading https://bootstrap.pypa.io/get-pip.py to W:\ai\.server\python\get-pip.py
2023-11-22 19:58:33,793 INFO Executing W:\ai\.server\python\python.exe W:\ai\.server\python\get-pip.py
2023-11-22 19:58:38,446 INFO Collecting pip
2023-11-22 19:58:38,448 INFO Using cached pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
2023-11-22 19:58:38,853 INFO Collecting setuptools
2023-11-22 19:58:38,854 INFO Using cached setuptools-69.0.2-py3-none-any.whl.metadata (6.3 kB)
2023-11-22 19:58:38,982 INFO Collecting wheel
2023-11-22 19:58:38,983 INFO Using cached wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
2023-11-22 19:58:39,045 INFO Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
2023-11-22 19:58:39,103 INFO Using cached setuptools-69.0.2-py3-none-any.whl (819 kB)
2023-11-22 19:58:39,104 INFO Using cached wheel-0.41.3-py3-none-any.whl (65 kB)
2023-11-22 19:58:39,263 INFO Installing collected packages: wheel, setuptools, pip
2023-11-22 19:58:50,915 INFO Successfully installed pip-23.3.1 setuptools-69.0.2 wheel-0.41.3
2023-11-22 19:58:51,852 INFO Patching W:\ai\.server\python\python310._pth
2023-11-22 19:58:51,854 INFO Finished installing Python
2023-11-22 19:58:52,355 INFO Using Python: Python 3.10.11, W:\ai\.server\python\python.exe
2023-11-22 19:58:52,356 ERROR [WinError 2] The system cannot find the file specified
Traceback (most recent call last):
  File "C:\Users\odo1\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 165, in _install
    log.info(f"Using pip: {await get_python_version(self._pip_cmd)}, {self._pip_cmd}")
  File "C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 583, in get_python_version
    proc = await asyncio.create_subprocess_exec(
  File "asyncio\subprocess.py", line 218, in create_subprocess_exec
  File "asyncio\base_events.py", line 1667, in subprocess_exec
  File "asyncio\windows_events.py", line 394, in _make_subprocess_transport
  File "asyncio\base_subprocess.py", line 36, in __init__
  File "asyncio\windows_events.py", line 890, in _start
  File "asyncio\windows_utils.py", line 153, in __init__
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
2023-11-22 19:58:52,359 ERROR Installation failed

there is no file C:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py
its in w:\Users\USERID\AppData\Roaming\krita\pykrita\ai_diffusion\server.py


where does it install 2023-11-22 19:58:39,263 INFO Installing collected packages: wheel, setuptools, pip
2023-11-22 19:58:50,915 INFO Successfully installed pip-23.3.1 setuptools-69.0.2 wheel-0.41.3

these too? i dont see a pip-23.3.1

**Comment by Acly** [comment]
pip uses a global cache. Maybe you can overwrite it with envrionment variable `PIP_CACHE_DIR`?

Also I'm starting to think it might be easier for your setup to install ComfyUI manually.
