### ISSUE TITLE
upscale failed

### ISSUE THREAD

**Issue by gmf1982** [Acly/krita-ai-diffusion#790]
The following error occurs when using upcale：
!!! Exception during processing!!! box_blur() got an unexpected keyword argument 'separable'
Traceback (most recent call last):
  File "D:\AI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\AI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\AI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\AI\ComfyUI\custom_nodes\comfyui-tooling-nodes\tile.py", line 174, in merge
    layout.merge(image, index, tile)
  File "D:\AI\ComfyUI\custom_nodes\comfyui-tooling-nodes\tile.py", line 94, in merge
    mask = self.mask(coord, blend=True)
  File "D:\AI\ComfyUI\custom_nodes\comfyui-tooling-nodes\tile.py", line 88, in mask
    mask = box_blur(mask, (self.blending, self.blending), separable=True)
TypeError: box_blur() got an unexpected keyword argument 'separable'

**Comment by Acly** [comment]
I'm assuming this is a custom ComfyUI install.

Try updating kornia:
```
pip install --upgrade kornia
```

**Comment by gmf1982** [comment]
> I'm assuming this is a custom ComfyUI install.
> 
> Try updating kornia:
> 
> ```
> pip install --upgrade kornia
> ```

Solved, thank you!
