### ISSUE TITLE
[Win11] Port bind problem

### ISSUE THREAD

**Issue by oytunistrator** [Acly/krita-ai-diffusion#81]
The user cannot access/bind the port: 8188
OS: Win11 Pro x64 

```
2023-11-20 17:14:25,151 ERROR C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:24: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 201, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 105, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\server.py", line 614, in start
    await site.start()
  File "C:\Users\user\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
  File "asyncio\base_events.py", line 1519, in create_server
PermissionError: [Errno 13] error while attempting to bind on address ('127.0.0.1', 8188): an attempt was made to access a socket in a way not permitted by access permissions.
```

**Comment by Acly** [comment]
Could be 2 reasons:
* Either your user really is restricted regarding opening ports. Typically not the case on Win11 but could have been configured that way (also through firewall maybe).
* Something is already running on that port. Either some other application, or there is a left-over ComfyUI process. This can happen if you run Krita, it starts the server, but when it doesn't exit properly (a crash for example) the server isn't stopped. In that case you can look for `python.exe` process that is still running task manager, or fix it via log off and back in, or reboot.

**Comment by oytunistrator** [comment]
I solved the problem by changing the port. The specified ports are blocked on Windows Firewall because they are infected ports. I need to write a bat file and run the server separately. It would be more convenient if an option to change the port was developed.

ComfyUI.bat:
```
@echo off
c:
cd C:\Users\tedar\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI
..\python\python.exe .\main.py --port 9091 --lowvram 
```

Ports other than certain services can only be opened on Windows. Windows Firewall may have prevented risky ports from being opened. For this reason, I run the server separately and then add and use the models. I show the direct port to the Krita application.

Ref: [High-Risk Ports](https://support.huawei.com/enterprise/en/doc/EDOC1100297670)

**Comment by Acly** [comment]
Interesting, I don't think the default port is a high risk port though. Also it only listens on localhost, which usually doesn't trigger the firewall (it's not accessible on any network). Not sure why it's an issue here.

Btw. you can add arguments also in `ai_diffusion/settings.json`, there is a field `server_arguments`. It should pick up the changed port automatically that way and connect.
