### ISSUE TITLE
SSL Error on MacOS

### ISSUE THREAD

**Issue by DrewWalkup** [Acly/krita-ai-diffusion#840]
DESCRIPTION:
When attempting to use a Custom Server running ComfyUI with https using the plugin on Mac, there is an SSL certification verification fail.

INFO:
OS: Mac
Krita version: 5.2.2
Plugin version: 1.18.1 
GPU vendor: Nvidia

CLIENT LOG:
`2024-06-18 23:10:51,886 INFO Loaded 8 sampler presets from /Users/dw/Library/Application Support/krita/pykrita/ai_diffusion/presets/samplers.json
2024-06-18 23:10:51,891 INFO Extension initialized, Version: 1.18.0, Python: 3.10.7 (main, Dec  7 2023, 11:44:20) [Clang 13.0.0 (clang-1300.0.29.30)]
2024-06-18 23:10:51,891 INFO Loading settings from /Users/dw/Library/Application Support/krita/ai_diffusion/settings.json
2024-06-18 23:10:52,596 INFO Connecting to https://comfyui.com:8888
2024-06-18 23:10:52,912 ERROR Error: Could not establish websocket connection at wss://comfyui.com:8888: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997) using Python 3.10.7
Traceback (most recent call last):
  File "/Users/dw/Library/Application Support/krita/pykrita/ai_diffusion/comfy_client.py", line 97, in connect
    async with websockets_client.connect(f"{wsurl}/ws?clientId={client._id}"):
  File "/Users/dw/Library/Application Support/krita/pykrita/ai_diffusion/websockets/src/websockets/legacy/client.py", line 637, in __aenter__
    return await self
  File "/Users/dw/Library/Application Support/krita/pykrita/ai_diffusion/websockets/src/websockets/legacy/client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
  File "/Users/dw/Library/Application Support/krita/pykrita/ai_diffusion/websockets/src/websockets/legacy/client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/Applications/krita.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Applications/krita.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/Applications/krita.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Applications/krita.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Applications/krita.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dw/Library/Application Support/krita/pykrita/ai_diffusion/connection.py", line 85, in _connect
    self._client = await ComfyClient.connect(url)
  File "/Users/dw/Library/Application Support/krita/pykrita/ai_diffusion/comfy_client.py", line 102, in connect
    raise Exception(msg)
Exception: Could not establish websocket connection at wss://comfyui.com:8888: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997) using Python 3.10.7
`

**Comment by chen-zhuohan** [comment]
@DrewWalkup Did it work on your Mac? It seems the problem is still there. I want to know more deeply reason, why mac os need it, why it must be wss instead of ws?
