### ISSUE TITLE
[BUG] ControlNet error

### ISSUE THREAD

**Issue by Rogal80** [Acly/krita-ai-diffusion#844]
Hi,

Recently I just clean folders from pykrita and installed the latest release and after trying to add controlnet to the layer this error appeared:

SORRY for long wall:(

ValueError
Python 3.10.7: C:\Program Files\Krita (x64)\bin\krita.exe
Wed Jun 19 18:20:23 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\region.py in add_control(self=<ai_diffusion.region.RootRegion object>)
  209 
  210     def add_control(self):
  211         self.active_or_root.control.add()
  212 
  213     def is_linked(self, layer: Layer, mode=RegionLink.any):
self = <ai_diffusion.region.RootRegion object>
self.active_or_root = <ai_diffusion.region.RootRegion object>
self.active_or_root.control = <ai_diffusion.control.ControlLayerList object>
self.active_or_root.control.add = <bound method ControlLayerList.add of <ai_diffusion.control.ControlLayerList object>>

 C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py in add(self=<ai_diffusion.control.ControlLayerList object>)
  164     def add(self):
  165         layer = self._model.layers.active
  166         control = ControlLayer(self._model, self._last_mode, layer.id)
  167         control.mode_changed.connect(self._update_last_mode)
  168         layer.removed.connect(lambda: self.remove(control))
control undefined
global ControlLayer = <class 'ai_diffusion.control.ControlLayer'>
self = <ai_diffusion.control.ControlLayerList object>
self._model = <ai_diffusion.model.Model object>
self._last_mode = <ControlMode.scribble: 2>
layer = <ai_diffusion.layer.Layer object>
layer.id = PyQt5.QtCore.QUuid('{25b8c8d5-69b0-4f33-83cb-afc03c19494b}')

 C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py in __init__(self=<ai_diffusion.control.ControlLayer object>, model=<ai_diffusion.model.Model object>, mode=<ControlMode.scribble: 2>, layer_id=PyQt5.QtCore.QUuid('{25b8c8d5-69b0-4f33-83cb-afc03c19494b}'))
   54         self._model = model
   55         self.layer_id = layer_id
   56         self.mode = mode
   57         self._update_is_supported()
   58 
self = <ai_diffusion.control.ControlLayer object>
self.mode = <ControlMode.scribble: 2>
mode = <ControlMode.scribble: 2>

 C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py in set_mode(self=<ai_diffusion.control.ControlLayer object>, mode=<ControlMode.scribble: 2>)
   75             self._update_is_pose_vector()
   76             if not self.use_custom_strength:
   77                 self._set_values_from_preset()
   78 
   79     def set_preset_value(self, value: int):
self = <ai_diffusion.control.ControlLayer object>
self._set_values_from_preset = <bound method ControlLayer._set_values_from_preset of <ai_diffusion.control.ControlLayer object>>

 C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py in _set_values_from_preset(self=<ai_diffusion.control.ControlLayer object>)
   84 
   85     def _set_values_from_preset(self):
   86         params = ControlPresets.instance().interpolate(
   87             self.mode, self._model.sd_version, self.preset_value / self.max_preset_value
   88         )
params undefined
global ControlPresets = <class 'ai_diffusion.control.ControlPresets'>
ControlPresets.instance = <bound method ControlPresets.instance of <class 'ai_diffusion.control.ControlPresets'>>
).interpolate undefined
self = <ai_diffusion.control.ControlLayer object>
self.mode = <ControlMode.scribble: 2>
self._model = <ai_diffusion.model.Model object>
self._model.sd_version = <SDVersion.sd15: 'SD 1.5'>
self.preset_value = 2
self.max_preset_value = 4

 C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py in instance(cls=<class 'ai_diffusion.control.ControlPresets'>)
  210     def instance(cls) -> ControlPresets:
  211         if cls._instance is None:
  212             cls._instance = ControlPresets()
  213         return cls._instance
  214 
cls = <class 'ai_diffusion.control.ControlPresets'>
cls._instance = None
global ControlPresets = <class 'ai_diffusion.control.ControlPresets'>

 C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py in __init__(self=<ai_diffusion.control.ControlPresets object>)
  216         self._path = util.plugin_dir / "presets" / "control.json"
  217         self._user_path = util.user_data_dir / "presets" / "control.json"
  218         self._read()
  219 
  220     def get(self, mode: ControlMode, version: SDVersion):
self = <ai_diffusion.control.ControlPresets object>
self._read = <bound method ControlPresets._read of <ai_diffusion.control.ControlPresets object>>

 C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py in _read(self=<ai_diffusion.control.ControlPresets object>)
  249         _validate_presets(self._path, self._presets)
  250         if self._user_path.exists():
  251             user = self._read_file(self._user_path)
  252             if _validate_presets(self._user_path, user):
  253                 _recursive_update(self._presets, user)
user undefined
self = <ai_diffusion.control.ControlPresets object>
self._read_file = <bound method ControlPresets._read_file of <ai_diffusion.control.ControlPresets object>>
self._user_path = WindowsPath('C:/Users/jerzy/AppData/Roaming/krita/ai_diffusion/presets/control.json')

 C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py in _read_file(self=<ai_diffusion.control.ControlPresets object>, path=WindowsPath('C:/Users/jerzy/AppData/Roaming/krita/ai_diffusion/presets/control.json'))
  260             return json.load(path.open("r"))
  261         except Exception as e:
  262             raise ValueError(f"Failed to read control layer presets file {path}: {e}") from e
  263 
  264 
builtinValueError = <class 'ValueError'>
e undefined
ValueError: Failed to read control layer presets file C:\Users\jerzy\AppData\Roaming\krita\ai_diffusion\presets\control.json: Extra data: line 1 column 3 (char 2)
    __cause__ = JSONDecodeError('Extra data: line 1 column 3 (char 2)')
    __class__ = <class 'ValueError'>
    __context__ = JSONDecodeError('Extra data: line 1 column 3 (char 2)')
    __delattr__ = <method-wrapper '__delattr__' of ValueError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of ValueError object>
    __doc__ = 'Inappropriate argument value (of correct type).'
    __eq__ = <method-wrapper '__eq__' of ValueError object>
    __format__ = <built-in method __format__ of ValueError object>
    __ge__ = <method-wrapper '__ge__' of ValueError object>
    __getattribute__ = <method-wrapper '__getattribute__' of ValueError object>
    __gt__ = <method-wrapper '__gt__' of ValueError object>
    __hash__ = <method-wrapper '__hash__' of ValueError object>
    __init__ = <method-wrapper '__init__' of ValueError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of ValueError object>
    __lt__ = <method-wrapper '__lt__' of ValueError object>
    __ne__ = <method-wrapper '__ne__' of ValueError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of ValueError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of ValueError object>
    __repr__ = <method-wrapper '__repr__' of ValueError object>
    __setattr__ = <method-wrapper '__setattr__' of ValueError object>
    __setstate__ = <built-in method __setstate__ of ValueError object>
    __sizeof__ = <built-in method __sizeof__ of ValueError object>
    __str__ = <method-wrapper '__str__' of ValueError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = True
    __traceback__ = <traceback object>
    args = (r'Failed to read control layer presets file C:\Use...ontrol.json: Extra data: line 1 column 3 (char 2)',)
    with_traceback = <built-in method with_traceback of ValueError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 260, in _read_file
    return json.load(path.open("r"))
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\region.py", line 211, in add_control
    self.active_or_root.control.add()
  File "C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 166, in add
    control = ControlLayer(self._model, self._last_mode, layer.id)
  File "C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 56, in __init__
    self.mode = mode
  File "C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 77, in set_mode
    self._set_values_from_preset()
  File "C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 86, in _set_values_from_preset
    params = ControlPresets.instance().interpolate(
  File "C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 212, in instance
    cls._instance = ControlPresets()
  File "C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 218, in __init__
    self._read()
  File "C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 251, in _read
    user = self._read_file(self._user_path)
  File "C:\Users\jerzy\AppData\Roaming\krita\pykrita\ai_diffusion\control.py", line 262, in _read_file
    raise ValueError(f"Failed to read control layer presets file {path}: {e}") from e
ValueError: Failed to read control layer presets file C:\Users\jerzy\AppData\Roaming\krita\ai_diffusion\presets\control.json: Extra data: line 1 column 3 (char 2)

**Comment by Rogal80** [comment]
ok that was my fault , somehow i just edit json file - sorry to bother
