### ISSUE TITLE
Can't install Local Managed Server

### ISSUE THREAD

**Issue by jeanmartin13** [Acly/krita-ai-diffusion#869]
Hello,

I'm trying to install the plugin (ubuntu 22.04.4) but I have this error message :

`Error during installation: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch from https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=f0deb5d2f932a68ed54625ba140eddbf2af22be978ee19b9b63c986add6425b2:
        Expected sha256 f0deb5d2f932a68ed54625ba140eddbf2af22be978ee19b9b63c986add6425b2
             Got        92d02879b2991343e7fb9b8ff76cb5feeb1bce354f65f9b74f8556e439e954e1`

Here is the full lof file :

`2024-06-24 15:59:24,207 INFO Loaded 10 sampler presets from /home/jean-martin/.local/share/krita/pykrita/ai_diffusion/presets/samplers.json
2024-06-24 15:59:24,237 INFO Extension initialized, Version: 1.19.0, Python: 3.10.7 (main, Nov 29 2023, 15:11:32) [GCC 11.4.0]
2024-06-24 15:59:24,968 INFO Connecting to http://127.0.0.1:8188
2024-06-24 16:01:21,320 INFO Loaded 10 sampler presets from /home/jean-martin/.local/share/krita/pykrita/ai_diffusion/presets/samplers.json
2024-06-24 16:01:21,350 INFO Extension initialized, Version: 1.19.0, Python: 3.10.7 (main, Nov 29 2023, 15:11:32) [GCC 11.4.0]
2024-06-24 16:01:21,350 INFO Loading settings from /home/jean-martin/.local/share/krita/ai_diffusion/settings.json
2024-06-24 16:01:22,036 INFO Connecting to http://127.0.0.1:8188
2024-06-24 16:03:46,219 INFO Installation started in /home/jean-martin/.local/share/krita/ai_diffusion/server
2024-06-24 16:03:46,224 INFO Creating venv in /home/jean-martin/.local/share/krita/ai_diffusion/server/venv
2024-06-24 16:03:46,224 INFO Executing /usr/bin/python3.10 -m venv venv
2024-06-24 16:03:47,775 INFO Using Python: Python 3.10.12, /home/jean-martin/.local/share/krita/ai_diffusion/server/venv/bin/python3
2024-06-24 16:03:48,035 INFO Using pip: pip 22.0.2 from /home/jean-martin/.local/share/krita/ai_diffusion/server/venv/lib/python3.10/site-packages/pip (python 3.10)
2024-06-24 16:03:48,036 INFO Downloading https://github.com/comfyanonymous/ComfyUI/archive/887a6341ed14c9904230cf55a0eabe95cd0218d3.zip to /home/jean-martin/.local/share/krita/ai_diffusion/server/.cache/ComfyUI-887a6341ed14c9904230cf55a0eabe95cd0218d3.zip
2024-06-24 16:03:48,859 INFO Extracting /home/jean-martin/.local/share/krita/ai_diffusion/server/.cache/ComfyUI-887a6341ed14c9904230cf55a0eabe95cd0218d3.zip to /home/jean-martin/.local/share/krita/ai_diffusion/server
2024-06-24 16:03:48,906 INFO Executing /home/jean-martin/.local/share/krita/ai_diffusion/server/venv/bin/python3 -su -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
2024-06-24 16:03:49,135 INFO Looking in indexes: https://download.pytorch.org/whl/cu121
2024-06-24 16:03:49,694 INFO Collecting torch
2024-06-24 16:03:54,895 INFO Using cached https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-linux_x86_64.whl (781.0 MB)
2024-06-24 16:03:55,716 ERROR Error during installation: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch from https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=f0deb5d2f932a68ed54625ba140eddbf2af22be978ee19b9b63c986add6425b2:
        Expected sha256 f0deb5d2f932a68ed54625ba140eddbf2af22be978ee19b9b63c986add6425b2
             Got        92d02879b2991343e7fb9b8ff76cb5feeb1bce354f65f9b74f8556e439e954e1

Traceback (most recent call last):
  File "/home/jean-martin/.local/share/krita/pykrita/ai_diffusion/server.py", line 264, in install
    await self._install(cb)
  File "/home/jean-martin/.local/share/krita/pykrita/ai_diffusion/server.py", line 139, in _install
    await try_install(comfy_dir, self._install_comfy, comfy_dir, network, cb)
  File "/home/jean-martin/.local/share/krita/pykrita/ai_diffusion/server.py", line 559, in try_install
    raise e
  File "/home/jean-martin/.local/share/krita/pykrita/ai_diffusion/server.py", line 554, in try_install
    await installer(*args)
  File "/home/jean-martin/.local/share/krita/pykrita/ai_diffusion/server.py", line 193, in _install_comfy
    await _execute_process("PyTorch", self._pip_install(*torch_args), self.path, cb)
  File "/home/jean-martin/.local/share/krita/pykrita/ai_diffusion/server.py", line 548, in _execute_process
    raise Exception(f"Error during installation: {errlog}")
Exception: Error during installation: ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch from https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-linux_x86_64.whl#sha256=f0deb5d2f932a68ed54625ba140eddbf2af22be978ee19b9b63c986add6425b2:
        Expected sha256 f0deb5d2f932a68ed54625ba140eddbf2af22be978ee19b9b63c986add6425b2
             Got        92d02879b2991343e7fb9b8ff76cb5feeb1bce354f65f9b74f8556e439e954e1

2024-06-24 16:03:55,717 ERROR Installation failed
`

Any idea to solve that issue ?

I have Comfyui installed also, it works. I guess that both local and custom can be installed ?

**Comment by Acly** [comment]
I think this usually happens if the download of a python package somehow fails and leaves a corrupted file. See #819

**Comment by jeanmartin13** [comment]
> I think this usually happens if the download of a python package somehow fails and leaves a corrupted file. See #819

@Acly Thanks 8 After a purge of pip cache it's working again.
