### ISSUE TITLE
Install fails to install Custom Nodes. Log File Included

### ISSUE THREAD

**Issue by RichardGoldbergSchool** [Acly/krita-ai-diffusion#87]
Both the Custom nodes and Required models are not installing. The following is displayed on the UI.

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Richard Goldberg\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux-98bf5b70a98577dcbb1227cdf4fbbf022149a1e1\\src\\controlnet_aux\\normalbae\\nets\\submodules\\efficientnet_repo\\geffnet\\activations\\activations_jit.py' 

This file actually exists in the correct directory. Full install log below.

2023-11-20 14:48:11,157 INFO Extension initialized, Version: 1.7.1, Python: 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
2023-11-20 14:48:12,461 INFO Connecting to http://127.0.0.1:8188
2023-11-20 14:48:43,476 INFO Installation started in C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2023-11-20 14:48:43,485 INFO Downloading https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip to C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\python-3.10.11-embed-amd64.zip
2023-11-20 14:48:43,820 INFO Extracting C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\python-3.10.11-embed-amd64.zip to C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python
2023-11-20 14:48:43,901 INFO Patching C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python310._pth
2023-11-20 14:48:43,902 INFO Downloading https://bootstrap.pypa.io/get-pip.py to C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\get-pip.py
2023-11-20 14:48:44,160 INFO Executing C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\get-pip.py
2023-11-20 14:48:46,340 INFO Collecting pip
2023-11-20 14:48:46,340 INFO Using cached pip-23.3.1-py3-none-any.whl.metadata (3.5 kB)
2023-11-20 14:48:46,496 INFO Collecting setuptools
2023-11-20 14:48:46,496 INFO Using cached setuptools-69.0.0-py3-none-any.whl.metadata (6.3 kB)
2023-11-20 14:48:46,559 INFO Collecting wheel
2023-11-20 14:48:46,559 INFO Using cached wheel-0.41.3-py3-none-any.whl.metadata (2.2 kB)
2023-11-20 14:48:46,560 INFO Using cached pip-23.3.1-py3-none-any.whl (2.1 MB)
2023-11-20 14:48:46,622 INFO Using cached setuptools-69.0.0-py3-none-any.whl (819 kB)
2023-11-20 14:48:46,623 INFO Using cached wheel-0.41.3-py3-none-any.whl (65 kB)
2023-11-20 14:48:46,752 INFO Installing collected packages: wheel, setuptools, pip
2023-11-20 14:48:53,376 INFO Successfully installed pip-23.3.1 setuptools-69.0.0 wheel-0.41.3
2023-11-20 14:48:53,600 INFO Patching C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python310._pth
2023-11-20 14:48:53,601 INFO Finished installing Python
2023-11-20 14:48:53,902 INFO Using Python: Python 3.10.11, C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe
2023-11-20 14:48:54,624 INFO Using pip: pip 23.3.1 from C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages\pip (python 3.10), C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\Scripts\pip.exe
2023-11-20 14:48:54,624 INFO Downloading https://github.com/comfyanonymous/ComfyUI/archive/7114cfec0eefe713340257c85a2b342e98fdcfb2.zip to C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2.zip
2023-11-20 14:48:55,693 INFO Extracting C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2.zip to C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server
2023-11-20 14:48:55,867 INFO Executing C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
2023-11-20 14:48:56,560 INFO Looking in indexes: https://download.pytorch.org/whl/cu121
2023-11-20 14:48:57,134 INFO Collecting torch
2023-11-20 14:48:57,184 INFO Using cached https://download.pytorch.org/whl/cu121/torch-2.1.1%2Bcu121-cp310-cp310-win_amd64.whl (2473.9 MB)
2023-11-20 14:49:05,376 INFO Collecting torchvision
2023-11-20 14:49:05,440 INFO Using cached https://download.pytorch.org/whl/cu121/torchvision-0.16.1%2Bcu121-cp310-cp310-win_amd64.whl (5.6 MB)
2023-11-20 14:49:05,872 INFO Collecting torchaudio
2023-11-20 14:49:05,936 INFO Using cached https://download.pytorch.org/whl/cu121/torchaudio-2.1.1%2Bcu121-cp310-cp310-win_amd64.whl (4.0 MB)
2023-11-20 14:49:06,319 INFO Collecting filelock (from torch)
2023-11-20 14:49:06,372 INFO Using cached https://download.pytorch.org/whl/filelock-3.9.0-py3-none-any.whl (9.7 kB)
2023-11-20 14:49:06,464 INFO Collecting typing-extensions (from torch)
2023-11-20 14:49:06,464 INFO Using cached https://download.pytorch.org/whl/typing_extensions-4.4.0-py3-none-any.whl (26 kB)
2023-11-20 14:49:06,840 INFO Collecting sympy (from torch)
2023-11-20 14:49:06,906 INFO Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
2023-11-20 14:49:07,280 INFO Collecting networkx (from torch)
2023-11-20 14:49:07,343 INFO Using cached https://download.pytorch.org/whl/networkx-3.0-py3-none-any.whl (2.0 MB)
2023-11-20 14:49:07,728 INFO Collecting jinja2 (from torch)
2023-11-20 14:49:07,778 INFO Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
2023-11-20 14:49:08,128 INFO Collecting fsspec (from torch)
2023-11-20 14:49:08,191 INFO Using cached https://download.pytorch.org/whl/fsspec-2023.4.0-py3-none-any.whl (153 kB)
2023-11-20 14:49:08,496 INFO Collecting numpy (from torchvision)
2023-11-20 14:49:08,592 INFO Using cached https://download.pytorch.org/whl/numpy-1.24.1-cp310-cp310-win_amd64.whl (14.8 MB)
2023-11-20 14:49:08,966 INFO Collecting requests (from torchvision)
2023-11-20 14:49:09,028 INFO Using cached https://download.pytorch.org/whl/requests-2.28.1-py3-none-any.whl (62 kB)
2023-11-20 14:49:09,376 INFO Collecting pillow!=8.3.*,>=5.3.0 (from torchvision)
2023-11-20 14:49:09,439 INFO Using cached https://download.pytorch.org/whl/Pillow-9.3.0-cp310-cp310-win_amd64.whl (2.5 MB)
2023-11-20 14:49:09,466 INFO Requirement already satisfied: MarkupSafe>=2.0 in c:\users\richard goldberg\appdata\roaming\python\python310\site-packages (from jinja2->torch) (2.1.1)
2023-11-20 14:49:09,821 INFO Collecting charset-normalizer<3,>=2 (from requests->torchvision)
2023-11-20 14:49:09,872 INFO Using cached https://download.pytorch.org/whl/charset_normalizer-2.1.1-py3-none-any.whl (39 kB)
2023-11-20 14:49:10,186 INFO Collecting idna<4,>=2.5 (from requests->torchvision)
2023-11-20 14:49:10,250 INFO Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
2023-11-20 14:49:10,592 INFO Collecting urllib3<1.27,>=1.21.1 (from requests->torchvision)
2023-11-20 14:49:10,652 INFO Using cached https://download.pytorch.org/whl/urllib3-1.26.13-py2.py3-none-any.whl (140 kB)
2023-11-20 14:49:10,965 INFO Collecting certifi>=2017.4.17 (from requests->torchvision)
2023-11-20 14:49:11,038 INFO Using cached https://download.pytorch.org/whl/certifi-2022.12.7-py3-none-any.whl (155 kB)
2023-11-20 14:49:11,373 INFO Collecting mpmath>=0.19 (from sympy->torch)
2023-11-20 14:49:11,434 INFO Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
2023-11-20 14:49:11,689 INFO Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, jinja2, idna, fsspec, filelock, charset-normalizer, certifi, torch, requests, torchvision, torchaudio
2023-11-20 14:50:28,576 INFO Successfully installed certifi-2022.12.7 charset-normalizer-2.1.1 filelock-3.9.0 fsspec-2023.4.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.0 numpy-1.24.1 pillow-9.3.0 requests-2.28.1 sympy-1.12 torch-2.1.1+cu121 torchaudio-2.1.1+cu121 torchvision-0.16.1+cu121 typing-extensions-4.4.0 urllib3-1.26.13
2023-11-20 14:50:28,888 INFO Executing C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\python.exe -m pip install -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt
2023-11-20 14:50:29,616 INFO Requirement already satisfied: torch in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 1)) (2.1.1+cu121)
2023-11-20 14:50:29,712 INFO Collecting torchsde (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 2))
2023-11-20 14:50:29,713 INFO Using cached torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)
2023-11-20 14:50:29,763 INFO Collecting einops (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 3))
2023-11-20 14:50:29,763 INFO Using cached einops-0.7.0-py3-none-any.whl.metadata (13 kB)
2023-11-20 14:50:29,824 INFO Collecting transformers>=4.25.1 (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 4))
2023-11-20 14:50:29,824 INFO Using cached transformers-4.35.2-py3-none-any.whl.metadata (123 kB)
2023-11-20 14:50:29,887 INFO Collecting safetensors>=0.3.0 (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 5))
2023-11-20 14:50:29,887 INFO Using cached safetensors-0.4.0-cp310-none-win_amd64.whl.metadata (3.8 kB)
2023-11-20 14:50:29,888 INFO Requirement already satisfied: aiohttp in c:\users\richard goldberg\appdata\roaming\python\python310\site-packages (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 6)) (3.8.1)
2023-11-20 14:50:29,949 INFO Collecting accelerate (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 7))
2023-11-20 14:50:29,950 INFO Using cached accelerate-0.24.1-py3-none-any.whl.metadata (18 kB)
2023-11-20 14:50:30,014 INFO Collecting pyyaml (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 8))
2023-11-20 14:50:30,015 INFO Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl.metadata (2.1 kB)
2023-11-20 14:50:30,015 INFO Requirement already satisfied: Pillow in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 9)) (9.3.0)
2023-11-20 14:50:30,077 INFO Collecting scipy (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 10))
2023-11-20 14:50:30,077 INFO Using cached scipy-1.11.4-cp310-cp310-win_amd64.whl.metadata (60 kB)
2023-11-20 14:50:30,172 INFO Collecting tqdm (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 11))
2023-11-20 14:50:30,173 INFO Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
2023-11-20 14:50:30,266 INFO Collecting psutil (from -r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 12))
2023-11-20 14:50:30,266 INFO Using cached psutil-5.9.6-cp37-abi3-win_amd64.whl.metadata (22 kB)
2023-11-20 14:50:30,325 INFO Requirement already satisfied: filelock in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from torch->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 1)) (3.9.0)
2023-11-20 14:50:30,326 INFO Requirement already satisfied: typing-extensions in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from torch->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 1)) (4.4.0)
2023-11-20 14:50:30,326 INFO Requirement already satisfied: sympy in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from torch->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 1)) (1.12)
2023-11-20 14:50:30,326 INFO Requirement already satisfied: networkx in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from torch->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 1)) (3.0)
2023-11-20 14:50:30,327 INFO Requirement already satisfied: jinja2 in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from torch->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 1)) (3.1.2)
2023-11-20 14:50:30,327 INFO Requirement already satisfied: fsspec in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from torch->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 1)) (2023.4.0)
2023-11-20 14:50:30,327 INFO Requirement already satisfied: numpy>=1.19 in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from torchsde->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 2)) (1.24.1)
2023-11-20 14:50:30,361 INFO Collecting trampoline>=0.1.2 (from torchsde->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 2))
2023-11-20 14:50:30,362 INFO Using cached trampoline-0.1.2-py3-none-any.whl (5.2 kB)
2023-11-20 14:50:30,672 INFO Collecting huggingface-hub<1.0,>=0.16.4 (from transformers>=4.25.1->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 4))
2023-11-20 14:50:30,672 INFO Using cached huggingface_hub-0.19.4-py3-none-any.whl.metadata (14 kB)
2023-11-20 14:50:30,736 INFO Collecting packaging>=20.0 (from transformers>=4.25.1->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 4))
2023-11-20 14:50:30,737 INFO Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
2023-11-20 14:50:30,985 INFO Collecting regex!=2019.12.17 (from transformers>=4.25.1->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 4))
2023-11-20 14:50:31,046 INFO Using cached regex-2023.10.3-cp310-cp310-win_amd64.whl.metadata (41 kB)
2023-11-20 14:50:31,046 INFO Requirement already satisfied: requests in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from transformers>=4.25.1->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 4)) (2.28.1)
2023-11-20 14:50:31,138 INFO Collecting tokenizers<0.19,>=0.14 (from transformers>=4.25.1->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 4))
2023-11-20 14:50:31,139 INFO Using cached tokenizers-0.15.0-cp310-none-win_amd64.whl.metadata (6.8 kB)
2023-11-20 14:50:31,230 INFO Collecting attrs>=17.3.0 (from aiohttp->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 6))
2023-11-20 14:50:31,231 INFO Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
2023-11-20 14:50:31,294 INFO Requirement already satisfied: charset-normalizer<3.0,>=2.0 in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from aiohttp->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 6)) (2.1.1)
2023-11-20 14:50:31,294 INFO Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\richard goldberg\appdata\roaming\python\python310\site-packages (from aiohttp->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 6)) (6.0.2)
2023-11-20 14:50:31,295 INFO Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\richard goldberg\appdata\roaming\python\python310\site-packages (from aiohttp->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 6)) (4.0.2)
2023-11-20 14:50:31,295 INFO Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\richard goldberg\appdata\roaming\python\python310\site-packages (from aiohttp->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 6)) (1.7.2)
2023-11-20 14:50:31,295 INFO Requirement already satisfied: frozenlist>=1.1.1 in c:\users\richard goldberg\appdata\roaming\python\python310\site-packages (from aiohttp->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 6)) (1.3.0)
2023-11-20 14:50:31,296 INFO Requirement already satisfied: aiosignal>=1.1.2 in c:\users\richard goldberg\appdata\roaming\python\python310\site-packages (from aiohttp->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 6)) (1.2.0)
2023-11-20 14:50:31,325 INFO Requirement already satisfied: colorama in c:\users\richard goldberg\appdata\roaming\python\python310\site-packages (from tqdm->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 11)) (0.4.4)
2023-11-20 14:50:31,482 INFO Collecting fsspec (from torch->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 1))
2023-11-20 14:50:31,482 INFO Using cached fsspec-2023.10.0-py3-none-any.whl.metadata (6.8 kB)
2023-11-20 14:50:31,575 INFO Requirement already satisfied: idna>=2.0 in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 6)) (3.4)
2023-11-20 14:50:31,575 INFO Requirement already satisfied: MarkupSafe>=2.0 in c:\users\richard goldberg\appdata\roaming\python\python310\site-packages (from jinja2->torch->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 1)) (2.1.1)
2023-11-20 14:50:31,640 INFO Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from requests->transformers>=4.25.1->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 4)) (1.26.13)
2023-11-20 14:50:31,640 INFO Requirement already satisfied: certifi>=2017.4.17 in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from requests->transformers>=4.25.1->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 4)) (2022.12.7)
2023-11-20 14:50:31,641 INFO Requirement already satisfied: mpmath>=0.19 in c:\users\richard goldberg\appdata\roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages (from sympy->torch->-r C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI-7114cfec0eefe713340257c85a2b342e98fdcfb2\requirements.txt (line 1)) (1.3.0)
2023-11-20 14:50:31,671 INFO Using cached torchsde-0.2.6-py3-none-any.whl (61 kB)
2023-11-20 14:50:31,671 INFO Using cached einops-0.7.0-py3-none-any.whl (44 kB)
2023-11-20 14:50:31,671 INFO Using cached transformers-4.35.2-py3-none-any.whl (7.9 MB)
2023-11-20 14:50:31,733 INFO Using cached safetensors-0.4.0-cp310-none-win_amd64.whl (277 kB)
2023-11-20 14:50:31,734 INFO Using cached accelerate-0.24.1-py3-none-any.whl (261 kB)
2023-11-20 14:50:31,734 INFO Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
2023-11-20 14:50:31,734 INFO Using cached scipy-1.11.4-cp310-cp310-win_amd64.whl (44.1 MB)
2023-11-20 14:50:31,768 INFO Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
2023-11-20 14:50:31,824 INFO Using cached psutil-5.9.6-cp37-abi3-win_amd64.whl (252 kB)
2023-11-20 14:50:31,824 INFO Using cached huggingface_hub-0.19.4-py3-none-any.whl (311 kB)
2023-11-20 14:50:31,825 INFO Using cached fsspec-2023.10.0-py3-none-any.whl (166 kB)
2023-11-20 14:50:31,825 INFO Using cached packaging-23.2-py3-none-any.whl (53 kB)
2023-11-20 14:50:31,825 INFO Using cached regex-2023.10.3-cp310-cp310-win_amd64.whl (269 kB)
2023-11-20 14:50:31,825 INFO Using cached tokenizers-0.15.0-cp310-none-win_amd64.whl (2.2 MB)
2023-11-20 14:50:32,512 INFO Installing collected packages: trampoline, tqdm, scipy, safetensors, regex, pyyaml, psutil, packaging, fsspec, einops, attrs, huggingface-hub, torchsde, tokenizers, accelerate, transformers
2023-11-20 14:50:43,014 INFO Attempting uninstall: fsspec
2023-11-20 14:50:43,014 INFO Found existing installation: fsspec 2023.4.0
2023-11-20 14:50:43,077 INFO Uninstalling fsspec-2023.4.0:
2023-11-20 14:50:43,077 INFO Successfully uninstalled fsspec-2023.4.0
2023-11-20 14:51:01,856 INFO Successfully installed accelerate-0.24.1 attrs-23.1.0 einops-0.7.0 fsspec-2023.10.0 huggingface-hub-0.19.4 packaging-23.2 psutil-5.9.6 pyyaml-6.0.1 regex-2023.10.3 safetensors-0.4.0 scipy-1.11.4 tokenizers-0.15.0 torchsde-0.2.6 tqdm-4.66.1 trampoline-0.1.2 transformers-4.35.2
2023-11-20 14:51:02,178 INFO Finished installing ComfyUI
2023-11-20 14:51:02,179 INFO Downloading https://github.com/Fannovel16/comfyui_controlnet_aux/archive/98bf5b70a98577dcbb1227cdf4fbbf022149a1e1.zip to C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\comfyui_controlnet_aux-98bf5b70a98577dcbb1227cdf4fbbf022149a1e1.zip
2023-11-20 14:51:03,453 INFO Extracting C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\.cache\comfyui_controlnet_aux-98bf5b70a98577dcbb1227cdf4fbbf022149a1e1.zip to C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\custom_nodes
2023-11-20 14:51:03,545 ERROR [Errno 2] No such file or directory: 'C:\\Users\\Richard Goldberg\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux-98bf5b70a98577dcbb1227cdf4fbbf022149a1e1\\src\\controlnet_aux\\normalbae\\nets\\submodules\\efficientnet_repo\\geffnet\\activations\\activations_jit.py'
Traceback (most recent call last):
  File "C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 275, in install
    await self._install(cb)
  File "C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 172, in _install
    await _install_if_missing(dir, self._install_custom_node, pkg, network, cb)
  File "C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 547, in _install_if_missing
    raise e
  File "C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 544, in _install_if_missing
    await installer(*args)
  File "C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 244, in _install_custom_node
    await _extract_archive(pkg.name, resource_zip_path, folder.parent, cb)
  File "C:\Users\Richard Goldberg\AppData\Roaming\krita\pykrita\ai_diffusion\server.py", line 509, in _extract_archive
    zip_file.extractall(target)
  File "zipfile.py", line 1645, in extractall
  File "zipfile.py", line 1699, in _extract_member
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Richard Goldberg\\AppData\\Roaming\\krita\\pykrita\\ai_diffusion\\.server\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux-98bf5b70a98577dcbb1227cdf4fbbf022149a1e1\\src\\controlnet_aux\\normalbae\\nets\\submodules\\efficientnet_repo\\geffnet\\activations\\activations_jit.py'
2023-11-20 14:51:03,546 ERROR Installation failed

**Comment by Acly** [comment]
Basically it failed to extract a ZIP. Did you try again? This might be spurious... if it fails at the same step for the same file maybe there is something wrong with the archive (ai_diffusion/.server/.cache/comfyui_controlnet_aux-98bf5b70a98577dcbb1227cdf4fbbf022149a1e1.zip)

**Comment by RichardGoldbergSchool** [comment]
Found the likely problem but haven't found a solution yet. The likely problem is that windows has a 260 character limit on file paths. I tried enabling longer file path support in power shell using the following command: New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force but that did not have the desired effect. The current file path is 263 characters long so I am attempting to shorten my windows User name unless you know something that's more obvious that I'm missing.

**Comment by Acly** [comment]
You can choose the server installation path freely, it doesn't have to be inside the plugin folder.

(I've run into this stupid path limit often enough I should've thought of it, but damn, how is this still a problem in 2023...)

**Comment by RichardGoldbergSchool** [comment]
And there's the obvious solution that I was missing hahaha. That fixed it. Thank you!

**Comment by KillyTheNetTerminal** [comment]
Sorry but how can I select "server installation path freely"
