### ISSUE TITLE
Errore se cerco di usare CUDA (NVIDIA GPU)

### ISSUE THREAD

**Issue by StefanoKKKK** [Acly/krita-ai-diffusion#875]
Ciao, se se cerco di usare CUDA (NVIDIA GPU) mi da questo errore
2024-03-26 15:28:35,211 INFO 
2024-03-26 15:28:35,212 ERROR Traceback (most recent call last):
  File "C:\Users\Utente\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\main.py", line 76, in <module>
    import execution
  File "C:\Users\Utente\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "C:\Users\Utente\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\Users\Utente\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\Users\Utente\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\sd.py", line 3, in <module>
    from comfy import model_management
  File "C:\Users\Utente\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\model_management.py", line 118, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\Users\Utente\AppData\Roaming\krita\pykrita\ai_diffusion\.server\ComfyUI\comfy\model_management.py", line 87, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\Users\Utente\AppData\Roaming\krita\
[client.log](https://github.com/user-attachments/files/15973987/client.log)
[server.log](https://github.com/user-attachments/files/15973988/server.log)
pykrita\ai_diffusion\.server\python\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
    _lazy_init()
  File "C:\Users\Utente\AppData\Roaming\krita\pykrita\ai_diffusion\.server\python\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: The NVIDIA driver on your system is too old (found version 9010). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

Qualcuno può aiutarmi?

**Comment by Acly** [comment]
Update NVIDIA driver?
