### ISSUE TITLE
"RuntimeError: This event loop is already running" when clicking thumbnail

### ISSUE THREAD

**Issue by arcusmaximus** [Acly/krita-ai-diffusion#914]
Got this error when clicking on a thumbnail to preview a generated image, while the plugin was still busy generating other images:

```
RuntimeError
Python 3.10.7: D:\Krita\bin\krita.exe
Sat Jul  6 23:17:11 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\...\AppData\Roaming\krita\pykrita\ai_diffusion\eventloop.py in process_python_events()
   10 def process_python_events():
   11     _loop.call_soon(lambda: _loop.stop())
   12     _loop.run_forever()
   13 
   14 
global _loop = <ProactorEventLoop running=True closed=False debug=False>
_loop.run_forever = <bound method ProactorEventLoop.run_forever of <...EventLoop running=True closed=False debug=False>>

 D:\Krita\bin\asyncio\windows_events.py in run_forever(self=<ProactorEventLoop running=True closed=False debug=False>)


 D:\Krita\bin\asyncio\base_events.py in run_forever(self=<ProactorEventLoop running=True closed=False debug=False>)


 D:\Krita\bin\asyncio\base_events.py in _check_running(self=<ProactorEventLoop running=True closed=False debug=False>)

RuntimeError: This event loop is already running
    __cause__ = None
    __class__ = <class 'RuntimeError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of RuntimeError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of RuntimeError object>
    __doc__ = 'Unspecified run-time error.'
    __eq__ = <method-wrapper '__eq__' of RuntimeError object>
    __format__ = <built-in method __format__ of RuntimeError object>
    __ge__ = <method-wrapper '__ge__' of RuntimeError object>
    __getattribute__ = <method-wrapper '__getattribute__' of RuntimeError object>
    __gt__ = <method-wrapper '__gt__' of RuntimeError object>
    __hash__ = <method-wrapper '__hash__' of RuntimeError object>
    __init__ = <method-wrapper '__init__' of RuntimeError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of RuntimeError object>
    __lt__ = <method-wrapper '__lt__' of RuntimeError object>
    __ne__ = <method-wrapper '__ne__' of RuntimeError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of RuntimeError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of RuntimeError object>
    __repr__ = <method-wrapper '__repr__' of RuntimeError object>
    __setattr__ = <method-wrapper '__setattr__' of RuntimeError object>
    __setstate__ = <built-in method __setstate__ of RuntimeError object>
    __sizeof__ = <built-in method __sizeof__ of RuntimeError object>
    __str__ = <method-wrapper '__str__' of RuntimeError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('This event loop is already running',)
    with_traceback = <built-in method with_traceback of RuntimeError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\krita\pykrita\ai_diffusion\eventloop.py", line 12, in process_python_events
    _loop.run_forever()
  File "asyncio\windows_events.py", line 321, in run_forever
  File "asyncio\base_events.py", line 590, in run_forever
  File "asyncio\base_events.py", line 582, in _check_running
RuntimeError: This event loop is already running
```

**Comment by Acly** [comment]
Fixed in [1.20.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.20.0)
