### ISSUE TITLE
Error using NSFW

### ISSUE THREAD

**Issue by gmf1982** [Acly/krita-ai-diffusion#982]
An error occurred when I turned on the NSFW option and the following message was returned. Does anyone know the reason? Thanks!

!!! Exception during processing!!! axes don't match array
Traceback (most recent call last):
  File "D:\AI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\AI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\AI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\AI\ComfyUI\custom_nodes\comfyui-tooling-nodes\nsfw.py", line 141, in check
    input = self.models.feature_extractor(image, do_rescale=False, return_tensors="pt")
  File "D:\AI\ComfyUI\venv\lib\site-packages\transformers\image_processing_utils.py", line 446, in __call__
    return self.preprocess(images, **kwargs)
  File "D:\AI\ComfyUI\venv\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 318, in preprocess
    images = [self.resize(image=image, size=size, resample=resample) for image in images]
  File "D:\AI\ComfyUI\venv\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 318, in <listcomp>
    images = [self.resize(image=image, size=size, resample=resample) for image in images]
  File "D:\AI\ComfyUI\venv\lib\site-packages\transformers\models\clip\image_processing_clip.py", line 144, in resize
    return resize(image, size=output_size, resample=resample, data_format=data_format, **kwargs)
  File "D:\AI\ComfyUI\venv\lib\site-packages\transformers\image_transforms.py", line 275, in resize
    image = to_pil_image(image)
  File "D:\AI\ComfyUI\venv\lib\site-packages\transformers\image_transforms.py", line 153, in to_pil_image
    image = to_channel_dimension_format(image, ChannelDimension.LAST)
  File "D:\AI\ComfyUI\venv\lib\site-packages\transformers\image_transforms.py", line 84, in to_channel_dimension_format
    image = image.transpose((1, 2, 0))
ValueError: axes don't match array

**Comment by Acly** [comment]
Interesting, haven't seen that. It's just basic Generate workflow? If you can provide a workflow.json dump it might help to reproduce.

Which version of transformers are you using?
```
pip list

-> transformers              4.43.3
```

**Comment by gmf1982** [comment]
> Interesting, haven't seen that. It's just basic Generate workflow? If you can provide a workflow.json dump it might help to reproduce.
> 
> Which version of transformers are you using?
> 
> ```
> pip list
> 
> -> transformers              4.43.3
> ```

The version of transformers I am using is 4.26.1, and it was solved after upgrading to 4.43.3. Thank you so much!
