### ISSUE TITLE
Error when selecting region prompt linked to empty layer group

### ISSUE THREAD

**Issue by arcusmaximus** [Acly/krita-ai-diffusion#990]
```
IndexError
Python 3.10.7: D:\Krita\bin\krita.exe
Sat Jul 27 20:24:28 2024

A problem occurred in a Python script.  Here is the sequence of
function calls leading up to the error, in the order they occurred.

 C:\Users\...\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py in _activate_region(self=<ai_diffusion.ui.region.RegionPromptWidget object>, region=<ai_diffusion.region.Region object>)
  500 
  501     def _activate_region(self, region: RootRegion | Region):
  502         self._regions.active = region
  503         self._prompt.focus()
  504 
self = <ai_diffusion.ui.region.RegionPromptWidget object>
self._regions = <ai_diffusion.region.RootRegion object>
self._regions.active = <ai_diffusion.region.Region object>
region = <ai_diffusion.region.Region object>

 C:\Users\...\AppData\Roaming\krita\pykrita\ai_diffusion\region.py in active(self=<ai_diffusion.region.RootRegion object>, region=<ai_diffusion.region.Region object>)
  195             self._active = region
  196             self.active_changed.emit(region)
  197             self._track_layer(region)
  198 
  199     @property
self = <ai_diffusion.region.RootRegion object>
self._track_layer = <bound method RootRegion._track_layer of <ai_diffusion.region.RootRegion object>>
region = <ai_diffusion.region.Region object>

 C:\Users\...\AppData\Roaming\krita\pykrita\ai_diffusion\region.py in _track_layer(self=<ai_diffusion.region.RootRegion object>, region=<ai_diffusion.region.Region object>)
  310                 target = region.first_layer
  311                 if target.type is LayerType.group:
  312                     target = target.child_layers[-1]
  313                 self.layers.active = target
  314 
target = <ai_diffusion.layer.Layer object>
target.child_layers = []
IndexError: list index out of range
    __cause__ = None
    __class__ = <class 'IndexError'>
    __context__ = None
    __delattr__ = <method-wrapper '__delattr__' of IndexError object>
    __dict__ = {}
    __dir__ = <built-in method __dir__ of IndexError object>
    __doc__ = 'Sequence index out of range.'
    __eq__ = <method-wrapper '__eq__' of IndexError object>
    __format__ = <built-in method __format__ of IndexError object>
    __ge__ = <method-wrapper '__ge__' of IndexError object>
    __getattribute__ = <method-wrapper '__getattribute__' of IndexError object>
    __gt__ = <method-wrapper '__gt__' of IndexError object>
    __hash__ = <method-wrapper '__hash__' of IndexError object>
    __init__ = <method-wrapper '__init__' of IndexError object>
    __init_subclass__ = <built-in method __init_subclass__ of type object>
    __le__ = <method-wrapper '__le__' of IndexError object>
    __lt__ = <method-wrapper '__lt__' of IndexError object>
    __ne__ = <method-wrapper '__ne__' of IndexError object>
    __new__ = <built-in method __new__ of type object>
    __reduce__ = <built-in method __reduce__ of IndexError object>
    __reduce_ex__ = <built-in method __reduce_ex__ of IndexError object>
    __repr__ = <method-wrapper '__repr__' of IndexError object>
    __setattr__ = <method-wrapper '__setattr__' of IndexError object>
    __setstate__ = <built-in method __setstate__ of IndexError object>
    __sizeof__ = <built-in method __sizeof__ of IndexError object>
    __str__ = <method-wrapper '__str__' of IndexError object>
    __subclasshook__ = <built-in method __subclasshook__ of type object>
    __suppress_context__ = False
    __traceback__ = <traceback object>
    args = ('list index out of range',)
    with_traceback = <built-in method with_traceback of IndexError object>

The above is a description of an error in a Python program.  Here is
the original traceback:

Traceback (most recent call last):
  File "C:\Users\...\AppData\Roaming\krita\pykrita\ai_diffusion\ui\region.py", line 502, in _activate_region
    self._regions.active = region
  File "C:\Users\...\AppData\Roaming\krita\pykrita\ai_diffusion\region.py", line 197, in active
    self._track_layer(region)
  File "C:\Users\...\AppData\Roaming\krita\pykrita\ai_diffusion\region.py", line 312, in _track_layer
    target = target.child_layers[-1]
IndexError: list index out of range
```

To reproduce:
* Create a new Krita document
* Draw anything in the default "Paint Layer 1" and click "Add Region."
* Type any text for the general prompt and the region prompt.
* Generate an image.
* Click Apply - this creates a new layer group.
* Move the two layers inside the group to the top (so they sit above it instead).
* Click the general prompt textbox, then the region textbox.

Using version 1.21.0.

**Comment by Acly** [comment]
Fixed in [v1.22.0](https://github.com/Acly/krita-ai-diffusion/releases/tag/v1.22.0)
