### ISSUE TITLE
Error Could not list available languages for translation: Error transferring http://127.0.0.1:8188/api/etn/languages - server replied: Not Found

### ISSUE THREAD

**Issue by Regare** [Acly/krita-ai-diffusion#992]
### Local Managed Server works, i can use ComfyUI on the server  but it doesn't connect to Krita. 
Server running - Connection error: Connection Established, but the server is missing one or more custom node
![image](https://github.com/user-attachments/assets/8c3c39e9-852c-4f2d-ad46-16c3477b4bf3)

**on the client.log:**
```
2024-07-28 03:41:22,004 INFO Starting server with python -su -Xutf8 main.py
2024-07-28 03:41:38,257 INFO Connecting to http://127.0.0.1:8188
2024-07-28 03:41:38,321 ERROR Could not list available languages for translation: Error transferring http://127.0.0.1:8188/api/etn/languages - server replied: Not Found
```
how do i fix this?

**Comment by Marksusu** [comment]
https://github.com/Acly/krita-ai-diffusion/discussions/867

你可以试试这里提供的方法

**Comment by Acly** [comment]
Usually it means the server (comfyui-tooling-nodes in particular) is not updated.

Since you are using managed server, it should have performed the update after you installed the latest plugin version. Did it not ask for an update? Or did something go wrong during update?

To fix you could try to go to folder where you installed the server, and delete just `ComfyUI/custom_nodes/comfyui-tooling-nodes`. When you restart Krita it should ask to re-install the missing nodes.

**Comment by Regare** [comment]
i tried reinstall the nodes on managed server, it doesn't work, it works after i tried to `pip install ctranslate2` manually on python and on `ComfyUI/custom_nodes/comfyui-tooling-nodes`.

**Comment by Acly** [comment]
Would be interesting to know what your client.log for installation is. For me it is:
```
2024-07-24 17:43:12,287 INFO Downloading https://github.com/Acly/comfyui-tooling-nodes/archive/5bad00f72f13e6a18ccbf882a660800bc3897aee.zip to C:\Dev\krita-ai-diffusion\tests\server\.cache\comfyui-tooling-nodes-5bad00f72f13e6a18ccbf882a660800bc3897aee.zip
2024-07-24 17:43:12,833 INFO Extracting C:\Dev\krita-ai-diffusion\tests\server\.cache\comfyui-tooling-nodes-5bad00f72f13e6a18ccbf882a660800bc3897aee.zip to C:\Dev\krita-ai-diffusion\tests\server\ComfyUI\custom_nodes
2024-07-24 17:43:12,861 INFO Executing C:\Dev\krita-ai-diffusion\tests\server\python\python.exe -su -m pip install -r C:\Dev\krita-ai-diffusion\tests\server\ComfyUI\custom_nodes\comfyui-tooling-nodes\requirements.txt
2024-07-24 17:43:13,633 INFO Collecting argostranslate (from -r C:\Dev\krita-ai-diffusion\tests\server\ComfyUI\custom_nodes\comfyui-tooling-nodes\requirements.txt (line 2))
2024-07-24 17:43:13,695 INFO Using cached argostranslate-1.9.6-py3-none-any.whl.metadata (10 kB)
2024-07-24 17:43:13,864 INFO Collecting ctranslate2<5,>=4.0 (from argostranslate->-r C:\Dev\krita-ai-diffusion\tests\server\ComfyUI\custom_nodes\comfyui-tooling-nodes\requirements.txt (line 2))
2024-07-24 17:43:13,864 INFO Using cached ctranslate2-4.3.1-cp310-cp310-win_amd64.whl.metadata (10 kB)
```
ie. ctranslate2 is installed as a dependency already

**Comment by brisfan** [comment]
Hi,
I have the same problem on a mac M1 running on Sonoma 14.4.1 : 

`Server running - Connection error: Connection established, but the server is missing one or more custom node`

Can someone explain to me how to fix it? Excuse me in advance, I need a simple explanation. I don't have a very high level in this field of computing.



**On the client log :**
2024-07-30 08:11:29,307 INFO Loaded 10 sampler presets from /Users/brisfan/Library/Application Support/krita/pykrita/ai_diffusion/presets/samplers.json
2024-07-30 08:11:29,319 INFO Extension initialized, Version: 1.21.0, Python: 3.10.7 (main, Dec  7 2023, 11:44:20) [Clang 13.0.0 (clang-1300.0.29.30)]
2024-07-30 08:11:29,319 INFO Loading settings from /Users/brisfan/Library/Application Support/krita/ai_diffusion/settings.json
2024-07-30 08:11:29,319 INFO Found server installation v1.21.0 at /Users/brisfan/Library/Application Support/krita/ai_diffusion/server
2024-07-30 08:11:30,496 INFO Starting server with python -su -Xutf8 main.py
2024-07-30 08:11:34,243 INFO Connecting to http://127.0.0.1:8188

**On the server log :**
2024-07-30 08:11:32,000 INFO Total VRAM 8192 MB, total RAM 8192 MB
2024-07-30 08:11:32,000 INFO pytorch version: 2.3.1
2024-07-30 08:11:32,001 INFO Set vram state to: SHARED
2024-07-30 08:11:32,001 INFO Device: mps
2024-07-30 08:11:32,680 INFO Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-07-30 08:11:32,700 INFO /Users/brisfan/Library/Application Support/krita/ai_diffusion/server/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
2024-07-30 08:11:32,700 INFO warnings.warn(
2024-07-30 08:11:33,444 INFO [Prompt Server] web root: /Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/web
2024-07-30 08:11:34,036 INFO [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: /Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts[0m
2024-07-30 08:11:34,037 INFO [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-07-30 08:11:34,037 INFO [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-07-30 08:11:34,117 INFO DWPose: Onnxruntime with acceleration providers detected
2024-07-30 08:11:34,197 INFO Traceback (most recent call last):
2024-07-30 08:11:34,197 INFO File "/Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/nodes.py", line 1931, in load_custom_node
2024-07-30 08:11:34,197 INFO module_spec.loader.exec_module(module)
2024-07-30 08:11:34,197 INFO File "<frozen importlib._bootstrap_external>", line 850, in exec_module
2024-07-30 08:11:34,197 INFO File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2024-07-30 08:11:34,197 INFO File "/Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes/comfyui-tooling-nodes/__init__.py", line 1, in <module>
2024-07-30 08:11:34,197 INFO from . import api, nodes, tile, region, nsfw, translation
2024-07-30 08:11:34,197 INFO File "/Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes/comfyui-tooling-nodes/nsfw.py", line 77, in <module>
2024-07-30 08:11:34,197 INFO class CachedModels:
2024-07-30 08:11:34,197 INFO File "/Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes/comfyui-tooling-nodes/nsfw.py", line 78, in CachedModels
2024-07-30 08:11:34,197 INFO _instance: WeakRef | None = None
2024-07-30 08:11:34,197 INFO TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
2024-07-30 08:11:34,197 INFO 
2024-07-30 08:11:34,197 INFO Cannot import /Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes/comfyui-tooling-nodes module for custom nodes: unsupported operand type(s) for |: 'type' and 'NoneType'
2024-07-30 08:11:34,217 INFO 
2024-07-30 08:11:34,217 INFO Import times for custom nodes:
2024-07-30 08:11:34,217 INFO 0.0 seconds: /Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes/websocket_image_save.py
2024-07-30 08:11:34,217 INFO 0.0 seconds: /Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes/comfyui-inpaint-nodes
2024-07-30 08:11:34,217 INFO 0.0 seconds: /Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-07-30 08:11:34,217 INFO 0.1 seconds (IMPORT FAILED): /Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes/comfyui-tooling-nodes
2024-07-30 08:11:34,218 INFO 0.5 seconds: /Users/brisfan/Library/Application Support/krita/ai_diffusion/server/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-07-30 08:11:34,218 INFO 
2024-07-30 08:11:34,236 INFO Starting server
2024-07-30 08:11:34,236 INFO 
2024-07-30 08:11:34,236 INFO To see the GUI go to: http://127.0.0.1:8188
